### ISSUE TITLE
Crash with latest Galacticraft (after build 210)

### ISSUE THREAD

**Issue by PromanSEW** [BuildCraft/BuildCraft#4446] opened 2019-07-26 15:30 UTC
BuildCraft version: 7.99.24.1
Forge version: 1.12.2-14.23.5.2838
Link to crash report or log: https://gist.github.com/PromanSEW/2d1ed4e41e5c8f5b15275f78abedbb8d
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Run with latest Galacticraft
Additional information: Galacticraft 4.0.2.218
Galacticraft 4.0.2.210 works fine, if there is bug in it, please close issue.

**Comment by AlexIIL** [comment] 2019-07-26 15:51
I think this is a bug in GalaxySpace, you'd probably need to report this to them rather than buildcraft (This is likely caused by this commit: https://github.com/micdoodle8/Galacticraft/commit/a4fe67c8ba8ef1df211065cfce87d8e0c5129e27#diff-a81cffd4bbb9094b278023d97eb4dab1, however this *could* be fixed in galacticraft if they re-added the constructor that was removed)

**Closed** 2019-07-27 07:49 UTC
Labels: type: bug, type: mod compat, version: 1.12.2
