### ISSUE TITLE
BuildcraftCore/LIB faill on startup

### ISSUE THREAD

**Issue by Crosus97** [BuildCraft/BuildCraft#4330] opened 2019-01-20 23:50 UTC
BuildCraft version: _7.99.21_
Forge version: _forge-14.23.5.2807_
Link to crash report or log: 
[crash-2019-01-21_00.32.29-client.txt](https://github.com/BuildCraft/BuildCraft/files/2777154/crash-2019-01-21_00.32.29-client.txt)

Singleplayer or multiplayer: Launching Minecraft

Steps to reproduce: 
launch buildcraft (core - transport- compat-builders-energy)
when load.. the client crash (Adjunt crash report)
the game request buildcraftlib...

Additional information: 
when i add buildcraftlib the game said me, i have 2 duplicated mods
[latest.log](https://github.com/BuildCraft/BuildCraft/files/2777157/latest.log)

when i launch without BuilcraftCore (let libs like core since forge says they are the same mod)
all the modules need buildcraft core   -.-
![ca41f1b5ba3b4c53d73e7b3a5488eab5](https://user-images.githubusercontent.com/46854222/51446712-1f1d2300-1d16-11e9-93e0-e7a8c8ae9c8f.png)
[latest.log](https://github.com/BuildCraft/BuildCraft/files/2777165/latest.log)

**Comment by AlexIIL** [comment] 2019-01-20 23:59
The first part (buildcraftlib crashing) is caused by #4324, and can be temporarily fixed by either downgrading to 7.99.20, or waiting for 7.99.22 to come out, or downloading the "buildcraft-all-7.99.21.jar" file by itself (which includes all modules).

The second part is caused by our odd jar embedding structure: "buildcraft-lib-7.99.21.jar" contains 1 mod: `buildcraftlib`, but "buildcraft-core-7.99.21.jar" contains 2 mods: `buildcraftlib` and `buildcraftcore`. (The "buildcraft-all.7.99.21.jar" file contains all 9 modules: `lib`, `core`, `builders`, `energy`, `factory`, `robotics`, `silicon`, `transport`, and `compat`).

**Comment by AlexIIL** [comment] 2019-01-21 18:57
Oh right ok, apparently that bug has been in for a while before it was fixed then. So there's really little else that I can recommend other than "wait for me".

However `"cause me a constant drop frames"` - what sort of frame drops? That sounds like another bug that I need to fix :p.

(It might be an issue with too many animated fluid sprites that are added by the energy module that you can turn off in `config/Performance/enableAnimatedSprites`). Although if that doesn't work you can find out by opening up and navigating around the debug pie to find what parts of it are more expensive in one part than other bits.

**Closed** 2019-04-21 09:58 UTC
Labels: status: duplicate, status: fixed/implemented in dev, type: bug, version: 1.12.2
