### ISSUE TITLE
Issue with compatibility of Mekanisms Generators and Buildcraft V1.11.2

### ISSUE THREAD

**Issue by Tylerun** [BuildCraft/BuildCraft#3728] opened 2017-07-12 18:46 UTC
Buildcraft 7.99.6
Mekanism 9.3.2.307
Mekanism Generators 9.3.2.307
Forge 13.20.1.2393

Hey everyone. So I have a issue with Mekanism Generators and Buildcraft crashing. Seems buildcraft is causing the issue because generators works without it. 

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MekanismGenerators (mekanismgenerators)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.fuels.IFuel.getFluid()Lnet/minecraftforge/fluids/Fluid;

[crash-2017-07-12_13.41.11-client.txt](https://github.com/BuildCraft/BuildCraft/files/1142973/crash-2017-07-12_13.41.11-client.txt)

**Comment by AEnterprise** [comment] 2017-07-12 18:48
duplicate of #3716 mekanism needs to update to the latest api and it will be fixed in the next mekanism release

**Closed by AEnterprise** 2017-07-12 18:48 UTC
