### ISSUE TITLE
Crash when trying to rebuild refinery from blueprint.

### ISSUE THREAD

**Issue by golyalpha** [BuildCraft/BuildCraft#4079] opened 2018-03-14 08:18 UTC
BuildCraft version: Alpha 7.99.15 (MC 1.12.2)
Forge version: 1.12.2-14.23.2.2611
Link to crash report or log: [Gist](https://gist.github.com/golyalpha/f6995e09b388e3d041a622fbc7af0028)
Singleplayer or multiplayer: SP
#### Steps to reproduce:
 - Build a refinery with two engines (stirling and combustion) one distillery one heat exchanger and a pump with infinite water source. Stirling engine powers the pump and combustion engine, filled with cool fuel, powers the distillery.  
 - Refine one batch of 16 B of oil (searing), both engines filled up at the start.  
 - Make a blueprint of the entire thing (including the infinite water source)
 - Try to build it in a builder.

#### Additional information: 
If I manage to boot up the world, and prevent it from crashing, I'll post a download link. I'll also try to post a download link for the blueprint file (I assume it's stored alongside the save).  
Keep in mind, the world used was superflat with "Redstone Ready" preset.
Also, there were a bunch of logic gates, pulsars and signal wires.

**Comment by golyalpha** [comment] 2018-03-14 09:48
The world couldn't load, so I removed the build site in MCEdit, trying to load it up now, if it works, I'm gonna change this post with the link to the save.

**Comment by LuigiHutch** [comment] 2018-03-14 09:52
Please update the bc version number in your issue as 7.99 is not a completed version number

Just an FYI: 
As shown by the builders recipe being removed in 7.99.15, the builder is not really ready at all, let alone for survival (along with a few other things). The builder currently only 'properly' supports vanilla blocks and and doesn't even support BC blocks themselves so don't expect it to work correctly.

Duplicate of https://github.com/BuildCraft/BuildCraft/issues/4076 ?

**Comment by golyalpha** [comment] 2018-03-14 10:01
Ok, managed to fix my world. At a glance, this definitely seems like a duplicate of the issue 4076, but I'd recommend leaving either this one or the other issue open, because closing the issue implies it's been fixed and is working properly now.

**Comment by AlexIIL** [comment] 2018-03-14 11:52
Ok, I've reopened the other issue.

**Closed by AlexIIL** 2018-03-14 11:52 UTC
Labels: status: duplicate, type: bug, type: unported content, version: 1.12.2
