### ISSUE TITLE
crash at start loading

### ISSUE THREAD

**Issue by Hypsellis** [BuildCraft/BuildCraft#3689] opened 2017-06-26 23:34 UTC
I get this crash at loading, I don't know why it happens https://pastebin.com/fyRGn1c8

**Comment by AlexIIL** [comment] 2017-06-26 23:40
One of your coremods is buggy. Can you try removing mods one by one to see which one is the cause? I'd recommend starting with either replacing foamfix with the FoamFixAPI-Lawful version, or removing buildcraft itself and seeing if the crash still happens.

**Comment by Hypsellis** [comment] 2017-06-27 04:39
It is surely caused by Tough As Nails, it surely linked to this issue. https://github.com/Glitchfiend/ToughAsNails/issues/274. Anyway now I get this crash. https://pastebin.com/3x1aXQ9V

**Comment by AEnterprise** [comment] 2017-06-27 07:08
yes and that makes it a duplicate of #3676 and will be fixed for the next version

**Closed by AEnterprise** 2017-06-27 07:08 UTC
Labels: type: bug, type: caused by other mod, version: 1.11.2
