### ISSUE TITLE
Can't pull liquid with bucket from tank 

### ISSUE THREAD

**Issue by Sorinwaker** [BuildCraft/BuildCraft#3781] opened 2017-08-17 01:54 UTC
**Buildcraft** version: 7.99.7
**Forge** version: 1.11.2-13.20.1.2386
No crash just Can't pull liquid with bucket from tank (tried Lava and water). 
Singleplayer/multiplayer: Multiplayer 

Additional information:Was working before the update to 7.99.7 from 7.99.6

update 1 : found a work around if I only have one bucket it work ,when it's stacked bucket it dosent work

**Comment by AEnterprise** [comment] 2017-08-17 05:54
duplicate of https://github.com/BuildCraft/BuildCraft/issues/3729

**Closed by AEnterprise** 2017-08-17 05:54 UTC
