### ISSUE TITLE
BuildCraft block loadig error

### ISSUE THREAD

**Issue by DeadMazay2000** [BuildCraft/BuildCraft#4087] opened 2018-03-18 16:55 UTC
BuildCraft version: 
Forge version: 
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information:

**Comment by AlexIIL** [comment] 2018-03-18 17:04
Can I assume that opening this was a mistake? (and all details are in #4088 )

**Comment by AEnterprise** [comment] 2018-03-19 08:12
closing as duplicate of 4088

**Closed by AEnterprise** 2018-03-19 08:12 UTC
