### ISSUE TITLE
Builder problem in the end.

### ISSUE THREAD

**Issue by Mornyngstar** [BuildCraft/BuildCraft#3284] opened 2016-04-02 17:13 UTC
I was building a redstone piston enderman farm in the end. It is located 300 blocks away from the spawn island. When the builder reached the 128 block height it stopped working. I reset it/took it apart and moved it up (it was following a path marker line for building each layer. It would destroy blocks in the volume of area and then stop. I reset it as a single layer to build without the path markers and it destroyed the block area volume(air blocks) and stopped again. 
Just an idea but since it is at the 128 layer area could it have interference from clouds?

In case of possible conflicts:
Mods:
Buildcraft 7.1.15
Buildcraft-compat 7.1.3
Chicken Chunks 1.7.10-1.3.4.16-universal
CodeChickenCore-1-7-10-1.0.4.29-universal
CoFHCore 1.7.10-3.1.2-325
CoFHLib 1.7.10-1.1.1-181
Forestry 1.7.10-4.2.11.59
NetherOres 1.7.10-2.3.1-22
NotEnoughItems 1.7.10-1.0.3.74-universal
Reis-Minimap-Mod 1.7.10
ThermalDynamics 1.7.10-1.1.0-16
ThermalExpansion 1.7.10-4.1.2-240
ThermalFoundation 1.7.10-1.2.3-112

**Comment by bilt1999** [comment] 2016-04-05 11:35
I had the same issue ones. I used the same mods that u are using. I fixed this issue by making sure that all mods were up to date. When I had updated all the mods. The problem went away. I hope this helps , if not let me know and I'll see if I can help

**Comment by AlexIIL** [comment] 2016-06-12 13:18
Duplicate of #3262, sorry for not responding beforehand (although its being fixed in the latest branches)

**Closed by AlexIIL** 2016-06-12 13:18 UTC
