### ISSUE TITLE
Filler Recipe Not Working/item wont work when spawned. [1.12.2]

### ISSUE THREAD

**Issue by Crusher04** [BuildCraft/BuildCraft#3971] opened 2018-01-10 23:16 UTC
**BuildCraft** version: 7.99.12
**Forge** version: 1.12.2-14.23.1.2581
Link to crash report or log: (Images)(Not Crashing) https://imgur.com/a/T7OeF
Singleplayer or multiplayer: Both
Additional information: Cannot use the filler when spawned nor craft it.

**Comment by LuigiHutch** [comment] 2018-01-10 23:19
0. There is no such BuildCraft version called 1.12.2
1.  Some recipes in 7.99.x may seem missing and do not show in JEI, that is either because they are assembley table recipes or they are blocks which aren't ready to be used in survival. #3941
2. You didn't connect it to landmarks

**Comment by Crusher04** [comment] 2018-01-10 23:23
0. Fixed.

1. Alright, i can't find any recipe for the filler. How are we supposed to craft it if nowhere on the wiki states the new recipe. That's if the recipe has changed.

2. Forgot about landmarks. Machine does seem to respond. More testing inbound. updated image: https://imgur.com/a/T7OeF

**Comment by Crusher04** [comment] 2018-01-10 23:25
Recreating question 1. Is the Filler supposed to not be used in this update?

**Comment by LuigiHutch** [comment] 2018-01-10 23:27
1. As stated in my statement above dumbed down; Some recipes in 7.99.x may seem missing, that is they are blocks which aren't ready to be used in survival.

2. It does work, drag the icons in like gates

**Comment by LuigiHutch** [comment] 2018-01-10 23:30
This is basically a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3969.  Please search before making issues :)

**Comment by Crusher04** [comment] 2018-01-10 23:31
Alright. Misinterpreted what was stated above. Thought you were just referencing recipes will be missing in JEI. My apologies. 

I Saw that now. Thanks! Closing issue.

**Closed** 2018-01-10 23:31 UTC
