### ISSUE TITLE
Missing Robot

### ISSUE THREAD

**Issue by Dragonox77** [BuildCraft/BuildCraft#3871] opened 2017-11-26 13:17 UTC
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2554
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: SinglePlayer

Additional information:
Hello, i just want to know if it is normal to don't have the robot in this version of buildcraft ?
Thank you and sorry for my bad english ^^

**Comment by LuigiHutch** [comment] 2017-11-26 13:18
Robots haven't been ported yet, they will come in a future release when they are done

**Comment by AEnterprise** [comment] 2017-11-26 13:21
duplicate of #3755

**Closed by AEnterprise** 2017-11-26 13:21 UTC

**Comment by Dragonox77** [comment] 2017-11-28 16:06
Ok thank you.
