### ISSUE TITLE
leadstone fluxduct can't connect to quarry

### ISSUE THREAD

**Issue by LizzardWizard** [BuildCraft/BuildCraft#3872] opened 2017-11-26 22:29 UTC
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.0.2552
Link to crashreport or log: none
Singleplayer/multiplayer: multiplayer

Additional information: tried using coal generator, did not work

**Comment by LuigiHutch** [comment] 2017-11-26 22:31
Thanks for the report. This is actually a duplicate of #3760

**Closed** 2017-11-27 08:29 UTC

**Comment by SalvadorScalia** [comment] 2018-02-10 03:25
+1 
Leadstone Fluxduct  can not connect to quarry.
