### ISSUE TITLE
Rare chance of a pipe being placed rendering incorrectly

### ISSUE THREAD

**Issue by LuigiHutch** [BuildCraft/BuildCraft#3238] opened 2016-03-14 09:52 UTC
BC 7.2.0

There is a rare chance of a pipe being placed not updating. 
![2016-03-14_09 47 44](https://cloud.githubusercontent.com/assets/9326429/13740729/2abba1aa-e9ca-11e5-9bdc-ab520d7f31ca.png)

To produce this, I just kept placing pipes and it has a rare chance or occuring. That is supposed to be gold transport pipe and it was not over a chunk boundry. It does not update with a block update.

**Comment by MrGraphic** [comment] 2016-03-14 11:28
Same happens after world load with already existing pipes - worth noting that it is not only visual thing as it also brakes gates GUI.
![2016-03-14_11 21 37](https://cloud.githubusercontent.com/assets/4780141/13743072/886ca6e8-e9d7-11e5-8a65-d37d3b6729dc.png)

**Comment by asiekierka** [comment] 2016-03-14 12:09
@MrGraphic - this does not happen to me. Could you try with just BuildCraft?

**Comment by MrGraphic** [comment] 2016-03-14 12:57
@asiekierka it happens sometimes. Also happens without other mods in env but it is very very rare. Leaving area of interest and returning fixes this, same for forcing rerender via pipe wires, same for world reload.

**Comment by AlexIIL** [comment] 2016-03-14 13:00
Yeah its rare and odd and I'm not sure if its a render problem or a networking problem- could be stuff being sent at the wrong time or it could be stuff not updating.

**Comment by asiekierka** [comment] 2016-03-14 19:47
Reproduced the rare chance bit, marking as bug.

**Comment by AEnterprise** [comment] 2016-06-25 09:42
since MC 1.8 messages are handled on a different thread then the main thread, i know BC does special things for networking but probably related

`IThreadListener.addScheduledTask`is to execute code on the main thread, the minecraft client instance or the server `worldserver` both implement that

**Comment by AlexIIL** [comment] 2016-06-25 14:12
Yeah I scrapped the entire BC networking system in favour of forge's own SimpleNetworkHandler and IMessage, which works much better. Oh, and I auto-handle ALL messages on the main thread, a tick or 2 later than normal so this sort of thing shouldn't happen in 8.0.x (and MCMP handles all init stuff anyway :) )

**Comment by AEnterprise** [comment] 2016-06-25 14:19
this can probably be closed as fixed then

**Closed** 2016-08-31 12:52 UTC
Labels: bug
