### ISSUE TITLE
Buildcraft and Mekanism crash

### ISSUE THREAD

**Issue by LuxerTheGamer** [BuildCraft/BuildCraft#3735] opened 2017-07-15 10:37 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (Inventory Tweaks [1.62].jar)
  PotionCoreFMLLoadingPlugin (Potion Core [1.5.2].jar)
  CCLCorePlugin (Code Chicken Lib [3.0.0.284].jar)
  RBLoadingPlugin (Real Bench [1.3.2].jar)
  LoadingPlugin (Sampler [1.71].jar)
  llibrary (LLibrary [1.7.6].jar)
  literalascension (Literal Ascension [1.0.2.2].jar)
  CreativePatchingLoader (Creative Core [1.7.4].jar)
  TANLoadingPlugin (Tough As Nails [2.1.0.61].jar)
  ForgelinPlugin (Forgelin [1.4.2].jar)
  LoadingPlugin (Quark [r1.2-93].jar)
  AppleCore (Apple Core [2.2.0].jar)
  LoadingPlugin (Resource Loader [1.5.2].jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (Foam Fix [0.7.0][Anarchy].jar)
  CoFH Loading Plugin (CoFH Core [4.2.6.14].jar)
  CTMCorePlugin (Connected Textures [0.2.0.8].jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 7/15/17 12:31 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MekanismGenerators (mekanismgenerators)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.fuels.IFuel.getFluid()Lnet/minecraftforge/fluids/Fluid;
	at mekanism.generators.common.MekanismGenerators.postInit(MekanismGenerators.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1739258800 bytes (1658 MB) / 3259887616 bytes (3108 MB) up to 8536260608 bytes (8140 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2393 Optifine OptiFine_1.11.2_HD_U_C3 151 mods loaded, 151 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2393.jar) 
	UCHIJ	forge{13.20.1.2393} [Minecraft Forge] (forge-1.11.2-13.20.1.2393.jar) 
	UCHIJ	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJ	potioncore_coremod{1.5.2_for_1.11.2} [Potion Core Coremod] (minecraft.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJ	ccl-entityhook{1.0} [ccl-entityhook] (Code Chicken Lib [3.0.0.284].jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJ	akashictome{1.1-7} [Akashic Tome] (Akashic Tome [1.1-7].jar) 
	UCHIJ	atg{2} [Alternate Terrain Generation] (Alternate Terrain Generation [2.1.7].jar) 
	UCHIJ	craftstudioapi{0.3.0-beta} [CraftStudio API] (Craft Studio API [0.3.0.86].jar) 
	UCHIJ	quark{r1.2-93} [Quark] (Quark [r1.2-93].jar) 
	UCHIJ	cofhcore{4.2.6} [CoFH Core] (CoFH Core [4.2.6.14].jar) 
	UCHIJ	animania{1.2.1} [Animania] (Animania [1.2.1].jar) 
	UCHIJ	applecore{2.2.0} [AppleCore] (Apple Core [2.2.0].jar) 
	UCHIJ	jei{4.5.0.292} [Just Enough Items] (Just Enough Items [4.5.0.292].jar) 
	UCHIJ	appleskin{1.0.7} [AppleSkin] (Apple Skin [1.0.7].jar) 
	UCHIJ	architect{1.2.0.59} [Architect] (Architect [1.2.0.59].jar) 
	UCHIJ	csb_armorstand{1.0.2} [Armor Stand Configurator] (Armor Stand GUI [1.0.2].jar) 
	UCHIJ	autoreglib{1.1-4} [AutoRegLib] (Auto Reg Lib [1.1-4].jar) 
	UCHIJ	barkifier{1.4.1} [Barkifier] (Barkifier [1.4.1].jar) 
	UCHIJ	baubles{1.4.5} [Baubles] (Baubles [1.4.5].jar) 
	UCHIJ	bedbugs{@VERSION@} [Bed Bugs] (Bed Bugs [1.1.7].jar) 
	UCHIJ	betteroverworld{0.6.3} [BetterOverworld] (Better Overworld [0.6.3].jar) 
	UCHIJ	betterquesting{2.4.235} [Better Questing] (Better Questing [2.4.235].jar) 
	UCHIJ	bibliocraft{2.3.2} [BiblioCraft] (Biblio Craft [2.3.2].jar) 
	UCHIJ	biomesoplenty{6.2.0.2267} [Biomes O' Plenty] (Biomes O Plenty [6.2.0.2267].jar) 
	UCHIJ	bibliowoodsbop{2.0} [BiblioWoodBoP] (Biblio Woods [BoP][2.0].jar) 
	UCHIJ	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide API [2.1.1-52].jar) 
	UCHIJ	bloodmagic{1.11-2.1.11-80} [Blood Magic: Alchemical Wizardry] (Blood Magic [2.1.11-80].jar) 
	UCHIJ	botania{r1.9-344} [Botania] (Botania [r1.9-344].jar) 
	UCHIJ	buildcraftlib{7.99.5} [BuildCraft Lib] (Buildcraft [7.99.5].jar) 
	UCHIJ	buildcraftcore{7.99.5} [BuildCraft] (Buildcraft [7.99.5].jar) 
	UCHIJ	buildcraftbuilders{7.99.5} [BC Builders] (Buildcraft [7.99.5].jar) 
	UCHIJ	buildcraftenergy{7.99.5} [BC Energy] (Buildcraft [7.99.5].jar) 
	UCHIJ	buildcraftfactory{7.99.5} [BC Factory] (Buildcraft [7.99.5].jar) 
	UCHIJ	buildcraftrobotics{7.99.5} [BC Robotics] (Buildcraft [7.99.5].jar) 
	UCHIJ	buildcraftsilicon{7.99.5} [BC Silicon] (Buildcraft [7.99.5].jar) 
	UCHIJ	buildcrafttransport{7.99.5} [BC Transport] (Buildcraft [7.99.5].jar) 
	UCHIJ	chisel{MC1.11.2-0.0.13.21} [Chisel] (Chisel [0.0.13.21].jar) 
	UCHIJ	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle [1.2.0.26].jar) 
	UCHIJ	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (Tinker Construct [2.7.0.26].jar) 
	UCHIJ	ceramics{1.11.2-1.2.2b} [Ceramics] (Ceramics [1.2.2b].jar) 
	UCHIJ	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon [3.1.0].jar) 
	UCHIJ	chiselsandbits{13.11} [Chisels & Bits] (Chisels And Bits [13.11].jar) 
	UCHIJ	clayworldgen{1.1.0-1.11} [Clay WorldGen] (Clay World Gen [1.1.0].jar) 
	UCHIJ	codechickenlib{3.0.0.284} [CodeChicken Lib] (Code Chicken Lib [3.0.0.284].jar) 
	UCHIJ	ctm{MC1.11.2-0.2.0.8} [CTM] (Connected Textures [0.2.0.8].jar) 
	UCHIJ	controlling{2.0.5} [Controlling] (Controlling [2.0.5].jar) 
	UCHIJ	cookingforblockheads{5.3.21} [Cooking for Blockheads] (Cooking For Blockheads [5.3.21].jar) 
	UCHIJ	crafttweakerjei{1.0.2} [CraftTweaker JEI Support] (Craft Tweaker [3.0.26].jar) 
	UCHIJ	crafttweaker{3.0.26} [Crafttweaker] (Craft Tweaker [3.0.26].jar) 
	UCHIJ	ctgui{1.0.0} [CT-GUI] (Craft Tweaker [3.0.26].jar) 
	UCHIJ	creativecore{1.7.4} [CreativeCore] (Creative Core [1.7.4].jar) 
	UCHIJ	ceanimals{1.3.1} [Crop-Eating Animals] (Crop Eating Animals [1.3.1].jar) 
	UCHIJ	custommainmenu{2.0.5} [Custom Main Menu] (Custom Main Menu [2.0.5].jar) 
	UCHIJ	cyberware{alpha-0.2.10} [Cyberware] (Cyberware [0.2.10].jar) 
	UCHIJ	earthworks{1.3.4} [Earthworks] (Earthworks [1.3.4].jar) 
	UCHIJ	elementaria{3.0.2} [Elementaria] (Elementaria [3.0.2].jar) 
	UCHIJ	elevatorid{1.3.2} [Elevator Mod] (Elevator [1.3.2].jar) 
	UCHIJ	embers{0.220} [Embers] (Embers [0.220].jar) 
	UCHIJ	tesla{1.3.0.52} [TESLA] (Tesla [1.3.0.52].jar) 
	UCHIJ	theoneprobe{1.4.7} [The One Probe] (The One Probe [1.4.7].jar) 
	UCHIJ	endercrop{1.11-1.3.4} [Ender Crop] (Ender Crop [1.3.4].jar) 
	UCHIJ	entity_hoppers{0.2.0-1.11.2} [Entity Hoppers] (Entity Hoppers [0.2.0].jar) 
	UCHIJ	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (Valkyrie Lib [0.11.0c].jar) 
	UCHIJ	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (Environmental Tech [0.11.0d].jar) 
	UCHIJ	erosion{2.1.2} [Erosion] (Erosion [2.1.2].jar) 
	UCHIJ	etlunar{1.11.2-0.11.0c} [ET Lunar] (Et Lunar [0.11.0c].jar) 
	UCHIJ	extrabitmanipulation{1.11.2-3.0.6} [Extra Bit Manipulation] (Extra Bit Manipulation [3.0.6].jar) 
	UCHIJ	extratweaker{0.4} [ExtraTweaker] (Extra Tweaker [0.4].jar) 
	UCHIJ	zerocore{1.11.2-0.1.0.6} [Zero CORE] (Zero Core [0.1.0.6].jar) 
	UCHIJ	bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (Extreme Reactors [0.4.5.30].jar) 
	UCHIJ	fairylights{2.1.0} [Fairy Lights] (Fairy Lights [2.1.0].jar) 
	UCHIJ	fastleafdecay{v12} [Fast Leaf Decay] (Fast Leaf Decay [v12].jar) 
	UCHIJ	faufil{1.0} [Faucets and Filters] (Faucets and Filters [1.0].jar) 
	UCHIJ	foamfix{@VERSION@} [FoamFix] (Foam Fix [0.7.0][Anarchy].jar) 
	UCHIJ	forgelin{1.4.2} [Forgelin] (Forgelin [1.4.2].jar) 
	UCHIJ	ftgumod{Minecraft 1.11.2} [From the Ground Up] (From The Ground Up [b1.1.7].jar) 
	UCHIJ	fw{1.5.0} [Fullscreen Windowed] (Fullscreen Windowed [1.5.0].jar) 
	UCHIJ	shadowmc{3.7.1} [ShadowMC] (Shadow MC [3.7.5].jar) 
	UCHIJ	funnels{1.2.2} [Funnels] (Funnels [1.2.2].jar) 
	UCHIJ	geomastery{1.1.1} [Geomastery] (Geomastery [1.1.1].jar) 
	UCHIJ	gravestone{1.7.4} [Gravestone Mod] (Gravestone [1.7.4].jar) 
	UCHIJ	hopperducts{1.4.9.2} [Hopper Ducts] (Hopper Ducts [1.4.9.2].jar) 
	UCHIJ	hgp{Release} [Horizontal Glass Panes] (Horizontal Glass Pane [1.1.4].jar) 
	UCHIJ	horsepower{1.4.4} [Horse Power] (Horse Power [1.4.4.29].jar) 
	UCHIJ	immersiveengineering{0.11-63} [Immersive Engineering] (Immersive Engineering [0.11-63].jar) 
	UCHIJ	immersivepetroleum{1.0.7} [Immersive Petroleum] (Immersive Petroleum [1.0.7].jar) 
	UCHIJ	teslacorelib{0.7.3} [Tesla Core Lib] (Tesla Core Lib [0.7.3].jar) 
	UCHIJ	industrialforegoing{1.11.2-0.3} [Industrial Foregoing] (Industrial Foregoing [0.3-16].jar) 
	UCHIJ	mtlib{@VERSION@} [MTLib] (MT Lib [2.0.3].jar) 
	UCHIJ	initialinventory{2.0.2} [InitialInventory] (Initial Inventory [2.0.2].jar) 
	UCHIJ	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (Inventory Tweaks [1.62].jar) 
	UCHIJ	ironchest{1.11.2-7.0.25.815} [Iron Chest] (Iron Chest [7.0.25.815].jar) 
	UCHIJ	journeymap{1.11.2-5.4.7} [JourneyMap] (Journey Map [5.4.7].jar) 
	UCHIJ	je_calculation{1.11.2-2.6.4} [Just Enough Calculation] (Just Enough Calculation [2.6.4].jar) 
	UCHIJ	jehc{1.2.2} [Just Enough HarvestCraft] (Just Enough HarvestCraft [1.2.2].jar) 
	UCHIJ	jeresources{0.6.6.12} [Just Enough Resources] (Just Enough Resources [0.6.6.12].jar) 
	UCHIJ	llibrary{1.7.6} [LLibrary] (LLibrary [1.7.6].jar) 
	UCHIJ	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (Literal Ascension [1.0.2.2].jar) 
	UCHIJ	mcmultipart{2.0.2} [MCMultiPart] (MC MultiPart [2.0.2].jar) 
	UCHIJ	mekanism{9.3.2} [Mekanism] (Mekanism [9.3.2.307].jar) 
	UCHIE	mekanismgenerators{9.3.2} [MekanismGenerators] (Mekanism Generators [9.3.2.307].jar) 
	UCHIJ	modtweaker{3.0.1} [Mod Tweaker] (Mod Tweaker [3.0.1].jar) 
	UCHIJ	moreplates{1.11.2-10.0} [More Plates] (More Plates [10.0].jar) 
	UCHIJ	morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus [3.2.14].jar) 
	UCHIJ	cfm{4.1.2} [MrCrayfish's Furniture Mod] (Mr Crayfish Furniture [4.1.2].jar) 
	UCHIJ	naturescompass{1.3.0} [Nature's Compass] (Natures Compass [1.3.0].jar) 
	UCHIJ	netherportalfix{1.0} [NetherPortalFix] (Nether Portal Fix [4.3.1].jar) 
	UCHIJ	notes{1.1.1} [Notes] (Notes [1.1.1].jar) 
	UCHIJ	p455w0rdslib{1.0.15} [p455w0rd's Library] (P455w0rds Lib [1.0.15].jar) 
	UCHIJ	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft [1.11.2h].jar) 
	UCHIJ	placeableitems{3.0.4.1} [Placeable Items Mod] (Placeable Items [3.0.4.1].jar) 
	UCHIJ	thermalfoundation{2.2.4} [Thermal Foundation] (Thermal Foundation [2.2.4.15].jar) 
	UCHIJ	plustic{5.2.0.0} [PlusTiC] (Plus TiC [5.2.0.0].jar) 
	UCHIJ	potioncore{1.5.2_for_1.11.2} [Potion Core] (Potion Core [1.5.2].jar) 
	UCHIJ	qualitytools{1.0.4_for_1.11.2} [Quality Tools] (Quality Tools [1.0.4].jar) 
	UCHIJ	reauth{3.5.0} [ReAuth] (Re Auth [3.5.0].jar) 
	UCHIJ	thermalexpansion{5.2.5} [Thermal Expansion] (Thermal Expansion [5.2.5.20].jar) 
	UCHIJ	redstonearsenal{2.2.5} [Redstone Arsenal] (Redstone Arsenal [2.2.5.9].jar) 
	UCHIJ	sandro.redstone{1.1c} [Redstone++] (Redstone++ [1.1c].jar) 
	UCHIJ	sandro{1.1a} [Sandro's Core] (Redstone++ [1.1c].jar) 
	UCHIJ	refinedstorage{1.4.19} [Refined Storage] (Refined Storage [1.4.19].jar) 
	UCHIJ	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary [1.3.3.653].jar) 
	UCHIJ	resourceloader{1.5.2} [Resource Loader] (Resource Loader [1.5.2].jar) 
	UCHIJ	roots{0.025} [Roots 2] (Roots 2 [0.025].jar) 
	UCHIJ	ropebridge{2.0.5} [Rope Bridge] (Rope Bridge [2.0.6].jar) 
	UCHIJ	saltmod{1.11.2_a} [Salty Mod] (Salty [1.11.2_a].jar) 
	UCHIJ	sampler{1.71} [Sampling Performance Profiler] (Sampler [1.71].jar) 
	UCHIJ	scannable{1.4.0.23} [Scannable] (Scannable [1.4.0.23].jar) 
	UCHIJ	signpost{1.05.5} [Sign Post] (SignPost [1.05.5].jar) 
	UCHIJ	spartanshields{1.3} [Spartan Shields] (Spartan Shields [1.3a].jar) 
	UCHIJ	spiceoflife{1.3.9} [The Spice of Life] (Spice Of Life [1.3.9].jar) 
	UCHIJ	bq_standard{2.4.132} [Standard Expansion] (Standard Expansion [2.4.132].jar) 
	UCHIJ	storagedrawers{1.11.2-4.2.10} [Storage Drawers] (Storage Drawers [4.2.10].jar) 
	UCHIJ	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (Storage Drawers Extras [2.0.0].jar) 
	UCHIJ	thermaldynamics{2.2.5} [Thermal Dynamics] (Thermal Dynamics [2.2.5.12].jar) 
	UCHIJ	toolbelt{1.6.1} [Tool Belt] (Tool Belt [1.6.1].jar) 
	UCHIJ	torchmaster{1.4.0.45} [TorchMaster] (Torch Master [1.4.0.45].jar) 
	UCHIJ	totemic{1.11.2-0.8.7} [Totemic] (Totemic [0.8.7].jar) 
	UCHIJ	toughasnails{2.1.0.61} [Tough As Nails] (Tough As Nails [2.1.0.61].jar) 
	UCHIJ	tanspit{@VERSION@} [Campfire Spit] (Tough As Nails Spit [1.3].jar) 
	UCHIJ	tanaddons{3.0.9} [Tough Expansion] (Tough Expansion [3.0.9].jar) 
	UCHIJ	undergroundbiomes{1.0.v.18} [Underground Biomes] (Underground Biomes Constructs [1.0.v.19].jar) 
	UCHIJ	vanillafoodpantry{3.2b1} [Vanilla Food Pantry] (Vanilla Food Pantry [3.2b1].jar) 
	UCHIJ	vanillatools{1.0.5} [Vanilla Tools] (Vanilla Tools [1.1x-1.0.6].jar) 
	UCHIJ	wearablebackpacks{2.5.0} [Wearable Backpacks] (Wearable Backpacks [2.5.0].jar) 
	UCHIJ	wolfarmor{1.3.2} [Wolf Armor and Storage] (Wolf Armor [1.3.3.6].jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (Inventory Tweaks [1.62].jar)
  invtweaks.forge.asm.ContainerTransformer
PotionCoreFMLLoadingPlugin (Potion Core [1.5.2].jar)
  com.tmtravlr.potioncore.asm.ArmorHandlerTransformer
CCLCorePlugin (Code Chicken Lib [3.0.0.284].jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
RBLoadingPlugin (Real Bench [1.3.2].jar)
  pw.prok.realbench.asm.RBTransformer
LoadingPlugin (Sampler [1.71].jar)
  
llibrary (LLibrary [1.7.6].jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
literalascension (Literal Ascension [1.0.2.2].jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
CreativePatchingLoader (Creative Core [1.7.4].jar)
  
TANLoadingPlugin (Tough As Nails [2.1.0.61].jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin [1.4.2].jar)
  
LoadingPlugin (Quark [r1.2-93].jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (Apple Core [2.2.0].jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Resource Loader [1.5.2].jar)
  lumien.resourceloader.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (Foam Fix [0.7.0][Anarchy].jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CoFH Loading Plugin (CoFH Core [4.2.6.14].jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CTMCorePlugin (Connected Textures [0.2.0.8].jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.76' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	OptiFine Version: OptiFine_1.11.2_HD_U_C3
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL Standard v6.0.2.zip
	OpenGlVersion: 4.5.0 NVIDIA 384.76
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by AEnterprise** [comment] 2017-07-15 10:39
known mekanism issue, see their issue (aidancbrady/Mekanism#4513) for details. duplicate of #3716

**Closed by AEnterprise** 2017-07-15 10:39 UTC
