### ISSUE TITLE
8.0.X Parts are not connecting to each other automaticly

### ISSUE THREAD

**Issue by forReason** [BuildCraft/BuildCraft#3477] opened 2017-01-11 17:20 UTC
Reproduction with:
- Ironpipe
- Iron fluid pipe

Problem
- Ironpipes wont connect automatically: 
![2017-01-11_19 33 10](https://cloud.githubusercontent.com/assets/12736950/21861498/636adad4-d835-11e6-8ee2-f59014f6cac7.png)
- A  lot of buggy fiddle with the wrench is required as the connection is also not set up properly when using the wrench:
![2017-01-11_19 40 30](https://cloud.githubusercontent.com/assets/12736950/21861611/e513fcdc-d835-11e6-93e4-7183d4b56cda.png)

**Comment by LuigiHutch** [comment] 2017-01-11 17:28
Wrenching pipes to connect to chests I believe is intended to easily decide what inventory they connect to. The engine issue is a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3336

**Comment by forReason** [comment] 2017-01-11 18:39
Updated title and description. Also added a screenshot. after further testing I found out that this only applies to Iron pipes.

**Comment by LuigiHutch** [comment] 2017-01-11 18:41
Intended. Iron pipes are used to control the direction of items, so you have to wrench them in the direction you want the items to go.

**Comment by forReason** [comment] 2017-01-11 18:41
ah okay. thx

**Comment by AlexIIL** [comment] 2017-01-11 18:44
...wait this new behaviour isn't a bug? I find it annoying if I've only got a single chest to connect a pipe to, and there's a "TODO" bit in code

**Comment by AlexIIL** [comment] 2018-04-16 17:40
...This one was left for a *long* time, but it's finally fixed for 7.99.17.

**Closed** 2018-05-06 17:40 UTC
Labels: status: fixed/implemented in dev
