### ISSUE TITLE
cant pick up oil or water

### ISSUE THREAD

**Issue by razor900** [BuildCraft/BuildCraft#3663] opened 2017-06-10 02:28 UTC
i run the latest version of buildcraft and 1.11.2 of minecraft. i only have bulidcraft and used forge as my uploader. whenever i click on a liquid (oil,water etc) it does not fill my bucket. does anyone else have this issue or have a fix? thanks in advance.

**Comment by AEnterprise** [comment] 2017-06-10 08:24
this works just fine in dev

**Comment by razor900** [comment] 2017-06-10 13:37
Im sure this is facepalm worthy, but what is dev?

**Comment by AEnterprise** [comment] 2017-06-10 13:47
in development, it works there and it also works for others,

are sure you don't have any other mods installed?

**Comment by razor900** [comment] 2017-06-10 14:13
My mod list says 'minecraft, minecraft coder pack ,forge mod loader ,mercurius updater, buildcraft'

**Comment by afdw** [comment] 2017-06-10 14:24
So if you remove BC and reproduce same things with water you'll can pick up it, yes?

**Comment by Restproof** [comment] 2017-06-23 09:20
I have somewhat the same problem as the OP. But only for oil. Water and lava work properly.
I don't know if I should open another issue with that.
I'm using 7.99.4, no other mods installed.

To be more specific, I can pick up oil from an oil geyser/deposit with a bucket but it doesn't get turned into a bucket of oil. I have to use the oil bucket from creative mode to deposit into cobustion engines to make them work.

**Comment by AEnterprise** [comment] 2017-06-23 09:29
@Restproof sounds like a different issue, please make a new issue with some more information (like what the bucket does turn into since you pick it up, other mods installed, ...)

@razor900 have you tried what heapens yet if you remove BC and try to pick up water in that world?

**Comment by AEnterprise** [comment] 2017-06-30 19:06
@razor900 since you cannot pick up any fuels it sounds like another mod is messing up the fluidregistry completely

also we need more information like mods installed (see above) so i'm closing this for now

**Closed by AEnterprise** 2017-06-30 19:06 UTC
Labels: version: 1.11.2
