### ISSUE TITLE
ProjectE and AutoCrafter

### ISSUE THREAD

**Issue by Stokykyle** [BuildCraft/BuildCraft#3965] opened 2018-01-07 19:32 UTC
**BuildCraft** version:  7.99.13
**Forge** version: 14.23.1.2585
Link to crash report or log: 
Singleplayer or multiplayer: Multiplayer
Additional information: 
When using ProjectE and the AutoWorkbench i have found when inserting the philosopher's stone into it duplicates the philosopher's stone and fills it's inventory with them.

**Comment by AEnterprise** [comment] 2018-01-07 19:37
for future reference: please do not put the info between the `<!--` tags as github will hide those, gearbot did show them so i extracted the info and put it under 'additional information' where it belongs

also duplicate of #3944

**Closed by AEnterprise** 2018-01-07 19:37 UTC
