### ISSUE TITLE
oil in flat worlds spawns in at its normal depth even when the world is lower than its spawn depth

### ISSUE THREAD

**Issue by ColossalNuke** [BuildCraft/BuildCraft#3984] opened 2018-01-20 23:15 UTC
oil in flat worlds spawns in at its normal depth even when the world is lower than its spawn depth

**Comment by LuigiHutch** [comment] 2018-01-20 23:18
Thanks for the report, this I believe is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3837

**Comment by ColossalNuke** [comment] 2018-01-20 23:22
I just looked at #3837, and it is in fact a duplicate

**Closed** 2018-01-21 05:40 UTC
