### ISSUE TITLE
[7.2] Lava not rendering correctly inside of pipes

### ISSUE THREAD

**Issue by wlhlm** [BuildCraft/BuildCraft#3164] opened 2015-12-20 11:13 UTC
Lava is rendered as if it's "leaking" out of fluid pipes. This seems to only affect lava.

![2015-12-20_12 04 23](https://cloud.githubusercontent.com/assets/1928113/11917712/f76ed7da-a712-11e5-9fea-e3ff64170312.png)

BC 7.2.0pre3
Forge 1635

**Comment by AlexIIL** [comment] 2015-12-20 13:32
Thanks! I've just fixed this and pre4 will be out shortly.

In the future could you use https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues for bug reports for 7.2.x? At some point this will change back to the normal BC repo, but until then it just to stay out of the way of 1.7.10 bug reports :) (Technically a duplicate of https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues/61 )

**Closed by AlexIIL** 2015-12-20 13:32 UTC

**Comment by wlhlm** [comment] 2015-12-20 13:35
> In the future could you use https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues for bug reports for 7.2.x? At some point this will change back to the normal BC repo, but until then it just to stay out of the way of 1.7.10 bug reports :) (Technically a duplicate of AlexIIL/Buildcraft_1.8_Issues#61 )

Sure, will do! I wasn't aware of the separate repository.

Thanks for the quick fix!
