### ISSUE TITLE
PipeConnectionAPI not rendering

### ISSUE THREAD

**Issue by Chocohead** [BuildCraft/BuildCraft#4140] opened 2018-04-22 22:51 UTC
BuildCraft version: 7.99.16

It appears that the PipeConnectionAPI is working, as the hitbox will change for a pipe trying to connect to a registered block, but the rendering seems to not change to match it.
![2018-04-22_23 43 14](https://user-images.githubusercontent.com/4021725/39100834-fb995724-4687-11e8-8aa9-830e74798ff2.png)

**Comment by AlexIIL** [comment] 2018-04-22 22:52
Yeah this is a *looong* running issue. It's tracked here: #3809.

**Comment by AlexIIL** [comment] 2018-04-22 22:52
(Although this is a duplicate of #3809)

**Closed** 2018-04-22 22:52 UTC
Labels: status: duplicate

**Comment by Chocohead** [comment] 2018-04-22 22:54
That would explain why I didn't find anything mentioning it recently, fair enough
