### ISSUE TITLE
7.99.1 Void fluid pipes don't work

### ISSUE THREAD

**Issue by Prot0Zer0** [BuildCraft/BuildCraft#3546] opened 2017-05-03 17:19 UTC
forge 13.20.0.2285
IC2 2.7.18-ex111
Rougelike Dungeons 1.11.2-1.6.6
and some of other mods that won't change anything like minimap, JEI and InvTweak
void pipes work well, but void fluid don't work, and now i have a lot of fluid to handle

**Comment by LuigiHutch** [comment] 2017-05-03 17:26
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3516

**Closed** 2017-05-03 22:00 UTC
Labels: 1.11.2, bug
