### ISSUE TITLE
Pipes not connecting to non buildcraft mods

### ISSUE THREAD

**Issue by Anora** [BuildCraft/BuildCraft#3827] opened 2017-09-30 16:27 UTC
7.99.7 
13.20.1.2476
no crash the pipes wont connect to machines from other mods and players on my server are complaining about it

**Comment by AlexIIL** [comment] 2017-09-30 16:31
Can you provide a bit more detail? Which specific pipes aren't connecting, and what machines do they not connect to?

**Comment by Anora** [comment] 2017-09-30 19:04
all of them by what I can tell, we have been trying them so far on the Thermalfoundation mod and none of the pipes connect to those machines even dough last I recall both mods used RF for power and other things

**Comment by LuigiHutch** [comment] 2017-09-30 19:09
Thanks for the report! I assume you mean kinesis pipes. That would mean that this is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3760

**Closed** 2017-09-30 19:29 UTC
