### ISSUE TITLE
Crash 7.99.4 - Minecraft Version 1.11.2

### ISSUE THREAD

**Issue by tia79** [BuildCraft/BuildCraft#3634] opened 2017-05-31 10:42 UTC
Several Crash reports. Happened alot when inventorys were opened also happens when you scroll down on the creative item lists.

Hope this helps further development :)

Again thanks for updating this for 1.11.2 :)

[crash-2017-05-31_12.34.15-client.txt](https://github.com/BuildCraft/BuildCraft/files/1041113/crash-2017-05-31_12.34.15-client.txt)
[crash-2017-05-31_12.35.54-client.txt](https://github.com/BuildCraft/BuildCraft/files/1041114/crash-2017-05-31_12.35.54-client.txt)
[crash-2017-05-25_03.01.21-client.txt](https://github.com/BuildCraft/BuildCraft/files/1041116/crash-2017-05-25_03.01.21-client.txt)
[crash-2017-05-27_19.23.45-client.txt](https://github.com/BuildCraft/BuildCraft/files/1041118/crash-2017-05-27_19.23.45-client.txt)
[crash-2017-05-31_01.25.49-client.txt](https://github.com/BuildCraft/BuildCraft/files/1041117/crash-2017-05-31_01.25.49-client.txt)
[crash-2017-05-31_01.37.46-client.txt](https://github.com/BuildCraft/BuildCraft/files/1041115/crash-2017-05-31_01.37.46-client.txt)
[crash-2017-05-31_01.40.13-client.txt](https://github.com/BuildCraft/BuildCraft/files/1041120/crash-2017-05-31_01.40.13-client.txt)
[crash-2017-05-31_02.48.41-client.txt](https://github.com/BuildCraft/BuildCraft/files/1041119/crash-2017-05-31_02.48.41-client.txt)

**Comment by afdw** [comment] 2017-05-31 14:15
So:
1, 2, 8: ```java
java.lang.NullPointerException: Rendering screen
	at buildcraft.builders.item.ItemSnapshot$EnumItemSnapshotType.getFromStack(ItemSnapshot.java:142)
	at buildcraft.builders.item.ItemSnapshot.getHeader(ItemSnapshot.java:52)
	at buildcraft.builders.BCBuildersEventDist.onRenderTooltipPostText(BCBuildersEventDist.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_197_BCBuildersEventDist_onRenderTooltipPostText_PostText.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(GuiUtils.java:399)
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:28)
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:23)
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:15)``` It was bug of JEI, fixed [here](https://github.com/mezz/JustEnoughItems/commit/2083077b8dd747991e64c73d0d905d0ae184ad24). Please update it.
3: ```java
java.lang.OutOfMemoryError: Java heap space``` You should increase maximum heap size (`-Xmx` option).
4: ```java
java.lang.NullPointerException: Exception in world tick
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:511)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator.next(Long2ObjectOpenHashMap.java:706)
	at net.minecraft.client.multiplayer.ChunkProviderClient.func_73156_b(ChunkProviderClient.java:80)
	at net.minecraft.client.multiplayer.WorldClient.func_72835_b(WorldClient.java:102)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
``` Something new, probably unrelated to BC.
5, 6, 7: ```java
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at buildcraft.transport.client.model.plug.ModelFacadeItem$FacadeOverride.handleItemState(ModelFacadeItem.java:108)``` Duplicate of #3618.

**Closed** 2017-05-31 14:19 UTC
Labels: version: 1.11.2
