### ISSUE TITLE
Buildcraft Out of Memory Error 

### ISSUE THREAD

**Issue by thefrasca** [BuildCraft/BuildCraft#3790] opened 2017-08-25 13:15 UTC
Below Out of memory error.  It appears to be looking at something in the chunk loading event, but i shouldn't have anything loading chunks.  It only appears to happen when no people are online on the server and it eventually crashes it with Out of memory errors.  I have 6GB allocated though so something is wrong.   

This is BC 7.99.6

Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception while ticking a block
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) ~[lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.IdentityHashMap.resize(IdentityHashMap.java:471) ~[?:1.8.0_131]
        at java.util.IdentityHashMap.put(IdentityHashMap.java:440) ~[?:1.8.0_131]
        at java.util.Collections$SetFromMap.add(Collections.java:5461) ~[?:1.8.0_131]
        at net.minecraft.util.ClassInheritanceMultiMap.func_180213_a(ClassInheritanceMultiMap.java:46) ~[of.class:?]
        at net.minecraft.util.ClassInheritanceMultiMap.<init>(ClassInheritanceMultiMap.java:30) ~[of.class:?]
        at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:88) ~[auo.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:433) ~[avd.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:139) ~[avd.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:104) ~[avd.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:68) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) ~[lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90) ~[lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136) ~[lv.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:303) ~[ajs.class:?]
        at net.minecraft.world.World.func_175726_f(World.java:298) ~[ajs.class:?]
        at net.minecraft.world.World.func_175625_s(World.java:2359) ~[ajs.class:?]
        at buildcraft.lib.compat.DefaultBlockAccessor.getTile(DefaultBlockAccessor.java:30) ~[DefaultBlockAccessor.class:?]
        at buildcraft.lib.compat.CompatManager.getTile(CompatManager.java:14) ~[CompatManager.class:?]
        at buildcraft.lib.misc.BlockUtil.getTileEntity(BlockUtil.java:328) ~[BlockUtil.class:?]
        at buildcraft.lib.tile.TileBC_Neptune.getLocalTile(TileBC_Neptune.java:191) ~[TileBC_Neptune.class:?]
        at buildcraft.lib.tile.TileBC_Neptune.getOffsetTile(TileBC_Neptune.java:186) ~[TileBC_Neptune.class:?]
        at buildcraft.lib.tile.TileBC_Neptune.getNeighbourTile(TileBC_Neptune.java:180) ~[TileBC_Neptune.class:?]
        at buildcraft.transport.pipe.Pipe.updateConnections(Pipe.java:241) ~[Pipe.class:?]
        at buildcraft.transport.pipe.Pipe.onLoad(Pipe.java:213) ~[Pipe.class:?]
        at buildcraft.transport.tile.TilePipeHolder.onLoad(TilePipeHolder.java:217) ~[TilePipeHolder.class:?]
        at net.minecraft.world.World.func_175700_a(World.java:1900) ~[ajs.class:?]
        at net.minecraft.world.World.func_147448_a(World.java:1927) ~[ajs.class:?]
        at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:840) ~[auo.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:104) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) ~[lv.class:?]

**Comment by AlexIIL** [comment] 2017-08-25 13:25
A Buildcraft pipe is loading the next chunk over. This might be related to https://github.com/MinecraftForge/MinecraftForge/issues/4238, as that's the only thing I can think of that might cause this.

**Comment by AlexIIL** [comment] 2017-08-25 13:29
Actually, I'll look into what the methods are before coming to a conclusion.

**Comment by thefrasca** [comment] 2017-08-25 14:38
I am not convinced that this is a BC issue, but that is what the trace seems to show, so I filed it.  I am still investigating as well.

**Comment by AEnterprise** [comment] 2017-08-25 17:04
can you put the entire crashlog on pastebin/gist and link it here? then we can see all info and other mods potentially involved

**Comment by thefrasca** [comment] 2017-08-25 19:14
https://pastebin.com/1pGfazbd  Crash Log

**Comment by AEnterprise** [comment] 2017-09-07 12:02
any luck tracking this down? if not i'm gona close this as it's very doubtfull that BC is the root cause

**Closed** 2017-09-09 17:18 UTC
