### ISSUE TITLE
Crash with heat exchanger

### ISSUE THREAD

**Issue by Bryanbetatester** [BuildCraft/BuildCraft#3881] opened 2017-11-29 20:27 UTC
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2555
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Singleplayer
[crash-2017-11-23_05.38.22-client.txt](https://github.com/BuildCraft/BuildCraft/files/1515413/crash-2017-11-23_05.38.22-client.txt)

Additional information:There is a bug with the heat exchanger, when you break the game it crashes and in crash report it says: missing particles, please solve it because I put it in my survival world

**Comment by AEnterprise** [comment] 2017-11-29 20:28
duplicate of #3874 , already fixed in dev

**Closed by AEnterprise** 2017-11-29 20:28 UTC
