### ISSUE TITLE
BCKinesisPipeStonePlacer crash BuildcraftAdditions-1.7.10-2.2.0.jar

### ISSUE THREAD

**Issue by ZizzyZizzy** [BuildCraft/BuildCraft#2962] opened 2015-08-11 19:50 UTC
Part of Resonant Rise 3.2.7.1 Mainline. No other mods (outside of the MAINLINE selection) installed.

http://pastebin.com/4VEZJqgU

The pipe mentioned in the subject causes a crash if you even go near the chunk where they are placed. The only way to fix it is to disable the mod, restart, let it delete all the ID's from BCAdditons, then restart the server with BCAdditions enabled again.

Yes, kCauldron is in use, but it crashes the same way with forge only.

We temporarily fixed the issue by updating to 2.2.0 from 2.1.4 that came with the pack. It just started crashing again a couple of days later. This time it only crashes in newly generated chunks with those pipes. They are generated in Villager complexes.

**Comment by davboecki** [comment] 2015-08-11 21:46
Don't use LogisticsPipes version 0.10.
That's causing you're problem.
Use the 0.9.2 builds.

**Comment by davboecki** [comment] 2015-08-13 12:30
@asiekierka You can close this as this is an issue with LP anyway.

**Comment by iTitus** [comment] 2015-08-13 12:34
@ZizzyZizzy This time this crash is caused by LP, but next time please report any issues with BCA on our issue tracker: https://github.com/BCA-Team/Buildcraft-Additions/issues ;)

**Closed** 2016-03-24 23:09 UTC
