### ISSUE TITLE
Pumps and quarries power from other mods?

### ISSUE THREAD

**Issue by josh-65** [BuildCraft/BuildCraft#4514] opened 2019-12-14 14:52 UTC
**Describe the solution you'd like**
Other power cables (thermal dynamics cryo fluxduct) should be able to power anything that requires an engine like pumps and quarries.

**Describe alternatives you've considered**
There could also be a converter block the can then be sent out with buildcraft kinesis pipe.

**Comment by bookerthegeek** [comment] 2019-12-14 16:52
While the player in me likes this idea, the modder in me has issues with it. Specifically that Buildcraft went back to Mj on purpose and removed the compatibility with RF on purpose.

What I would like to see though is not a direct RF to Mj converter, but a steam powered Mj producer.

**Comment by AlexIIL** [comment] 2019-12-14 17:28
Duplicate of #3760 (and many others)

**Closed by AlexIIL** 2019-12-14 17:28 UTC
Labels: status: duplicate, type: not a bug, version: 1.12.2
