### ISSUE TITLE
Suggestion: Allow BC Pump to destroy water source blocks

### ISSUE THREAD

**Issue by Okkasionen** [BuildCraft/BuildCraft#3101] opened 2015-10-27 20:55 UTC
I think the ability for the buildcraft pump to destroy water source blocks should be in some way possible.
Two ways I thought of to implement it toogleable because I still want infinite water pools for farms and such. so the config is not an option:

1. Applying an strong redstone singal to the pump to toogle between modes. It should not interfer with the redstone activated engines as they only pass a weak redstone signal or none.
2. Putting huge amounts of power in the pump overclocks it so that it absorbs water faster than minecraft regenerates it. In code it could be implemented as if a certain power limit is reached the pumped source block is deleted in a way that minecraft doesnt regenerate it.

i prefere number 2

thanks for reading

**Comment by XFactHD** [comment] 2015-10-28 12:14
That the pump doesn't destroy water blocks has a sense. The block updates caused by that can easily kill a server if many pumps are used (this problem already exists with Mekanisms pump). Suggestion number 2 is really bad. For example if I am midgame, can already produce thousands of RF/t and just want to build a water farm with 20 pumps, each with a tesseract on top, now this wouldn't be a problem, but if they are overclocked because I am unable to limit the power supply, 20 pumps would create 80 block updates. That's horrible for a server.

**Comment by Okkasionen** [comment] 2015-10-28 12:19
Second point is invalid theres the iron limiter pipe which throttles the power throughput by your needs

**Comment by XFactHD** [comment] 2015-10-28 12:27
My second point is only invalid if I would use BC pipes. I don't think I can put the iron pipe between a tesseract that outputs 150000 RF/t and the pump without having the pipe explode.

**Comment by Okkasionen** [comment] 2015-10-28 12:30
Pipes doesnt explode since Buildcraft i dont know

**Comment by XFactHD** [comment] 2015-10-28 12:48
BC pipes explode when they are over loaded and it would completely make sense if the iron pipe does also have a transfer limit.

**Comment by SandGrainOne** [comment] 2015-10-28 13:19
Item transportation pipes can explode, but neither fluid nor power pipes will explode. They simply restrict how much fluid or power that flow through them.

When that is said, neither ideas in the original post sounds very good. There was talk about adding a new machine that can drain water, but noone has implemented anything. The challenge is as you know to prevent Minecraft from making new source blocks.

There have been attempts, like "WaterHooks" (Apparently used by EnderIO-Addons). https://github.com/HenryLoenwind/waterhook But I'm not sure how well it works.

I'm closing this for now.

**Closed by SandGrainOne** 2015-10-28 13:19 UTC

**Comment by asiekierka** [comment] 2015-10-28 13:45
Kinesis pipes have not exploded for the last 2.5 years or so. It is very sad that people repeat things without ever checking again to see what's changed.

Item pipes do, but we have our reasons for it.
