### ISSUE TITLE
Pls give me example

### ISSUE THREAD

**Issue by MitiskoSVK** [BuildCraft/BuildCraft#4544] opened 2020-03-26 19:02 UTC
Hi I use buildcraft-compat-7.99.24.5 and i need remove recipe from .AssemblyTable all chipset...
Old version funcional code is:
mods.buildcraft.AssemblyTable.removeByName(<BuildCraft|Silicon:redstoneChipset:*>);
Please give me example new funcional code...

Very thanks

**Comment by AlexIIL** [comment] 2020-03-26 19:37
Duplicate of https://github.com/BuildCraft/BuildCraftCompat/issues/93

**Closed by AlexIIL** 2020-03-26 19:37 UTC
Labels: auto: bug
