### ISSUE TITLE
Can't melt anything in a crucible

### ISSUE THREAD

**Issue by RoseQueen21** [BuildCraft/BuildCraft#4508] opened 2019-11-11 22:03 UTC
no matter how much i try i can't melt leaves to get water or seeds to get seed oil or anything else for that matter so i dont know what else to do

**Comment by AlexIIL** [comment] 2019-11-11 22:07
This is the issue tracker for buildcraft specifically - you  would probably have more help if you asked on the issue page for that  modpack?

Also, is this a duplicate of #4506 ?

**Closed** 2019-11-12 17:42 UTC
Labels: status: duplicate

**Comment by RoseQueen21** [comment] 2019-11-12 20:21
where do I find the issue page for this modpack?

**Comment by aaronliu0130** [comment] 2019-11-16 03:43
@RoseQueen21 [Here you go.https://github.com/davqvist/Exoria/issues](https://github.com/davqvist/Exoria/issues)
