### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by Excepto** [BuildCraft/BuildCraft#3440] opened 2016-10-15 18:01 UTC
Ticking entity. It might be a repeat  #3361 . It was the automatic crafting table.
[crash-2016-10-15_19.50.49-server.txt](https://github.com/BuildCraft/BuildCraft/files/531321/crash-2016-10-15_19.50.49-server.txt)

**Comment by AEnterprise** [comment] 2016-10-16 11:03
indeed this is a duplicate of that issue and nothing changed: some mod is messing with BC recipes from another thread. your best bet is to do a binary search untill you can pinpoint what mod is causing this and report it there

also 1.7.10 is outdated and no longer supported by most mods so it might never get fixed

**Closed by AEnterprise** 2016-10-16 11:03 UTC
Labels: 1.7.10, duplicate
