### ISSUE TITLE
[1.11.2] 7.99.0 Client crash in ModelLoader with TConstruct

### ISSUE THREAD

**Issue by leagris** [BuildCraft/BuildCraft#3560] opened 2017-05-08 14:01 UTC
### Versions
BC 7.99.0
TConstruct 1.11.2-2.7.0.12

### Client Crash

[ crash-2017-05-08_15.40.03-client.txt](https://gist.github.com/leagris/6cb6a0611e0a45296fa9b8aa6ade13e8)

Client crash in:
```Java
model.ModelLoader
```
caused by a:
```Java
NullPointerException
```
in
```Java
buildcraft.lib.client.sprite.AtlasSpriteSwappable.func_110970_k
```
calling:
```Java
slimeknights.tconstruct.library.client.texture.TextureColoredTexture.loadData
```

**Comment by AEnterprise** [comment] 2017-05-08 14:04
thanks for the report, as clarification on your analysis: the BC function is called by tconstruct, not the other way arround

also could you try with BC 7.99.1?

**Comment by leagris** [comment] 2017-05-08 14:26
Cannot test in 7.99.1 because of https://github.com/BuildCraft/BuildCraft/issues/3544
And probably also because of https://github.com/SlimeKnights/TinkersConstruct/issues/2881

**Comment by AlexIIL** [comment] 2017-05-08 14:28
...ah ok. Then it should be fixed in 7.99.2, whenever that comes out

**Comment by kreezxil** [comment] 2017-05-09 19:07
I think I got the same thing, my pack loads fine until I add Tinker's construct. It hangs my server and so crash report there, but I"m abled to generate one in the client. Here it is.

https://pastebin.com/TRtwQmAw

**Comment by afdw** [comment] 2017-05-09 19:10
@kreezxil duplicate of https://github.com/BuildCraft/BuildCraft/issues/3534

**Comment by AEnterprise** [comment] 2017-05-09 20:02
7.99.2 is out, please let is know if this is still an issue

**Closed by AEnterprise** 2017-05-09 20:02 UTC
Labels: 1.11.2
