### ISSUE TITLE
Dedicated Minecraft 1.7.10 Server BC 7.0.x

### ISSUE THREAD

**Issue by MBfromOK** [BuildCraft/BuildCraft#2704] opened 2015-05-09 23:02 UTC
Tried to start a new server running Minecraft 1.7.10 and Buildcraft 7 (Yes, I know it is a Beta and subject to change).

I have googled the message and found no results including a google search with site:mod-buildcraft.com specified. Therefore, I am turning to you, the bug report forum

When trying to load I get the following crash message:

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 5/9/15 5:50 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:719)
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
        at forestry.pipes.proxy.ProxyPipes.initPropolisPipe(ProxyPipes.java:35)
        at forestry.plugins.PluginPropolisPipe.postInit(PluginPropolisPipe.java:64)
        at forestry.plugins.PluginManager.runPostInit(PluginManager.java:296)
        at forestry.core.ForestryCore.postInit(ForestryCore.java:118)
        at forestry.Forestry.postInit(Forestry.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:717)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: buildcraft.core.CreativeTabBuildCraft
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 36 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 2.6.32-504.16.2.el6.x86_64
        Java Version: 1.8.0_45, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1590757552 bytes (1517 MB) / 2008547328 bytes (1915 MB) up to 2008547328 bytes (1915 MB)
        JVM Flags: 2 total; -Xmx2048M -Xms2048M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP v9.05 FML v7.10.141.1403 Minecraft Forge 10.13.3.1403 60 mods loaded, 60 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        FML{7.10.141.1403} [Forge Mod Loader] (forge-1.7.10-10.13.3.1403-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        Forge{10.13.3.1403} [Minecraft Forge] (forge-1.7.10-10.13.3.1403-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        NotEnoughItems{1.0.4.106} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.106-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        OpenModsCore{0.7.2} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        bdlib{1.7.1.71} [BD Lib] (bdlib-mc1710-1.7.1.71.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1237-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        IC2{2.2.718-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.718-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        BuildCraft|Core{7.0.3} [BuildCraft] (buildcraft-7.0.3-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        Forestry{3.5.4.13} [Forestry for Minecraft] (forestry_1.7.10-3.5.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
        BinnieCore{2.0-pre8} [Binnie Core] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
        Botany{2.0-pre8} [Botany] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ExtraBees{2.0-pre8} [Extra Bees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ExtraTrees{2.0-pre8} [Extra Trees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        Genetics{2.0-pre8} [Genetics] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        BuildCraft|Energy{7.0.3} [BuildCraft Energy] (buildcraft-7.0.3-energy.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        BuildCraft|Factory{7.0.3} [BuildCraft Factory] (buildcraft-7.0.3-factory.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        BuildCraft|Robotics{7.0.3} [BuildCraft Robotics] (buildcraft-7.0.3-robotics.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        BuildCraft|Silicon{7.0.3} [BuildCraft Silicon] (buildcraft-7.0.3-silicon.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        BuildCraft|Transport{7.0.3} [Buildcraft Transport] (buildcraft-7.0.3-transport.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        EnderIO{1.7.10-2.2.8.367} [Ender IO] (EnderIO-1.7.10-2.2.8.367.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        EnderTech{1.7.10-0.3.2.382} [EnderTech] (EnderTech-1.7.10-0.3.2.382.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        TConstruct{1.7.10-1.8.4.build939} [Tinkers' Construct] (TConstruct-1.7.10-1.8.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ExtraTiC{1.4.1} [ExtraTiC] (ExtraTiC-1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ExtraUtilities{1.2.4b} [Extra Utilities] (extrautilities-1.2.4b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        gendustry{1.4.10.77} [GenDustry] (gendustry-mc1710-1.4.10.77.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
        IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        Mystcraft{0.11.5.00} [Mystcraft] (mystcraft-1.7.10-0.11.5.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        OpenMods{0.7.2} [OpenMods] (OpenModsLib-1.7.10-0.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        OpenBlocks{1.4.2} [OpenBlocks] (OpenBlocks-1.7.10-1.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        OpenPeripheralCore{1.1} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        OpenPeripheral{0.3.1} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        OpenPeripheralIntegration{0.2.1} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        MrTJPCoreMod{1.0.5.12} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.12-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Core{4.5.16.77} [ProjectRed] (ProjectRed-1.7.10-4.5.16.77-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Transmission{4.5.16.77} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.16.77-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Transportation{4.5.16.77} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.16.77-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Exploration{4.5.16.77} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.16.77-World.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Compatibility{4.5.16.77} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.16.77-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Integration{4.5.16.77} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.16.77-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Illumination{4.5.16.77} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.16.77-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ProjRed|Expansion{4.5.16.77} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.16.77-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        rftools{2.80} [RFTools] (rftools-2.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        SolarExpansion{1.5a} [Solar Expansion] (SolarExpansion-Basic-1.5a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        TwilightForest{2.3.5} [The Twilight Forest] (twilightforest-1.7.10-2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        VersionChecker{1.1.8} [Version Checker] (VersionChecker-1.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        wawla{1.2.1} [What Are We Looking At] (Wawla-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
        OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
        CoFHCore: -[1.7.10]3.0.2-262
        Mantle Environment: Environment healthy.
        TConstruct Environment: Environment healthy.
        List of loaded APIs:
                * BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1237-universal.jar
                * BuildCraftAPI|blocks (1.0) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|blueprints (1.2) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|boards (1.0) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|core (1.5) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|events (1.0) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|facades (1.1) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|filler (4.0) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|fuels (2.0) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|gates (4.1) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|items (1.1) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|library (1.0) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|power (1.3) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|recipes (2.1) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|robotics (1.2) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|statements (1.1) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|tablet (1.0) from buildcraft-7.0.3-core.jar
                * BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.6.1.0.jar
                * BuildCraftAPI|tools (1.0) from extrautilities-1.2.4b.jar
                * BuildCraftAPI|transport (4.0) from buildcraft-7.0.3-core.jar
                * CoFHAPI (1.7.10R1.0.0) from extrautilities-1.2.4b.jar
                * CoFHAPI|block (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHAPI|core (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHAPI|energy (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHAPI|fluid (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHAPI|inventory (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHAPI|item (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.367.jar
                * CoFHAPI|items (1.7.10R1.0.3) from SolarExpansion-Basic-1.5a.jar
                * CoFHAPI|modhelpers (1.7.10R1.0.3) from SolarExpansion-Basic-1.5a.jar
                * CoFHAPI|tileentity (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHAPI|transport (1.7.10R1.0.7) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHAPI|world (1.7.10R1.0.12) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib|audio (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib|gui (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib|gui|container (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHLib|gui|element (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHLib|gui|element|listbox (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib|gui|slot (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHLib|inventory (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib|render (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib|render|particle (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHLib|util (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib|util|helpers (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHLib|util|position (1.7.10R1.0.0B9) from EnderTech-1.7.10-0.3.2.382.jar
                * CoFHLib|world (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * CoFHLib|world|feature (1.7.10R1.0.1) from CoFHCore-[1.7.10]3.0.2-262.jar
                * EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.367.jar
                * EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.367.jar
                * EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.367.jar
                * ForestryAPI|apiculture (2.6.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|circuits (1.1.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|core (2.6.1) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|food (1.1.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|genetics (2.7.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|hives (4.0.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|recipes (2.1.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|storage (2.3.0) from forestry_1.7.10-3.5.4.13.jar
                * ForestryAPI|world (1.1.0) from forestry_1.7.10-3.5.4.13.jar
                * gendustryAPI (1.4.10) from gendustry-mc1710-1.4.10.77.jar
                * IC2API (1.0) from industrialcraft-2-2.2.718-experimental.jar
                * Mystcraft|API (0.1) from mystcraft-1.7.10-0.11.5.00.jar
                * OpenPeripheralApi (3.2) from OpenPeripheralCore-1.7.10-1.1.jar
                * RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|carts (1.3.1) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|core (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|signals (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
                * RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.6.1.0.jar
                * Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.6.1.0.jar
                * WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
        Profiler Position: N/A (disabled)
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)-bash-4.1$

**Comment by psxlover** [comment] 2015-05-09 23:20
Forestry{3.5.4.13} Forestry for Minecraft Unloaded->Constructed->Pre-initialized->Initialized->Errored
BinnieCore{2.0-pre8} Binnie Core Unloaded->Constructed->Pre-initialized->Initialized->Errored

Duplicate of #2703

**Closed** 2015-05-10 06:39 UTC
