### ISSUE TITLE
Buildcraft won't mine or pick up blocks!

### ISSUE THREAD

**Issue by Swandar** [BuildCraft/BuildCraft#3389] opened 2016-07-07 19:27 UTC
Hello,
I was trying to use the quarry and filler to remove a big section of my underground base and couldn't. I tried switching things around removing things out of the way of the of the yellow and black strips, but nothing would work, if anyone know how to fix this problem please tell me. Or if the build craft team could release a update fixing this that would be nice too.
![2016-07-07_14 25 24](https://cloud.githubusercontent.com/assets/19779837/16666803/d4bc48f6-444e-11e6-9c15-21b21ba80214.png)
![2016-07-07_14 25 14](https://cloud.githubusercontent.com/assets/19779837/16666804/d4bdbde4-444e-11e6-9a77-62ed83eddbee.png)
![2016-07-07_14 25 17](https://cloud.githubusercontent.com/assets/19779837/16666802/d4ba0dac-444e-11e6-9c66-dd41af0bc239.png)
You can see that the quarry forms just the arm rails and miner pipe aren't attached.

**Comment by AEnterprise** [comment] 2016-07-07 19:39
for a problem to be fixed we need info on what's going on, in this case that meens a log of when this heapens so we can check that for errors and what BC version this is with what other mods are installed

**Comment by Swandar** [comment] 2016-07-07 19:47
It seems to only happen in build 7.1.0 but anything before that is fine.
Here's there the latest logs

**Comment by Swandar** [comment] 2016-07-07 19:47
It seems to only happen in build 7.1.0 but anything before that is fine.
Here's there the latest logs

**Comment by Swandar** [comment] 2016-07-07 19:48
It seems to only happen in build 7.1.0 but anything before that is fine.
Here's there the latest logs

[logs.zip](https://github.com/BuildCraft/BuildCraft/files/352928/logs.zip)

**Comment by AEnterprise** [comment] 2016-07-07 19:52
those are client logs, we need the server log or fml-latest log, also a modlist please, checking the log line by line to see what all is loaded is a painfull job

**Comment by Swandar** [comment] 2016-07-07 19:56
There ya go hope it helps
[Logs.zip](https://github.com/BuildCraft/BuildCraft/files/352938/Logs.zip)

**Comment by Swandar** [comment] 2016-07-07 19:58
[Minecraft mod-list.zip](https://github.com/BuildCraft/BuildCraft/files/352943/Minecraft.mod-list.zip)
There's a cleaner mod list

**Comment by AlexIIL** [comment] 2016-07-07 20:08
That's a very old version of BC... can you try with 7.1.17?

**Comment by Swandar** [comment] 2016-07-07 20:21
I tried 7.1.17, 7.1.16, 7.1.15, 7.1.14, and 7.1.13. I just skipped to 7.0.6, which is the last one I new of that worked correctly.

**Comment by AEnterprise** [comment] 2016-07-07 20:23
is it a regular forge server or bukkit/thermos/...?

**Comment by Swandar** [comment] 2016-07-07 20:24
I'm using regular Forge, forge-1.7.10-10.13.4.1614-1.7.10.

**Comment by dj3520** [comment] 2016-07-08 08:03
have you tried `/buildcraft op` ? Also I _am_ seeing the arm in those screenshots, just not in the right place.

**Comment by Swandar** [comment] 2016-07-08 17:57
Yes, they are there just not attached to the frame of the quarry.

**Comment by AlexIIL** [comment] 2016-07-08 18:09
Does the arm move at all? Does it happen if you remove all mods other than buildcraft? (Obviously on a copy of the world, not the original).

**Comment by Swandar** [comment] 2016-07-10 03:45
The arms twitch but don't move anywhere. They don't mine anything, and I have tried removing all my mods but same problem.

**Comment by AEnterprise** [comment] 2016-07-10 08:06
can you try updating your forge to latest? i remember BC had issues like this in the past (mostly reported on the old forum) and this has both been caused by a BC bug as well as a forge bug in the past

**Comment by Swandar** [comment] 2016-07-12 00:08
I have the latest version of forge. I can't use the recommended version because a mod I use is 3 version ahead of it.

**Comment by AEnterprise** [comment] 2016-08-31 12:41
do you still have this issue? if so add and remove mods in a binary search to find the mod combination that causes this. For everyone else the quarry works so another mod seems to be messing with things

**Comment by AEnterprise** [comment] 2016-09-17 13:34
closing due to lack of information

**Closed by AEnterprise** 2016-09-17 13:34 UTC
