### ISSUE TITLE
Possible issue with BuildCraft's sprite loader

### ISSUE THREAD

**Issue by KainZeroGaming** [BuildCraft/BuildCraft#3840] opened 2017-11-08 17:32 UTC
Per another user, there may be an issue with TinkersConstruct and Buildcraft:

here is the crash report:
https://pastebin.com/embed_js/85shM94T

**Comment by AlexIIL** [comment] 2017-11-08 17:34
This (should) have been fixed by now -- can you update to [7.99.8](https://www.mod-buildcraft.com/releases/BuildCraft/7.99.8/buildcraft-7.99.8.jar)?

**Comment by LuigiHutch** [comment] 2017-11-08 17:35
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3534 Update!

**Comment by KainZeroGaming** [comment] 2017-11-08 17:44
I tried the 7.99.8 update without TC installed and crashed. ill make a new pastebin link.

**Comment by KainZeroGaming** [comment] 2017-11-08 17:46
Here is the new Crash Report.
https://pastebin.com/embed_js/8xk7YuLL

**Comment by AlexIIL** [comment] 2017-11-08 17:49
It looks like optifine is crashing on some models, although I guess that means that its buiildcraft related. Can you open a new issue about Optifine not being compatible with 7.99.8?

(Also can you try removing optifine temporarily to see if it makes any difference)

**Comment by KainZeroGaming** [comment] 2017-11-08 17:50
im going to remove it and test it now.

**Comment by KainZeroGaming** [comment] 2017-11-08 17:56
The game Runs with 7.99.8 as long as optifine is gone

**Comment by KainZeroGaming** [comment] 2017-11-08 18:02
Ok so I checked, and was using a much older optifine. worked fine with my setup until i added bc 7.99.8 but "OptiFine_1.11.2_HD_U_C3" works well with it.

**Comment by AlexIIL** [comment] 2017-11-08 18:03
So does it all work now? (If so please close this :) )

**Comment by KainZeroGaming** [comment] 2017-11-08 18:06
And The good news is. With bc 7.99.8 and OptiFine_1.11.2_HD_U_C3........TConstruct-1.11.2-2.7.1.34 Works

**Comment by KainZeroGaming** [comment] 2017-11-08 18:07
Im going to close this. Thanks Everyone.

**Closed** 2017-11-08 18:07 UTC
Labels: type: bug, type: mod compat, version: 1.11.2, version: out-of-date
