### ISSUE TITLE
Heat Exchanger's tile entity

### ISSUE THREAD

**Issue by FrostQ** [BuildCraft/BuildCraft#4083] opened 2018-03-16 15:33 UTC
BuildCraft version: 7.99.15
Forge version: 14.23.2.2611
Link to crash report or log: [crash-2018-03-16_16.22.25-client.txt](https://github.com/BuildCraft/BuildCraft/files/1819786/crash-2018-03-16_16.22.25-client.txt)
Singleplayer or multiplayer: 
Steps to reproduce: Heat Exchander
Additional information: 
![2018-03-16_16 20 48](https://user-images.githubusercontent.com/36822613/37529368-427d9ef2-2937-11e8-97b4-878f6bb731f0.png)
It make FPS drop when walking, place or breaking block
If "remove erroring tile entity" (forge's config) is false" it make CRASH

**Comment by AEnterprise** [comment] 2018-03-16 15:35
duplicate of #4067, already fixed for the next release

**Closed by AEnterprise** 2018-03-16 15:35 UTC
