### ISSUE TITLE
Builder not detecting Tinkers Construct Smeltery blocks

### ISSUE THREAD

**Issue by bluehornet2297** [BuildCraft/BuildCraft#3346] opened 2016-05-22 20:54 UTC
I am trying to create a structure that uses blue stained glass, marble and seared paver blocks. The architect table does not see the pavers but the glass and marble is okay. I'm assuming this is a compatibility thing; As you can see, none of the smeltery blocks work. 

I am on the latest version of Direwolf20 FTB pack, Minecraft version 1.7.10. It does not work on SMP or SSP.

![2016-05-22_16 48 23](https://cloud.githubusercontent.com/assets/19521033/15456397/3736a782-203d-11e6-8d91-7a814e48e4d2.png)
![2016-05-22_16 48 42](https://cloud.githubusercontent.com/assets/19521033/15456399/3fddce92-203d-11e6-8a0b-02c494b5f72e.png)

**Comment by asiekierka** [comment] 2016-05-22 21:05
Yes, someone would have to write compatibility for it in BuildCraftCompat.

2016-05-22 22:54 GMT+02:00 bluehornet2297 <notifications@github.com>:

**Comment by bluehornet2297** [comment] 2016-05-22 21:59
Is BuildCraftCompat already included in this version of the DireWolf 20 pack?

**Comment by asiekierka** [comment] 2016-05-22 22:04
Yes, but it does not have compatibility for Tinker's Construct. Someone would have to code it in.

**Comment by LuigiHutch** [comment] 2016-05-22 22:47
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3338

**Closed** 2016-05-22 22:59 UTC
Labels: duplicate

**Comment by bluehornet2297** [comment] 2016-05-22 23:06
Thanks for the help guys. Does anyone know if this is planned to be "added"(fixed) anytime soon? I would imagine all the mod authors are working on the versions for the newer MC right now. Seems like a pretty simple fix since so many other mods with TEs already are compatible...

**Comment by AEnterprise** [comment] 2016-05-23 08:00
this probably won't be done on 1.7.10 but you can ask the tinker devs to add it for 1.8/1.9 from there end, that is probably the easiest as then they can also add support for any other block that uses a TE
