### ISSUE TITLE
Heat Exchanger gets blocked on certain fluid amounts

### ISSUE THREAD

**Issue by LordGolias** [BuildCraft/BuildCraft#4135] opened 2018-04-21 19:25 UTC
BuildCraft version: 7.99.17
Singleplayer or multiplayer: both

Consider the path 
```
oil (cold) -> Distiller -> Heavy Oil (375 mB) + Fuel Gas (2 B)
```

If the 375mB of Heavy Oil is sent to the Heat Exchanger (HE), the HE it will only consume 370 mB of the fluid. More importantly, the remaining 5mB will be stuck at the entrance of the HE, causing no other kind of liquid to enter until e.g. 365mB of the same liquid arrives to the HE.

IMO, the HE should probably not store liquids on its ends and instead only accept liquids from the input pipe to the output pipe (with cooling/heating). This facilitates using the HE on more complex and fun designs where it is being used to heat different types of liquids during operations.

**Comment by LuigiHutch** [comment] 2018-04-21 20:31
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3780

**Comment by LordGolias** [comment] 2018-04-22 06:26
This is about the heat exchanger. The other is about the distiller.

**Closed** 2018-05-06 17:40 UTC
Labels: status: fixed/implemented in dev, version: 1.12.2

**Comment by Bigdbigd03** [comment] 2018-09-12 22:18
This issue looks like a mess. Wow
