### ISSUE TITLE
Incorrect WAILA information for pipes

### ISSUE THREAD

**Issue by justinrusso** [BuildCraft/BuildCraft#4060] opened 2018-03-03 16:39 UTC
Looking at any pipe shows the incorrect information in WAILA. They all appear as "Diamond Fluid Pipe"

![2018-01-13_00 51 13](https://user-images.githubusercontent.com/30686588/34904505-334881d4-f7fc-11e7-8aad-76f56d415670.png)

BuildCraft version: 7.99.15
Forge version: 14.23.2.2623
Singleplayer or multiplayer: Singleplayer
Waila version: 1.8.23

**Comment by AlexIIL** [comment] 2018-03-03 16:51
Do you know a WAILA dev that could help diagnose what's going on?

**Comment by AlexIIL** [comment] 2018-03-03 17:12
From a little bit of looking around I think the issue is here: https://github.com/TehNut/HWYLA/blob/1.12/src/main/java/mcp/mobius/waila/overlay/tooltiprenderers/TTRenderStack.java#L42: As buildcraft uses a single block for all pipe items, the `new ItemStack(Block)` call gets the *last* item that was registered. In this case it's the diamond fluid pipe (assuming power pipes are disabled? (https://github.com/BuildCraft/BuildCraft/blob/8.0.x/common/buildcraft/transport/BCTransportItems.java#L123).

As such I'm not sure there's much we can do about this on our end.

**Comment by LuigiHutch** [comment] 2018-03-03 17:14
Are you using waila or hwyla?

**Comment by AlexIIL** [comment] 2018-03-03 17:14
From one of the [linked issues](https://github.com/Darkhax-Minecraft/WailaStages/issues/1):

MC: 1.12.2
Forge: 2575
WAWLA: 2.5.248
HWYLA: 1.8.23-B38_1.12
WAILA Stages: 1.0.22

**Comment by justinrusso** [comment] 2018-03-03 17:16
I believe we have a direct contact to Tehnut, will reach out to him. Thanks for looking into it 👍

**Comment by LuigiHutch** [comment] 2018-03-03 17:18
So you are using hwyla not waila?

**Comment by justinrusso** [comment] 2018-03-03 17:19
Correct, I am using HWYLA. Reported it as WAILA because in game it appears as such.

**Comment by Ghent** [comment] 2018-03-03 17:42
I wonder if it is perhaps WAILA stages or WAWLA?  I am using HWYLA 1.8.23-B38-1.12.2 as well, but I do not experience the same issues.  I am not mixing it with the other two mods mentioned.

**Comment by justinrusso** [comment] 2018-03-03 17:58
I've removed both mods and it still shows the incorrect name

**Comment by Ghent** [comment] 2018-03-03 18:02
Are there other mods in place as well?  Have you tried it with only HWYLA installed?

**Comment by justinrusso** [comment] 2018-03-03 19:55
Well i removed a bunch of mods, and now they all show as "Iron Transport Pipe" instead...

**Comment by LuigiHutch** [comment] 2018-03-03 22:27
I cannot reproduce with:
BC 7.99.15
HWYLA 1.8.23-B38_1.12
WAWLA 1.12.2-2.5.251
WAILA Stages 1.12.2-1.0.22

![2018-03-03_22 26 10](https://user-images.githubusercontent.com/9326429/36939946-fa32d950-1f31-11e8-8022-b861bbc01623.png)

**Comment by justinrusso** [comment] 2018-03-03 22:50
Yeah. Tested as well with a fresh instance of those mods and it worked fine.

Im combing through my [mod list](https://gist.github.com/justinrusso/257a9a965ec625378141de6d0b8670ae) trying to see... its quite large.

Since removing around 40 of these mods, its changed from showing `Diamond Fluid Pipe` to `Iron Transport Pipe` . I just don't see what would be causing this behavior..
![image](https://user-images.githubusercontent.com/25138621/36940096-b01049ec-1f0a-11e8-88d8-d9afd155df4c.png)

**Comment by AlexIIL** [comment] 2018-03-03 23:00
I'd assume that the actual pipe name shown isn't important if it's wrong. I suppose it might be caused by the ID map shifting around for no reason... the pipe with the highest ID *might* win. Or lowest. Or anything else. (Basically, does changing worlds affect the name displayed)

**Comment by AEnterprise** [comment] 2018-03-23 19:48
@justinrusso did you manage to find the 3rd mod causing this?

**Comment by AEnterprise** [comment] 2018-03-30 08:55
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.

**Closed by AEnterprise** 2018-03-30 08:55 UTC
Labels: status: needs investigation, type: bug, type: mod compat, version: 1.12.2

**Comment by justinrusso** [comment] 2018-03-30 11:21
Sorry for the lack of updates. This was a bug with hwyla and has been resolved I believe
