### ISSUE TITLE
unable to load up (1.11.2)buildcraft-7.99.3

### ISSUE THREAD

**Issue by SDUBZ** [BuildCraft/BuildCraft#3608] opened 2017-05-24 08:56 UTC
Buildcraft: buildcraft-7.99.3
Forge:1.11.2-2304

[18:45:40] [Client thread/WARN] [FML]: ****************************************
[18:45:40] [Client thread/WARN] [FML]: ****************************************
[18:45:40] [Client thread/WARN] [FML]: * Unknown recipe class! buildcraft.transport.recipe.FacadeSwapRecipe Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[18:45:40] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:241)
[18:45:40] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:176)
[18:45:40] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:55)
[18:45:40] [Client thread/WARN] [FML]: *  at java.util.TimSort.gallopLeft(Unknown Source)
[18:45:40] [Client thread/WARN] [FML]: *  at java.util.TimSort.mergeAt(Unknown Source)
[18:45:40] [Client thread/WARN] [FML]: *  at java.util.TimSort.mergeCollapse(Unknown Source)...
[18:45:40] [Client thread/WARN] [FML]: ****************************************

**Comment by AEnterprise** [comment] 2017-05-24 08:57
duplicate of #3590 
already fixed in dev

**Closed by AEnterprise** 2017-05-24 08:57 UTC
