### ISSUE TITLE
Buggy fluid shards

### ISSUE THREAD

**Issue by Cyakat** [BuildCraft/BuildCraft#4075] opened 2018-03-13 07:20 UTC
BuildCraft version: 7.99.15
Forge version: 1.12.2-14.23.2.2611
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Steps to reproduce: Place a fragile water shard into a Compression Dynamo (Thermal Expansion)
Additional information: When the water shard is placed in, Minecraft bugs out and you cant place or break anything and opening containers doesn't work either.

**Comment by AEnterprise** [comment] 2018-03-13 08:08
sounds like an issue with TE, did you report this to them as well?

**Comment by Cyakat** [comment] 2018-03-14 01:24
No I have not, but I will tell them. Thanks for the help!

**Comment by KingLemming** [comment] 2018-03-15 05:18
This is not an issue with TE. If it were, literally everything would cause it. That doesn't happen - it's only your shards.

**Comment by AEnterprise** [comment] 2018-03-15 21:21
@KingLemming that may be but we don't have this issue in our own containers or with other mods, so it's a specific interaction in this case. Do you have any idea on what might be getting stuck in an infinite loop here?

**Comment by KingLemming** [comment] 2018-03-15 23:00
https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/dynamo/BlockDynamo.java#L231

Here's the method called when a block is activated. I am literally deferring to Forge's FluidHelper.

**Comment by AEnterprise** [comment] 2018-03-16 09:21
i guess maybe this is some weird interaction due to the shards not being allowed to be filled

**Comment by KingLemming** [comment] 2018-03-16 14:01
Should mention, I can't actually seem to make this happen. So it's entirely an unverified report.

I just know that there's nothing in my own code that would cause it. (And again, my own testing just showed it to work fine.)

**Comment by AlexIIL** [comment] 2018-03-16 14:08
@KingLemming thanks for testing, that should help quell the blame game.

@Cyakat Can you reproduce this again? if so, can you upload your "fml-client-latest.log" [here](gist,github.com) and link back to it?

**Comment by AEnterprise** [comment] 2018-03-16 20:35
just tried this myself and was also unable to make this heapen, seems a 3rd mod is indeed involved, nor do i see things in the code on eighter side that would explain this

**Comment by AEnterprise** [comment] 2018-03-23 19:44
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.

**Closed by AEnterprise** 2018-03-23 19:44 UTC
Labels: status: needs verification, type: mod compat, version: 1.12.2
