### ISSUE TITLE
1.11.2 - Crash While Exploring

### ISSUE THREAD

**Issue by Darkosto** [BuildCraft/BuildCraft#3643] opened 2017-06-02 17:44 UTC
Hello! I was exploring and generating new chunks after updating BC and got this crash:

https://pastebin.com/Kw1FbH8p

MC: 1.11.2
Forge: 2310
BC: 7.99.4

Let me know if you need any more info! Thanks for looking into this,
Darkosto

**Comment by LuigiHutch** [comment] 2017-06-02 17:47
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3639

**Comment by AlexIIL** [comment] 2017-06-02 17:47
Looks like its a bug in NEI (dupe of #3639), reported to NEI [here](https://github.com/TheCBProject/NotEnoughItems/issues/100).

Hopefully they fix this soon :)

**Closed by AlexIIL** 2017-06-02 17:47 UTC
