### ISSUE TITLE
BuildCraft Refinery not outputting to powered wooden pipe

### ISSUE THREAD

**Issue by bodieb1** [BuildCraft/BuildCraft#4096] opened 2018-03-21 23:10 UTC
BuildCraft version: 7.99.15
Forge version: 14.23.2.26.11
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer

-----
I tried to build a refinery by pumping oil into a tank and then pumping it into the refinery. I had a redstone engine powering a wooden fluid pipe going out into a tank. When I run the refinery, it makes fuel but it won't output into the tank. I have quartz piping and combustion engines powering the refinery. 
----
![2018-03-21_19 08 46](https://user-images.githubusercontent.com/35472874/37742276-57a8f2ba-2d3b-11e8-9a55-f9d8e8dcf40b.png)
![2018-03-21_19 08 57](https://user-images.githubusercontent.com/35472874/37742277-57b9f736-2d3b-11e8-9751-01be56671ba4.png)
![2018-03-21_19 00 32](https://user-images.githubusercontent.com/35472874/37742278-57cefa32-2d3b-11e8-8532-45c69a724024.png)
![2018-03-21_19 00 33](https://user-images.githubusercontent.com/35472874/37742279-57df02ec-2d3b-11e8-9270-e3ceb7ae3eba.png)

**Comment by LuigiHutch** [comment] 2018-03-21 23:13
Thanks for the report. That is actually the distiller as the refinery is not more. BC oil processing has been completely redone. Here is a basic guide about how the new blocks work: http://imgur.com/a/AXUOX

For your setup in short, you need to extract the fluids out the top and bottom :)

Duplicate of #3737 and #3950

**Comment by bodieb1** [comment] 2018-03-21 23:40
*Thanks!*
---
I've been trying to fix this for hours and all of the guides are outdated.
Thanks @LuigiHutch

**Closed** 2018-03-21 23:40 UTC
