### ISSUE TITLE
Pipes missing textures?

### ISSUE THREAD

**Issue by MarkisJr** [BuildCraft/BuildCraft#3752] opened 2017-07-22 08:46 UTC
NOTE: I'm on 1.11.2 and on a single player world.

I believe it is a bug, not sure.
![2017-07-22_18 41 58](https://user-images.githubusercontent.com/25335443/28489756-07f704c8-6f0e-11e7-835b-a2062a5720ee.png)
![2017-07-22_18 42 16](https://user-images.githubusercontent.com/25335443/28489755-07e2d00c-6f0e-11e7-8cc5-a03aac2ed3af.png)

**Comment by MarkisJr** [comment] 2017-07-22 08:46
Items and liquads are still transfering through them.

**Comment by AEnterprise** [comment] 2017-07-22 09:18
this is purely a visual thing, something in those chunks (or neighboring that got send to the client at the same time) is throwing errors when syncing to the client, this is causing forge to choke on the packet and the pipes are not receiving any info from the server about what they actually are

you're gona need to check your logs for what threw the inital error, most likely pams harvestcraft if you have that installed

**Comment by MarkisJr** [comment] 2017-07-22 09:30
Ok

**Comment by AEnterprise** [comment] 2017-07-23 08:45
missed this earlier: duplicate of #3685

**Closed by AEnterprise** 2017-07-23 08:45 UTC
