### ISSUE TITLE
Other mod's RF pipes not compatible with BuildCraft.

### ISSUE THREAD

**Issue by iamevan627** [BuildCraft/BuildCraft#4073] opened 2018-03-10 22:45 UTC
BuildCraft version: 7.99.13
Forge version: 14.23.1.2555
Link to crash report or log: None.
Singleplayer or multiplayer: Both.
Steps to reproduce: Put another mod's RF cable next to a buildcraft generator, quarry, etc.
Additional information: It worked in Buildcraft 7.1.16 on Minecraft 1.7.10.

**Comment by LuigiHutch** [comment] 2018-03-10 22:49
BuildCraft in 1.11+ has moved back to using its own MJ power system which is NOT compatible with RF. However, due to BuildCraft being in alpha no other mods support it, or should support it, as we are still making breaking changes to the API.

Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3760

**Closed** 2018-03-10 22:52 UTC
Labels: status: duplicate, type: mod compat, type: not a bug, version: 1.12.2
