### ISSUE TITLE
BuildCraft Quarry Crash on placement

### ISSUE THREAD

**Issue by Trhod17** [BuildCraft/BuildCraft#3848] opened 2017-11-20 06:42 UTC
**Buildcraft** version: Latest 1.7.10 version
**Forge** version: 1614 (1.7.10)
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : https://pastebin.com/CzUUKQJD 
Singleplayer/multiplayer: singleplayer

Additional information:
Whenever i place a quarry in my modpack the game crashes and i cant get back into the world
i set remove erroring tileentities to true in the forge config and i deleted the buildcraft config and restarted the game. still cant get back into my world

**Comment by AEnterprise** [comment] 2017-11-20 08:06
duplicate of https://github.com/BuildCraft/BuildCraft/issues/3839

the issue has been fixed but not released

**Closed by AEnterprise** 2017-11-20 08:06 UTC
