### ISSUE TITLE
When use IC2's Fluid Ejector Upgrade to send fluid into BC's Tank, game crash...

### ISSUE THREAD

**Issue by CaptainHarryChen** [BuildCraft/BuildCraft#3843] opened 2017-11-16 05:11 UTC
**Buildcraft** version: 7.99.8
**Forge** version: forge1.11.2-13.20.1.2386
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
[2017-11-16-3.log](https://github.com/BuildCraft/BuildCraft/files/1477393/2017-11-16-3.log)

Singleplayer/multiplayer:  both

Additional information:
When use IC2's Fluid Ejector Upgrade to send fluid into BC's Tank, game crash.Steve can move,but can't open any machine or chest.If quit the game, the program will not responding.

I set mechine like this
![qq 20171116130635](https://user-images.githubusercontent.com/29812003/32874789-5d6c08e6-cacf-11e7-9edb-3ef1ac9b3e7d.png)
![qq 20171116130657](https://user-images.githubusercontent.com/29812003/32874794-627904b0-cacf-11e7-98ec-a21da4e7d806.png)

My Enlish is very pool...............................

**Comment by AEnterprise** [comment] 2017-11-16 07:53
duplicate of #3774, this has also been forwarded to the ic2 bug tracker as we suspect the bug is on there end but no reply on that yet sadly

**Closed by AEnterprise** 2017-11-16 07:53 UTC
