### ISSUE TITLE
Land Marks/Architect

### ISSUE THREAD

**Issue by AgentK9** [BuildCraft/BuildCraft#2590] opened 2015-03-26 17:56 UTC
When I tried to make a blueprint in creative, when I clicked some land marks and then tried to remove them, the red lines stayed there. Also with the architect, some weird things were happening.

**Comment by asiekierka** [comment] 2015-04-01 11:57
What. Reproducible?

**Comment by psxlover** [comment] 2015-04-01 16:32
Haven't tried recently but I remember this happening and I also think I posted of a way to reproduce it.

**Comment by AEnterprise** [comment] 2015-04-02 07:28
ask chilm about this, remember seeing this heapen once on his stream

**Comment by psxlover** [comment] 2015-04-25 21:42
One bug with land marks is that if you place 2 land marks (let's say "A" and "B") and connect them by right clicking "A", then you place another lank mark "C" adjacent to "B" (not to the one you right clicked before) and then right click "C", "A" won't connect to "C".

The other one is harder to reproduce. Here's a way: http://youtu.be/1oZoXSxLSbo

**Comment by asiekierka** [comment] 2015-05-06 20:40
@psxlover - the video is private

**Comment by psxlover** [comment] 2015-05-07 06:19
Oops sorry about that, it should be ok now.

**Comment by hea3ven** [comment] 2015-06-03 00:10
This happens because objects are not properly unlinked in https://github.com/BuildCraft/BuildCraft/blob/6.5.x/common/buildcraft/builders/TileMarker.java#L265-L270. Just making a note here to check it out with more detail later.

**Comment by AEnterprise** [comment] 2016-06-25 11:30
this has been fixed with the rendering rewrite of 1.8+, can be closed

**Comment by AlexIIL** [comment] 2016-06-25 17:35
Yeah, land markers work completly differently now so this sort of thing will happen in different ways.

**Closed by AlexIIL** 2016-06-25 17:35 UTC
Labels: needs investigation
