### ISSUE TITLE
[1.11.2] Advanced Crafting Table cannot craft even if it is fully charged

### ISSUE THREAD

**Issue by stdio2016** [BuildCraft/BuildCraft#3726] opened 2017-07-12 14:34 UTC
Buildcraft version: 7.99.6
Steps to reproduce:
1. Build a advanced crafting table
2. Set your favorite recipe and prepare enough materials
3. Use laser to charge this advanced crafting table
4. When fully charged (500MJ), nothing happens...
![minecraft 1 11 2 2017_7_12 10_15_18](https://user-images.githubusercontent.com/17265792/28122803-d937ea76-6751-11e7-84f5-9dde08280a39.png)

**Comment by AEnterprise** [comment] 2017-07-12 15:28
yeah the table if checking if it has more power then needed in it's buffer, if it has exactly enough it refuses to craft, fixed on my fork for 1.12, will cherry pick to 1.11.2 later

**Comment by CathalK** [comment] 2017-07-18 21:25
Is there any fix or do we have to wait for an update?

**Comment by AEnterprise** [comment] 2017-07-19 06:30
an ingame fix is not possible sadly, the root cause was an internal change that means the assembly table can no longer receive more MJ then it needs to finish it's current crafting operation so a we need to release a new version

a fix was implemented on my 1.12 branch but i'm currently the only available BC dev, the others are out of town so we are not in a position right now to do a new release, once the others return i will backport this fix and others for a release

**Comment by stdio2016** [comment] 2017-07-19 07:16
I can apply this patch https://github.com/AEnterprise/BuildCraft/commit/7cb2c5161d8ff6bb00dc975a76112f4e948b287e on 1.11.2 😆

**Comment by AEnterprise** [comment] 2017-07-19 07:18
yes as i said in my previous comment on this issue: i will apply this one and other fixes i made while working on 1.12 to 1.11.2 later, all at once when we do a new release

**Closed** 2017-08-15 21:23 UTC
Labels: status: fixed/implemented in dev, type: bug, version: 1.11.2
