### ISSUE TITLE
Adding a Config option for RF Compat

### ISSUE THREAD

**Issue by Irgendwer01** [BuildCraft/BuildCraft#4610] opened 2020-10-24 13:14 UTC
**Is your feature request related to a problem? Please describe.**
Due to Buildcraft switched back to MJ most pack devs wont will use it because of the need of converting the energy and not many mods supporting it

**Describe the solution you'd like**
A config option that allows to disable and enable RF Compat if possible

**Comment by AlexIIL** [comment] 2020-10-24 18:51
No, not using RF is intentional.

(Duplicate of #3760 and many others)

**Closed by AlexIIL** 2020-10-24 18:51 UTC
Labels: auto: feature

**Comment by mikeloeven** [comment] 2021-04-03 19:47
> 
> 
> No, not using RF is intentional.
> 
> (Duplicate of #3760 and many others)

No its petty refusal to listen to the user base
