### ISSUE TITLE
Server Crash on startup

### ISSUE THREAD

**Issue by Remanent** [BuildCraft/BuildCraft#3898] opened 2017-12-07 06:39 UTC
Game is crashing on server startup, tried both an existing 1.12.2 world as well as a brand new 1.12.2 world, both crash on startup... existing world was created as a new 1.12.2 world about 2 weeks ago.  No other mods running.

Buildcraft Version 7.99.12 (buildcraft-core-7.99.12.jar)
Forge Version 2555 (forge-1.12.2-14.23.1.2555-universal.jar)
Pastebin: https://pastebin.com/9DA70Z0F
Multiplayer - Server

**Comment by AEnterprise** [comment] 2017-12-07 08:42
the problem is you installed only the core module of buildcraft and that has an dependency on the builders module it shoudn't have (see #3858 )

though since you only have the core module i think you probably ment to install the full version and grabbed the wrong file instead

**Comment by Remanent** [comment] 2017-12-07 09:14
I was trying to use the transport pipes as well, but it cept crashing on startup.. i don't want all of the mod

**Comment by AEnterprise** [comment] 2017-12-07 09:17
can you add builders and transport then and if it still crashes give a new crash report?

**Comment by Remanent** [comment] 2017-12-07 09:17
Copy, working on it now.  Will be back in a few

**Comment by Remanent** [comment] 2017-12-07 09:20
No crash using Core, Transport, and Builders.

**Comment by AEnterprise** [comment] 2017-12-07 09:23
alright probably was the same crash then, once 7.99.13 is out you should be able to remove builders again if you want

**Comment by Remanent** [comment] 2017-12-07 09:25
Getting a client crash during client startup using the core, builders, and transport pipes on the client side.

Buildcraft Version 7.99.12 (buildcraft-core-7.99.12.jar)
Forge Version 2555 (forge-1.12.2-14.23.1.2555-universal.jar)

https://pastebin.com/Dx8BuyMi

**Comment by AEnterprise** [comment] 2017-12-07 09:30
seems there still are some issues with separation of things into the modules

**Comment by AEnterprise** [comment] 2017-12-07 09:36
sorry ment to click 're-open and comment' earlier

**Comment by AlexIIL** [comment] 2017-12-07 13:13
Duplicate of #3873 and #3858.

@Remanent it should work with the modules from https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.13-prereleases/modules/ (which is basically stable, just not released yet.)

**Comment by Remanent** [comment] 2017-12-07 15:26
@AlexIIL Thank You.

Was playing with it, and it's loaded w/ just core and transport without crashes, the guide book however only shows the recipes in game for the core mod, and nothing from the transport mod (looking to introduce this mod to some players that haven't seen it before, and was going to give each of them the book to use since it's there).

**Comment by AlexIIL** [comment] 2017-12-07 15:28
The guide is still a WIP unfortunately. Although you *can* view recipes from other sections by clicking on crafting components (as it takes you to a new page with all of the crafting recipes involving that resource), its just a little annoying as there's no search feature yet, and you have to click through lots of pages and items in order to get to the recipe that you want.

**Comment by Remanent** [comment] 2017-12-07 15:44
@AlexIIL Ah, gotcha.  Definitely not intuitive, but it does work. Thanks again.

**Closed** 2017-12-24 22:16 UTC
Labels: status: fixed/implemented in dev, type: bug, version: 1.12.2
