### ISSUE TITLE
7.9.9.13 Crash game.

### ISSUE THREAD

**Issue by damir84** [BuildCraft/BuildCraft#3936] opened 2017-12-25 16:12 UTC
**Buildcraft** version: 7.9.9.13
**Forge** version: 1.12.2-forge1.12.2-14.23.1.2581
Link to crashreport or log : https://pastebin.com/b5V4NmgY
Singleplayer

Additional information:
[b5V4NmgY.txt](https://github.com/BuildCraft/BuildCraft/files/1585996/b5V4NmgY.txt)

**Comment by AEnterprise** [comment] 2017-12-25 16:13
this is an issue in codechickenlib that has been fixed, please update that mod

**Comment by LuigiHutch** [comment] 2017-12-25 16:14
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3903. Update CodeChickenLib

**Closed by AEnterprise** 2017-12-25 16:13 UTC

**Comment by damir84** [comment] 2017-12-25 16:22
Updated Codechicken and it works. Thank you!
