### ISSUE TITLE
[7.99.4] Rendering screen

### ISSUE THREAD

**Issue by SvEgiiVEteR** [BuildCraft/BuildCraft#3691] opened 2017-06-28 03:49 UTC
Opened inventory and after 5 seconds crash
https://gist.github.com/5c402a527ff5321017e7269f362c9148

**Comment by afdw** [comment] 2017-06-28 07:00
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3639.

**Closed by afdw** 2017-06-28 07:00 UTC
Labels: type: caused by other mod, version: 1.11.2
