### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Groundedrex** [BuildCraft/BuildCraft#4669] opened 2022-02-19 19:29 UTC
made a modpack but the current buildcraft keeps crashing and when i go to previous versions it interferes with redstone flux what should i do 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_21.5.0_Forge_1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 2/19/22 2:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.Error: Failed to create a page link for immersivepetroleum:schematic class flaxbeard.immersivepetroleum.common.items.ItemProjector ({id:"immersivepetroleum:schematic",Count:1b,tag:{multiblock:"II:Packer"},Damage:0s})
	at buildcraft.lib.client.guide.entry.PageEntryItemStack.iterateAllDefault(PageEntryItemStack.java:114)
	at buildcraft.lib.client.guide.GuideManager.generateContentsPage(GuideManager.java:337)
	at buildcraft.lib.client.guide.GuideManager.reload0(GuideManager.java:203)
	at buildcraft.lib.client.guide.GuideManager.reload(GuideManager.java:132)
	at buildcraft.lib.client.guide.GuideManager.func_110549_a(GuideManager.java:119)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at buildcraft.lib.BCLibProxy$ClientProxy.fmlPostInit(BCLibProxy.java:173)
	at buildcraft.lib.BCLib.postInit(BCLib.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at flaxbeard.immersivepetroleum.common.items.ItemProjector.func_77624_a(ItemProjector.java:92)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at buildcraft.lib.misc.GuiUtil.getUnFormattedTooltip(GuiUtil.java:449)
	at buildcraft.lib.client.guide.parts.contents.PageLinkItemStack.getTooltip(PageLinkItemStack.java:43)
	at buildcraft.lib.client.guide.parts.contents.PageLinkItemStack.create(PageLinkItemStack.java:29)
	at buildcraft.lib.client.guide.entry.PageEntryItemStack.iterateAllDefault(PageEntryItemStack.java:110)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 974665664 bytes (929 MB) / 2548563968 bytes (2430 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 87 mods loaded, 87 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                              | Signature                                |
	|:----- |:--------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft             | 1.12.2                   | minecraft.jar                                       | None                                     |
	| LCHIJ | mcp                   | 9.42                     | minecraft.jar                                       | None                                     |
	| LCHIJ | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                 | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | micdoodlecore         |                          | minecraft.jar                                       | None                                     |
	| LCHIJ | xaerominimap_core     | 1.12.2-1.0               | minecraft.jar                                       | None                                     |
	| LCHIJ | foamfixcore           | 7.7.4                    | minecraft.jar                                       | None                                     |
	| LCHIJ | randompatches         | 1.12.2-1.22.1.10         | randompatches-1.12.2-1.22.1.10.jar                  | None                                     |
	| LCHIJ | aiimprovements        | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                     | None                                     |
	| LCHIJ | appliedenergistics2   | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar                | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJ | ichunutil             | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJ | backtools             | 7.0.1                    | BackTools-1.12.2-7.0.1.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJ | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                              | None                                     |
	| LCHIJ | betterpingdisplay     | 1.0                      | BetterPingDisplay-1.12.2-1.0.jar                    | None                                     |
	| LCHIJ | betterthanbunnies     | 1.12.1-1.1.0             | BetterThanBunnies-1.12.1-1.1.0.jar                  | None                                     |
	| LCHIJ | bibliocraft           | 2.4.6                    | BiblioCraft[v2.4.6][MC1.12.2].jar                   | None                                     |
	| LCHIJ | biomesoplenty         | 7.0.1.2445               | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar       | None                                     |
	| LCHIJ | bonsaitrees           | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                          | None                                     |
	| LCHIJ | codechickenlib        | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ | redstoneflux          | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar             | None                                     |
	| LCHIJ | brandonscore          | 2.4.20                   | BrandonsCore-1.12.2-2.4.20.162-universal.jar        | None                                     |
	| LCHIE | buildcraftlib         | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | buildcraftcore        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | buildcraftbuilders    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | buildcrafttransport   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | buildcraftsilicon     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | buildcraftcompat      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | buildcraftenergy      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | buildcraftfactory     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | buildcraftrobotics    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                        | None                                     |
	| LCHI  | carpentersblocks      | 3.4.0-poc.6              | Carpenter's Blocks v3.4.0-poc.6 - MC 1.12.2 (1).jar | None                                     |
	| LCHI  | carryon               | 1.12.3                   | carryon-1.12.2-1.12.3.15.jar                        | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHI  | jei                   | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                           | None                                     |
	| LCHI  | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                            | None                                     |
	| LCHI  | twilightforest        | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar       | None                                     |
	| LCHI  | tconstruct            | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                    | None                                     |
	| LCHI  | ceramics              | 1.12-1.3.7b              | Ceramics-1.12-1.3.7b.jar                            | None                                     |
	| LCHI  | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                            | None                                     |
	| LCHI  | chancecubes           | 1.12.2-5.0.2.385         | ChanceCubes-1.12.2-5.0.2.385.jar                    | None                                     |
	| LCHI  | chickenchunks         | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | chickens              | 6.0.4                    | chickens-6.0.4.jar                                  | None                                     |
	| LCHI  | chiselsandbits        | 14.33                    | chiselsandbits-14.33.jar                            | None                                     |
	| LCHI  | cyclicmagic           | 1.20.8                   | Cyclic-1.12.2-1.20.8.jar                            | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCHI  | draconicevolution     | 2.3.28                   | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar  | None                                     |
	| LCHI  | draconicadditions     | 1.17.0                   | Draconic-Additions-1.12.2-1.17.0.45-universal.jar   | None                                     |
	| LCHI  | elevatorid            | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                       | None                                     |
	| LCHI  | enchdesc              | 1.1.20                   | EnchantmentDescriptions-1.12.2-1.1.20.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | enderstorage          | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | engineersdecor        | 1.1.3                    | engineersdecor-1.12.2-1.1.3.jar                     | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHI  | extrautils2           | 1.0                      | extrautils2-1.12-1.9.9.jar                          | None                                     |
	| LCHI  | fat_cat               | 0.0.5                    | FatCat-0.0.5.jar                                    | None                                     |
	| LCHI  | flansmod              | 5.10.0                   | Flan's+Mod-1.12.2-5.10.0.jar                        | None                                     |
	| LCHI  | foamfix               | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                          | None                                     |
	| LCHI  | cfm                   | 6.3.1                    | furniture-6.3.1-1.12.2.jar                          | None                                     |
	| LCHI  | galacticraftcore      | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar               | None                                     |
	| LCHI  | galacticraftplanets   | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar           | None                                     |
	| LCHI  | glassdoors            | 1.0.0                    | glassdoors-1.12.2-1.0.0.jar                         | None                                     |
	| LCHI  | gravestone            | 1.10.3                   | gravestone-1.10.3.jar                               | None                                     |
	| LCHI  | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
	| LCHI  | immersiveengineering  | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                    | None                                     |
	| LCHI  | immersivepetroleum    | 1.1.10                   | immersivepetroleum-1.12.2-1.1.10.jar                | None                                     |
	| LCHI  | trackapi              | 1.2                      | TrackAPI-1.2.jar                                    | None                                     |
	| LCHI  | universalmodcore      | 1.1.3                    | UniversalModCore-1.12.2-forge-1.1.3.jar             | None                                     |
	| LCHI  | immersiverailroading  | 1.9.1                    | ImmersiveRailroading-1.12.2-forge-1.9.1.jar         | None                                     |
	| LCHI  | ironchest             | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                     | None                                     |
	| LCHI  | mcwbridges            | 1.0.4                    | mcw-bridges-1.0.4-mc1.12.2.jar                      | None                                     |
	| LCHI  | mekanism              | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                       | None                                     |
	| LCHI  | minecoprocessors      | 1.12.2-5                 | minecoprocessors-1.12.2-5.jar                       | None                                     |
	| LCHI  | miner_block           | 1.0.0                    | MinerBlock-1_12_2-1_0.jar                           | None                                     |
	| LCHI  | nuclearcraft          | 2.18zz                   | NuclearCraft-2.18zz-1.12.2.jar                      | None                                     |
	| LCHI  | oreexcavation         | 1.4.150                  | OreExcavation-1.4.150.jar                           | None                                     |
	| LCHI  | projecte              | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                         | None                                     |
	| LCHI  | projectintelligence   | 1.0.9                    | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar   | None                                     |
	| LCHI  | roost                 | 2.0.10                   | roost-1.12.2-2.0.10.jar                             | None                                     |
	| LCHI  | simplepartspack       | 5.7.2                    | Simple+Parts-Content+Pack-1.12.2-5.7.2.jar          | None                                     |
	| LCHI  | storagedrawers        | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                     | None                                     |
	| LCHI  | tcomplement           | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar                  | None                                     |
	| LCHI  | tinkertoolleveling    | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                 | None                                     |
	| LCHI  | travelersbackpack     | 1.0.35                   | TravelersBackpack-1.12.2-1.0.35.jar                 | None                                     |
	| LCHI  | tropicraft            | 7.1.9.115                | tropicraft-MC1.12.2-7.1.9.115.jar                   | None                                     |
	| LCHI  | waystones             | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                          | None                                     |
	| LCHI  | wopper                | 1.12-r5                  | Wopper-1.12-r5.jar                                  | None                                     |
	| LCHI  | ww2pack               | 5.7.2                    | WW2-Content+Pack-1.12.2-5.7.2.jar                   | None                                     |
	| LCHI  | xaerominimap          | 21.5.0                   | Xaeros_Minimap_21.5.0_Forge_1.12.jar                | None                                     |
	| LCHI  | yeoldepack            | 5.8.2                    | Ye+Olde-Content+Pack-1.12.2-5.8.2.jar               | None                                     |
	| LCHI  | immersiveintelligence | 0.2.1                    | immersiveintelligence-0.2.1.jar                     | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |
	| LCHI  | fluidcows             | 1.1.22                   | FluidCows-1.1.22.jar                                | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_21.5.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
  com.therandomlabs.randompatches.core.RPTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14742 Compatibility Profile Context 21.8.2 27.20.22025.1006' Renderer: 'Radeon RX 570 Series'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleMelter (Enabled/Not Forced)
		- ModuleArmor (Enabled/Not Forced)
		- ModuleSteelworks (Enabled/Not Forced)
		- CeramicsPlugin (Enabled/Not Forced)
		- ToolLevelingPlugin (Enabled/Not Forced)
		- Oredict (Enabled/Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF

**Comment by AlexIIL** [comment] 2022-02-27 15:52
This is a duplicate of https://github.com/BuildCraft/BuildCraft/issues/4664.

**Closed by AlexIIL** 2022-02-27 15:52 UTC
Labels: auto: crash
