### ISSUE TITLE
Unable to hook up buildcraft engines

### ISSUE THREAD

**Issue by KiraAmano** [BuildCraft/BuildCraft#3821] opened 2017-09-24 12:29 UTC
**Buildcraft** version: 7.99.7
**Forge** version: 1.11.2
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) :  None
Singleplayer/multiplayer: Both

Additional information:
I tried to hook up a redstone engine, stirling engine, and creative engine (seperately) to forestry's autofarm using the farm gearbox. Not only did this not work, but when trying to hook up buildcraft's kinesis pipes to an engine and then subsequently the farm, the pipes also didn't connect into the gearbox. 

This is odd, as in other versions it has been compatible.

**Comment by LuigiHutch** [comment] 2017-09-24 12:38
Thanks for the report. This is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3760 This will be fixed once BC leaves alpha and the API is stable

**Closed** 2017-09-24 12:39 UTC
Labels: duplicate, version: 1.11.2
