### ISSUE TITLE
oil in the nether buildcraft 7.99.7

### ISSUE THREAD

**Issue by zezreli** [BuildCraft/BuildCraft#3824] opened 2017-09-25 17:38 UTC
**Buildcraft** version: 7.99.7
**Forge** version: 13.20.1.2476
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: singleplayer

Additional information:
it spawned oil in the nether on seed :  4892394019845594397
and cords : x = -324 z= -69 y = 59
around there should it be

![2017-09-25_19 19 01](https://user-images.githubusercontent.com/27296782/30822432-09526eea-a229-11e7-8b03-32979db14715.png)
![2017-09-25_19 18 58](https://user-images.githubusercontent.com/27296782/30822431-094f8c2a-a229-11e7-8f48-bfef23599852.png)

**Comment by zezreli** [comment] 2017-09-25 17:39
more correct cords and be seen on the pictures at the map

**Comment by AEnterprise** [comment] 2017-09-25 17:42
duplicate of #3812

**Closed by AEnterprise** 2017-09-25 17:42 UTC
