### ISSUE TITLE
Stirling Engine Consumes Buckets

### ISSUE THREAD

**Issue by Holzstock** [BuildCraft/BuildCraft#3679] opened 2017-06-19 11:08 UTC
When putting a Lava-bucket into the Stirling-engine the bucket disappears without returning an empty bucket.

**Comment by LuigiHutch** [comment] 2017-06-19 11:09
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3619. Update to 7.99.4

**Closed** 2017-06-19 11:11 UTC
Labels: duplicate
