### ISSUE TITLE
1.12.2 Invalid Property

### ISSUE THREAD

**Issue by Caeas** [BuildCraft/BuildCraft#4459] opened 2019-08-10 12:45 UTC
On Startup the server reports invalid property errors all the time.

#### Affected Versions

- BuildCraft **buildcraft-all-7.99.24.2.jar**
- Minecraft: **1.12.2**
- Forge: **forge-1.12.2-14.23.5.2838-universal**
- SpongeForge? **no**
- Optifine? **no**
- Single Player and/or Server? **Server**

sorry for the close was accendiatly. Not sure if this is a duplicate with the existing ones sorry :(

#### Logfile

https://pastebin.com/D46WwL6P

**Comment by AEnterprise** [comment] 2019-08-10 12:54
duplicate of #4343

**Closed by AEnterprise** 2019-08-10 12:54 UTC
