### ISSUE TITLE
Render error for only client pipes (pump & quarry)

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3299] opened 2016-04-12 12:11 UTC
when looking upwards from below the pipe sometimes just disappears
![2016-04-11_15 18 46](https://cloud.githubusercontent.com/assets/5960902/14459444/517a944a-00b8-11e6-82c4-4560ca7ff5e2.png)
![2016-04-11_15 18 50](https://cloud.githubusercontent.com/assets/5960902/14459447/53612f6c-00b8-11e6-9628-f4b67ec9675b.png)

From two different angles (sorry that it's night-timed)

**Comment by AlexIIL** [comment] 2016-04-12 13:25
This happens with the quarry too?

**Comment by rapus95** [comment] 2016-04-12 15:07
yeah for me it did; some pics will follow

**Comment by rapus95** [comment] 2016-04-12 15:18
![2016-04-12_17 18 24](https://cloud.githubusercontent.com/assets/5960902/14465267/966e3664-00d2-11e6-8157-5f709562d9cc.png)
![2016-04-12_17 18 27](https://cloud.githubusercontent.com/assets/5960902/14465273/9bd54ce6-00d2-11e6-988d-f16fb3ddc849.png)
But it seems to only happen if the quarry is not running

**Comment by rapus95** [comment] 2016-04-12 15:21
as fas i can see it's some small spawn of vertical angles at which it is not rendered properly the angle is somewhat dowards as you can see (in any upwards angles i haven't been able to reproduce it)
Oh and i might should mention i'm using optifine :/ going to test w/o it

**Comment by rapus95** [comment] 2016-04-12 15:38
For the pump ingame facing vertical value shows -31.5 to -39
and for the quarry it's 39 to 31.5 aswell

**Comment by AEnterprise** [comment] 2016-04-12 15:51
optifine is probably the causing it, remove it and see if you can still reproduce

**Comment by SandGrainOne** [comment] 2016-04-12 15:53
Which version of BC is this? Because I noticed the same in BC 8.

**Comment by rapus95** [comment] 2016-04-12 17:00
7.2.5 and the values were w/o optifine

**Comment by rapus95** [comment] 2016-04-12 17:27
I now tested w/ and w/o Optifine and in both cases the results were equal

**Comment by AlexIIL** [comment] 2016-04-12 17:30
Thanks. I'll look into it then.

**Comment by AEnterprise** [comment] 2016-04-12 17:30
alright must be a rendering bounding box issue then

**Comment by AlexIIL** [comment] 2016-04-28 14:26
Closed via commit, 7.2.6 should be released shortly.

**Closed by AlexIIL** 2016-04-28 14:26 UTC
Labels: bug
