### ISSUE TITLE
[1.11.2] Error block logic (BC Tank <= IC2 Fermenter + biogas ejector)

### ISSUE THREAD

**Issue by kjl2875** [BuildCraft/BuildCraft#3682] opened 2017-06-20 08:24 UTC
![error](https://user-images.githubusercontent.com/29188361/27323585-f948e274-55dc-11e7-996b-e8a4f55d10bf.jpg)
[in single player and multi player]

I can't now open gui in block (Everything)
maybe it's some where running infinity roof code. (just guess)
and I can move around destory block.

**Comment by AEnterprise** [comment] 2017-06-20 08:28
does this work with other tanks? also can you upload the log from when this heapened? if you don't know for sure what log then start the game, reproduce the error and upload the latest logfile (to gist/pastebin please and link here)

**Comment by kjl2875** [comment] 2017-06-20 09:01
It works in IC2 fluid tank.
and here log and video.

[https://youtu.be/LWuqHj1486M](https://youtu.be/LWuqHj1486M)

industrialcraft-2-2.7.59-ex111.jar
buildcraft-7.99.4.jar (Aplha)

------------ Log here -------------
[17:46:27] [Client thread/INFO]: Setting user: USER!
[17:46:28] [Client thread/INFO]: [STDOUT]: [itemphysic] Patched net.minecraft.entity.item.EntityItem ...
[17:46:30] [Client thread/INFO]: [STDERR]: Potential problem: Galacticraft did not complete injection of bytecode into: bqe (4 / 6)
[17:46:31] [Client thread/WARN]: Skipping bad option: lastServer:
[17:46:31] [Client thread/INFO]: LWJGL Version: 2.9.4
[17:46:42] [Client thread/INFO]: Reloading ResourceManager: BetterFps, Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Actually Additions, FMLFileResourcePack:AutoRegLib, FMLFileResourcePack:Baubles, FMLFileResourcePack:BD Lib, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BuildCraft Lib, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:Crop-Eating Animals, FMLFileResourcePack:MrCrayfish's Furniture Mod, FMLFileResourcePack:Colossal Chests, FMLFileResourcePack:Compact Solar Arrays, FMLFileResourcePack:Cyclops Core, FMLFileResourcePack:Forestry, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:GenDustry, FMLFileResourcePack:Advanced Generators, FMLFileResourcePack:Immersive Craft, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough HarvestCraft, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:JEI Bees, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Morph-o-Tool, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:Reborn Core, FMLFileResourcePack:reborncore-MCMultiPart, FMLFileResourcePack:RFTools, FMLFileResourcePack:Steve's Carts 2, FMLFileResourcePack:WorldEdit, Faithful 1.11.2-rv4.zip
[17:46:55] [Client thread/INFO]: [STDOUT]: [itemphysic] Patched net.minecraft.client.renderer.entity.RenderEntityItem ...
[17:47:07] [Client thread/WARN]: File minecraft:sounds/gearswitch.ogg does not exist, cannot add it to event stevescarts:gearswitch
[17:47:07] [Client thread/WARN]: File minecraft:sounds/win.ogg does not exist, cannot add it to event stevescarts:win
[17:47:07] [Client thread/WARN]: File minecraft:sounds/boop1.ogg does not exist, cannot add it to event stevescarts:boop
[17:47:07] [Client thread/WARN]: File minecraft:sounds/boop2.ogg does not exist, cannot add it to event stevescarts:boop
[17:47:07] [Client thread/WARN]: File minecraft:sounds/boop3.ogg does not exist, cannot add it to event stevescarts:boop
[17:47:07] [Client thread/WARN]: File minecraft:sounds/gameover.ogg does not exist, cannot add it to event stevescarts:gameover
[17:47:07] [Client thread/WARN]: File minecraft:sounds/1lines.ogg does not exist, cannot add it to event stevescarts:1lines
[17:47:07] [Client thread/WARN]: File minecraft:sounds/2lines.ogg does not exist, cannot add it to event stevescarts:2lines
[17:47:07] [Client thread/WARN]: File minecraft:sounds/3lines.ogg does not exist, cannot add it to event stevescarts:3lines
[17:47:07] [Client thread/WARN]: File minecraft:sounds/4lines.ogg does not exist, cannot add it to event stevescarts:4lines
[17:47:07] [Client thread/WARN]: File minecraft:sounds/highscore.ogg does not exist, cannot add it to event stevescarts:highscore
[17:47:07] [Client thread/WARN]: File minecraft:sounds/hit.ogg does not exist, cannot add it to event stevescarts:hit
[17:47:07] [Client thread/WARN]: File minecraft:sounds/click.ogg does not exist, cannot add it to event stevescarts:click
[17:47:07] [Client thread/WARN]: File minecraft:sounds/blobclick.ogg does not exist, cannot add it to event stevescarts:blobclick
[17:47:07] [Client thread/WARN]: File minecraft:sounds/flagclick.ogg does not exist, cannot add it to event stevescarts:flagclick
[17:47:07] [Client thread/WARN]: File minecraft:sounds/goodjob.ogg does not exist, cannot add it to event stevescarts:goodjob
[17:47:07] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:47:07] [Thread-12/INFO]: Initializing LWJGL OpenAL
[17:47:07] [Thread-12/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:47:07] [Thread-12/INFO]: OpenAL initialized.
[17:47:07] [Sound Library Loader/INFO]: Sound engine started
[17:47:11] [Client thread/INFO]: Created: 16x16 textures-atlas
[17:47:18] [Client thread/INFO]: [STDOUT]: TrueTypeFont loaded: java.awt.Font[family=Ubuntu,name=Ubuntu,style=plain,size=64] - AntiAlias = false
[17:47:18] [Client thread/INFO]: [STDOUT]: TrueTypeFont loaded: java.awt.Font[family=Ubuntu,name=Ubuntu Bold,style=plain,size=64] - AntiAlias = false
[17:47:18] [Client thread/INFO]: [STDOUT]: TrueTypeFont loaded: java.awt.Font[family=Ubuntu,name=Ubuntu Italic,style=plain,size=64] - AntiAlias = false
[17:47:19] [Client thread/INFO]: [STDOUT]: TrueTypeFont loaded: java.awt.Font[family=Ubuntu,name=Ubuntu,style=plain,size=40] - AntiAlias = false
[17:47:25] [Client thread/INFO]: Reloading ResourceManager: BetterFps, Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Actually Additions, FMLFileResourcePack:AutoRegLib, FMLFileResourcePack:Baubles, FMLFileResourcePack:BD Lib, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BuildCraft Lib, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:Crop-Eating Animals, FMLFileResourcePack:MrCrayfish's Furniture Mod, FMLFileResourcePack:Colossal Chests, FMLFileResourcePack:Compact Solar Arrays, FMLFileResourcePack:Cyclops Core, FMLFileResourcePack:Forestry, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:GenDustry, FMLFileResourcePack:Advanced Generators, FMLFileResourcePack:Immersive Craft, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough HarvestCraft, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:JEI Bees, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Morph-o-Tool, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:Reborn Core, FMLFileResourcePack:reborncore-MCMultiPart, FMLFileResourcePack:RFTools, FMLFileResourcePack:Steve's Carts 2, FMLFileResourcePack:WorldEdit, FMLFileResourcePack:Minecraft Forge, Faithful 1.11.2-rv4.zip
[17:47:25] [Client thread/WARN]: File minecraft:sounds/gearswitch.ogg does not exist, cannot add it to event stevescarts:gearswitch
[17:47:25] [Client thread/WARN]: File minecraft:sounds/win.ogg does not exist, cannot add it to event stevescarts:win
[17:47:25] [Client thread/WARN]: File minecraft:sounds/boop1.ogg does not exist, cannot add it to event stevescarts:boop
[17:47:25] [Client thread/WARN]: File minecraft:sounds/boop2.ogg does not exist, cannot add it to event stevescarts:boop
[17:47:25] [Client thread/WARN]: File minecraft:sounds/boop3.ogg does not exist, cannot add it to event stevescarts:boop
[17:47:25] [Client thread/WARN]: File minecraft:sounds/gameover.ogg does not exist, cannot add it to event stevescarts:gameover
[17:47:25] [Client thread/WARN]: File minecraft:sounds/1lines.ogg does not exist, cannot add it to event stevescarts:1lines
[17:47:25] [Client thread/WARN]: File minecraft:sounds/2lines.ogg does not exist, cannot add it to event stevescarts:2lines
[17:47:25] [Client thread/WARN]: File minecraft:sounds/3lines.ogg does not exist, cannot add it to event stevescarts:3lines
[17:47:25] [Client thread/WARN]: File minecraft:sounds/4lines.ogg does not exist, cannot add it to event stevescarts:4lines
[17:47:25] [Client thread/WARN]: File minecraft:sounds/highscore.ogg does not exist, cannot add it to event stevescarts:highscore
[17:47:25] [Client thread/WARN]: File minecraft:sounds/hit.ogg does not exist, cannot add it to event stevescarts:hit
[17:47:25] [Client thread/WARN]: File minecraft:sounds/click.ogg does not exist, cannot add it to event stevescarts:click
[17:47:25] [Client thread/WARN]: File minecraft:sounds/blobclick.ogg does not exist, cannot add it to event stevescarts:blobclick
[17:47:25] [Client thread/WARN]: File minecraft:sounds/flagclick.ogg does not exist, cannot add it to event stevescarts:flagclick
[17:47:25] [Client thread/WARN]: File minecraft:sounds/goodjob.ogg does not exist, cannot add it to event stevescarts:goodjob
[17:47:25] [Client thread/INFO]: SoundSystem shutting down...
[17:47:26] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[17:47:26] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:47:26] [Thread-20/INFO]: Initializing LWJGL OpenAL
[17:47:26] [Thread-20/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:47:26] [Thread-20/INFO]: OpenAL initialized.
[17:47:26] [Sound Library Loader/INFO]: Sound engine started
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercellw.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercellu.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercells.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercelle.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercelld.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load rftools:textures/blocks/powercelln.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load stevescarts:textures/items/large_sctank_pane_icon.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/bookshelf_connect/0.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/bookshelf_connect/1.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/bookshelf_connect/2.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load stevescarts:textures/items/sctank_pane_icon.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load minecraft:mcpatcher/ctm/bookshelf_connect/3.png, java.io.FileNotFoundException
[17:47:28] [Client thread/ERROR]: Using missing texture, unable to load stevescarts:textures/items/huge_sctank_pane_icon.png, java.io.FileNotFoundException
[17:47:29] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/blocks/leaves_oak.png, java.io.FileNotFoundException
[17:47:29] [Client thread/ERROR]: Using missing texture, unable to load stevescarts:textures/items/sctank_valve_icon.png, java.io.FileNotFoundException
[17:47:30] [Client thread/INFO]: Created: 4096x4096 textures-atlas
[17:47:34] [Client thread/WARN]: Unable to resolve texture due to upward reference: #1 in cfm:models/block/blinds_closed
[17:47:37] [Client thread/WARN]: Skipping bad option: lastServer:
[17:47:52] [Client thread/INFO]: Deleting level 새로운 세계--
[17:47:52] [Client thread/INFO]: Attempt 1...
[17:47:54] [Client thread/INFO]: Deleting level 새로운 세계
[17:47:54] [Client thread/INFO]: Attempt 1...
[17:47:55] [Client thread/INFO]: Deleting level 새로운 세계-
[17:47:55] [Client thread/INFO]: Attempt 1...
[17:48:08] [Server thread/INFO]: Starting integrated minecraft server version 1.11.2
[17:48:08] [Server thread/INFO]: Generating keypair
[17:48:09] [Server thread/INFO]: [STDOUT]: settings for hell world: 
[17:48:10] [Server thread/INFO]: Preparing start region for level 0
[17:48:11] [Server thread/INFO]: Preparing spawn area: 9%
[17:48:12] [Server thread/INFO]: Preparing spawn area: 18%
[17:48:13] [Server thread/INFO]: Preparing spawn area: 28%
[17:48:14] [Server thread/INFO]: Preparing spawn area: 39%
[17:48:15] [Server thread/INFO]: Preparing spawn area: 49%
[17:48:16] [Server thread/INFO]: Preparing spawn area: 59%
[17:48:17] [Server thread/INFO]: Preparing spawn area: 71%
[17:48:18] [Server thread/INFO]: Preparing spawn area: 81%
[17:48:19] [Server thread/INFO]: Preparing spawn area: 93%
[17:48:20] [Server thread/INFO]: Changing view distance to 16, from 10
[17:48:21] [Server thread/INFO]: USER![local:E:b62cccda] logged in with entity id 704 at (213.5, 64.0, 217.5)
[17:48:21] [Server thread/INFO]: USER! has joined the game
[17:48:21] [Server thread/INFO]: USER! has just earned the achievement [You've been installed!]
[17:48:24] [Thread-36/INFO]: [CHAT] WARNING: BuildCraft 7.99.4 is in ALPHA!
[17:48:24] [Thread-36/INFO]: [CHAT]   Report bugs you find here
[17:48:24] [Thread-36/INFO]: [CHAT]   and include the version 7.99.4 in the description
[17:48:25] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4981ms behind, skipping 99 tick(s)
[17:48:25] [Server thread/INFO]: Saving and pausing game...
[17:48:25] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[17:48:25] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[17:48:25] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[17:48:25] [Server thread/INFO]: Saving chunks for level 'New World'/Moon
[17:48:25] [Server thread/INFO]: Saving chunks for level 'New World'/Mars
[17:48:25] [Server thread/INFO]: Saving chunks for level 'New World'/Asteroids
[17:48:25] [Server thread/INFO]: Saving chunks for level 'New World'/Venus
[17:48:25] [Client thread/INFO]: [CHAT] USER! has just earned the achievement [You've been installed!]
[17:48:25] [Client thread/INFO]: [CHAT] §6Thank you for downloading MrCrayfish's Furniture Mod
[17:48:25] [Client thread/INFO]: [CHAT] §6-> §aCheck out the Furniture Mod Wiki
[17:48:25] [Client thread/INFO]: [CHAT] §6-> §rmrcrayfishs-furniture-mod.wikia.com
[17:48:25] [Client thread/INFO]: [CHAT] [Cyclops Core] Update available: 0.10.6 [Download]
[17:48:25] [Client thread/INFO]: [CHAT] [Cyclops Core]§f Fix Minetweaker crash
[17:48:28] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Press [§bJ§f]
[17:48:37] [Server thread/INFO]: USER! has just earned the achievement [Taking Inventory]
[17:48:37] [Client thread/INFO]: [CHAT] USER! has just earned the achievement [Taking Inventory]
[17:48:44] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 8867ms behind, skipping 177 tick(s)
[17:48:52] [Client thread/INFO]: [CHAT] There is an Update for Actually Additions available!
[17:48:52] [Client thread/INFO]: [CHAT] Current Version: 1.11.2-r109, newest Version: 1.11.2-r110
[17:48:52] [Client thread/INFO]: [CHAT] [Click for Changelog] [Click for Download]
[17:50:11] [Client thread/INFO]: [CHAT] Automatically output to the west side

**Comment by AEnterprise** [comment] 2017-06-20 09:09
i asked for a gist/pastebin not a wall of text

looking at the log and the video it seems your computer can't keep up at all and the server thread is getting stuck

if you reproduce it again and take a thread dump with a tool like visualVM that might show what is getting stuck although i do suspect that for some reason IC2 is getting stuck in a loop somewhere but i don't know why

**Comment by AEnterprise** [comment] 2017-06-20 13:37
could you instead install sampler and then have it generate a stall report when you try to reproduce it? in that case do not kill minecraft yourself but let the watchdog kill it so sampler can do it's work

**Comment by AEnterprise** [comment] 2017-06-30 19:12
closing as i couldn't reproduce in a test world

**Closed by AEnterprise** 2017-06-30 19:12 UTC
Labels: version: 1.11.2
