### ISSUE TITLE
[1.11.2] [BC7.99.4] Crash Bug with 100 mod pack

### ISSUE THREAD

**Issue by rockbanddude** [BuildCraft/BuildCraft#3658] opened 2017-06-07 22:51 UTC
I am currently trying to build a semi-stable 1.11 pack, but I just started having this crash bug. It started while I was playing with Melanism, but Mekanism doesn't show up in crash report.

https://pastebin.com/DRcdNzUu

**Comment by afdw** [comment] 2017-06-07 22:52
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3639.

**Closed by afdw** 2017-06-07 22:52 UTC
Labels: duplicate, version: 1.11.2

**Comment by rockbanddude** [comment] 2017-06-08 00:56
Just removed NEI, I'll report to them later

**Comment by afdw** [comment] 2017-06-08 00:57
Already reported: https://github.com/TheCBProject/NotEnoughItems/issues/100
