### ISSUE TITLE
I encountered a nullpointerexception bug.

### ISSUE THREAD

**Issue by Omarsd** [BuildCraft/BuildCraft#3935] opened 2017-12-24 21:53 UTC
First of all, I have to say that your mod is amazing. I could build a sort system out of pipes that works really well.

 Second of all, when I decided to use Obsidian Pipes instead of Hoppers to suck dropped items from my xp farm it crashed. I saw on the internet that if you connect that pipe with an engine (I used a redstone one) you can suck further, so I did and crashed. I've created several new worlds to test if It happens every time, and it does. The problem is that I cannot open my original world, since it crash every time.

**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2555 
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at buildcraft.transport.pipe.behaviour.PipeBehaviourObsidian.getSuckingBox(PipeBehaviourObsidian.java:110)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourObsidian.receivePower(PipeBehaviourObsidian.java:195)
	at buildcraft.transport.pipe.behaviour.PipeBehaviourObsidian.getPowerRequested(PipeBehaviourObsidian.java:185)
	at buildcraft.lib.engine.TileEngineBase_BC8.getPowerToExtract(TileEngineBase_BC8.java:352)
	at buildcraft.lib.engine.TileEngineBase_BC8.func_73660_a(TileEngineBase_BC8.java:316)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

Singleplayer/multiplayer: both.

Additional information:

I will try to see if I can edit those blocks with some program like MCEdit so I can still playing on my world. Thank you for your time.

**Comment by AEnterprise** [comment] 2017-12-24 21:56
duplicate of #3884 , already fixed for next release

**Closed by AEnterprise** 2017-12-24 21:56 UTC
