### ISSUE TITLE
robot is missing 

### ISSUE THREAD

**Issue by ecolortest** [BuildCraft/BuildCraft#3926] opened 2017-12-21 12:25 UTC
**Buildcraft** version: 7.99.8.1
**Forge** version: 13.20.1.2563
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Sigleplayer 

Additional information: robots is missing at  7.99.8.1 (1.11.2), can you fix this?

**Comment by LuigiHutch** [comment] 2017-12-21 12:25
Thanks for the report, this is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3755

**Comment by ecolortest** [comment] 2017-12-21 12:26
thanks

**Closed** 2017-12-21 12:33 UTC
