### ISSUE TITLE
Oil Spawns at Default surface height on Superflat World

### ISSUE THREAD

**Issue by liamiam** [BuildCraft/BuildCraft#3889] opened 2017-12-03 16:03 UTC
**Buildcraft** version: 7.99.8.1
**Forge** version: 13.20.1.2530
Link to crash report or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Singleplayer

Additional information:
Im not sure how this happened...
![2017-12-03_07 54 35](https://user-images.githubusercontent.com/8386828/33527135-4bd31c3a-d800-11e7-91d9-0680c3b0f6b7.png)
![2017-12-03_07 54 49](https://user-images.githubusercontent.com/8386828/33527136-4bec5a4c-d800-11e7-9741-ea679dd7e17c.png)
![2017-12-03_07 57 06](https://user-images.githubusercontent.com/8386828/33527137-4c068606-d800-11e7-99fe-641b427dd53b.png)
Oil should not really be that high.
And it dosen't make since because in older versions this dosen't happen.

**Comment by LuigiHutch** [comment] 2017-12-03 16:05
Thanks for the report. This is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3837

**Closed** 2017-12-03 16:06 UTC
