### ISSUE TITLE
Mekanism Generators 

### ISSUE THREAD

**Issue by Saitek2073** [BuildCraft/BuildCraft#3748] opened 2017-07-20 22:57 UTC
Mekanism Generators dose not work with current build 7.9.9.6

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MekanismGenerators (mekanismgenerators)

**Comment by AEnterprise** [comment] 2017-07-21 07:41
for future reference please upload the full crashlog on gist and link here as that one line you linked only tells us something in mekanism crashed (you usually also want to report it to the mod that actually crashing)

but it's a known mekanism issue, see their issue (aidancbrady/Mekanism#4513) for details. duplicate of #3716

**Closed by AEnterprise** 2017-07-21 07:41 UTC
