### ISSUE TITLE
[1.8] Pipes disappearing client-side

### ISSUE THREAD

**Issue by purpleposeidon** [BuildCraft/BuildCraft#3193] opened 2016-01-28 08:56 UTC
Probably caused by walking far enough away for the chunks to unload client-side, and walking back?

The pipes have a collision box, but do not ray-trace and do not render.

**Comment by AlexIIL** [comment] 2016-01-28 12:48
This is an annoying reoccurring issue with most tile entities I think, but they show up if you place a block next to them. I wasn't aware this happened when you walked far enough away as well though...

**Comment by AEnterprise** [comment] 2016-01-28 13:26
maybe just force a blockupdate when it recieves it's desc packet clientside?

**Comment by AlexIIL** [comment] 2016-01-28 13:35
That's not the issue @AEnterprise , the issue is that the client doesn't recieve a desc packet from the server- it doesn;t know that it needed to send a packet at all, so the client does its best with an invalid pipe and doesn;t render it.

**Comment by AEnterprise** [comment] 2016-01-28 14:46
@AlexIIL that's very odd, when a TE is loaded on the client side the server sends a desc packet to the client, if it's not doing that then you're eighter blocking that (by accident) in the code or there's a forge bug

**Comment by AlexIIL** [comment] 2016-01-28 14:48
I'm *was* blocking that on purpose and just sending out a BC packet instead of a normal MC packet, however in my dev environment I'm testing sending an MC packet and it seems to be working.

**Comment by asiekierka** [comment] 2016-03-24 23:20
What's the current status of this, @AlexIIL ?

**Comment by AEnterprise** [comment] 2016-06-25 09:48
has this been fixed? the commit and lackof other reports sugests so

**Comment by AlexIIL** [comment] 2016-06-25 14:39
Yeah I haven't encountered this. But it could be a duplicate of #3238.

**Closed by AlexIIL** 2016-06-25 14:39 UTC
Labels: needs investigation
