### ISSUE TITLE
Pipes cannot transfer energy and doesn't accept RF

### ISSUE THREAD

**Issue by Zer0Lyfe** [BuildCraft/BuildCraft#3863] opened 2017-11-24 06:52 UTC
**Buildcraft** version: 
**Forge** version: 1.12 14.23.0.2552
Link to crash report or log (on pastebin or gist, please don't put the entire log here) : none
Singleplayer/multiplayer:  Pipes cannot transfer energy with either RF or MJs as they don't even connect to the engines from BC or RF/FE machines

Additional information:
![2017-11-24_11 59 57](https://user-images.githubusercontent.com/28994351/33198582-f157196c-d126-11e7-9ab6-287ecbf73ee1.png)
![2017-11-24_12 00 08](https://user-images.githubusercontent.com/28994351/33198583-f18a6704-d126-11e7-8b2c-837b38a9d0bb.png)

**Comment by LuigiHutch** [comment] 2017-11-24 06:55
Thanks for the report! This is a duplicate of #3760

**Comment by LuigiHutch** [comment] 2017-11-24 06:56
Also engines only connect to power input pipes such as a Wooden kinesis pipe

**Comment by Zer0Lyfe** [comment] 2017-11-24 06:56
ah thank you Luigi.

**Closed** 2017-11-24 06:57 UTC
