### ISSUE TITLE
Buildcraft Silicon Crash

### ISSUE THREAD

**Issue by SirTwsted** [BuildCraft/BuildCraft#3883] opened 2017-11-30 11:19 UTC
****Buildcraft** version:** v7.99.12
****Forge** version:** v14.23.1.2555
**Mineraft Version:** v1.12.2

**Link to crashreport or log (on pastebin or gist, please don't put the entire log here) :** 
https://pastebin.com/CDBZRGeW

**Singleplayer/multiplayer:**  Single Player

**Additional information:** 
I tried both just Buildcraft JAR.
and also tried just the individual modules pack. Both ways crashes the game on start.

Cant install the Factory module, because it is out of date and no v1.12.2 is available for the Factory module.

**Comment by AEnterprise** [comment] 2017-11-30 11:34
crash is a duplicate of #3873
the factory module being missing on CF is my bad, seems for some reason those files got rejected and in the (spam) of all the rest being aproved i missed it, gona re-upload those and see

**Closed by AEnterprise** 2017-11-30 11:34 UTC

**Comment by SirTwsted** [comment] 2017-12-01 01:28
Thank you :)
