### ISSUE TITLE
Log spam, over a million lines of log spam.

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BuildCraft/BuildCraft#3107] opened 2015-11-01 14:02 UTC
I have open blocks tanks disabled, and have never had any in the world, and for some reason it seems that every buildcraft pipe in my world, of which I have lots, are iterating through and throwing an error about something that doesn't exist

`[00:51:41] [Server thread/DEBUG] [OpenMods/]: openmods.liquids.GenericTank.fillFromSides(GenericTank.java:154): Tank class buildcraft.transport.TileGenericPipe @ (-328,57,-123) returned null tank info. Nasty.`

the log files which I delete daily, are currently sitting at 6Gb from this error alone. 

Also my log is constantly spammed with things that look like errors about robots

`[20:06:42] [Server thread/INFO] [BuildCraft/]: Shutting down robot EntityRobot['Robot'/213, l='world', x=-283.47, y=54.26, z=-213.51] - no docking station
[20:06:42] [Server thread/WARN] [BuildCraft/]: Robot with id %d was not unregistered properly
[20:06:42] [Server thread/WARN] [BuildCraft/]: A robot entity was not properly unloaded
[20:06:42] [Server thread/WARN] [BuildCraft/]: Robot with id %d was not unregistered properly
[20:06:42] [Server thread/WARN] [BuildCraft/]: A robot entity was not properly unloaded
[20:06:42] [Server thread/WARN] [BuildCraft/]: Robot with id %d was not unregistered properly
[20:06:42] [Server thread/WARN] [BuildCraft/]: A robot entity was not properly unloaded
[20:06:42] [Server thread/WARN] [BuildCraft/]: Robot with id %d was not unregistered properly
[20:06:42] [Server thread/WARN] [BuildCraft/]: A robot entity was not properly unloaded
[20:06:42] [Server thread/WARN] [BuildCraft/]: Robot with id %d was not unregistered properly
[20:06:42] [Server thread/WARN] [BuildCraft/]: A robot entity was not properly unloaded
[20:06:42] [Server thread/WARN] [BuildCraft/]: Robot with id %d was not unregistered properly
[20:06:42] [Server thread/WARN] [BuildCraft/]: A robot entity was not properly unloaded
[20:06:42] [Server thread/WARN] [BuildCraft/]: Robot with id %d was not unregistered properly
[20:06:42] [Server thread/WARN] [BuildCraft/]: A robot entity was not properly unloaded`

**Comment by SandGrainOne** [comment] 2015-11-01 17:02
It is actually open blocks that are writing out that debug information about "null tank info". It is also apparently up for debate whether BuildCraft is in the wrong. See https://github.com/MinecraftForge/MinecraftForge/issues/2085

The robot spam is probably an issue with the link between the robot and its docking station. Try to make sure the chunks with the docking station and robot is loaded. 

I'm going to mark this as duplicate of #3054

**Closed by SandGrainOne** 2015-11-01 17:02 UTC
Labels: duplicate

**Comment by dj3520** [comment] 2015-11-01 17:36
"Robot with id %d" might want a small fixing. looks like that variable name
isn't being expanded
