### ISSUE TITLE
i cant craft Quarry

### ISSUE THREAD

**Issue by kaktusy123** [BuildCraft/BuildCraft#3543] opened 2017-05-02 12:37 UTC
in creative mode i can take quarry from JEI or equipment, but i cant craft it and JEI doesnt show recipe for quarry. 
Minecraft 1.11.2
BuildCraft 7.99.1
PS. Sorry for my english, im polish.

**Comment by afdw** [comment] 2017-05-02 12:41
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3537 (duplicate of https://github.com/BuildCraft/BuildCraft/issues/3527).

**Closed by afdw** 2017-05-02 12:41 UTC
