### ISSUE TITLE
Combustion Engine does not pump fuel out of distiller

### ISSUE THREAD

**Issue by ddowdy21** [BuildCraft/BuildCraft#3982] opened 2018-01-19 19:38 UTC
**BuildCraft** version: BuildCraft 7.99.14 for Minecraft 1.12.2
**Forge** version: 1.12.2-14.23.1.2590
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Additional information: I want to use the combustion engine to pump the fuel that is distilled in the distiller into a tank. The combustion engine will not pump out of the wooden fluid pipe connected to the distiller. I believe this is a Bug. I appreciate the hard work, Buildcraft is by far my favorite Minecraft mod.

**Comment by LuigiHutch** [comment] 2018-01-19 19:44
Have you got some screenshote of your setup? can you show them? Thanks!

**Comment by ddowdy21** [comment] 2018-01-19 19:52
Ill take some @LuigiHutch but another bug I'm dealing with is that my pipes are invisible

**Comment by LuigiHutch** [comment] 2018-01-19 19:55
I believe that is the same as https://github.com/BuildCraft/BuildCraft/issues/3960 Read the comments on that issue which may help resolve that issue

**Comment by ddowdy21** [comment] 2018-01-19 20:03
@LuigiHutch I really appreciate your response, I turned off the swappable sprites option and that took care of that issue. Hang tight for the pic of my setup.

**Comment by ddowdy21** [comment] 2018-01-19 20:15
![2018-01-19_15 12 43](https://user-images.githubusercontent.com/12734458/35169668-64031936-fd2b-11e7-8081-865aab1e1546.png)

Please Ignore the sloppiness, I changed my setup to accommodate for the alleged bug. The combustion engine I have hooked up to pump out of the distillery is rising in heat, which I believe means it should be working but you can see the system is haulted because it is not pumping out the fuel. I have been using buckets to transfer the fuel from the distillery to my tanks. @LuigiHutch

**Comment by ddowdy21** [comment] 2018-01-19 20:17
I also noticed that fuel fills from the top down in the tanks instead of rising from the bottom.

**Comment by LuigiHutch** [comment] 2018-01-19 20:18
BC oil processing has been completely redone. Here is a basic guide about how the new blocks work: http://imgur.com/a/AXUOX

For your setup in short, you need to extract the fluids out the top and bottom :)

Duplicate of #3737

**Comment by ddowdy21** [comment] 2018-01-19 20:44
@LuigiHutch Ahhh, somewhat confusing for me haha, but I figured I was doing something wrong. Thanks for the help, I'll get the hang of it.

**Comment by LuigiHutch** [comment] 2018-01-19 20:47
If you have anymore questions about the processing or something else, I recommend just popping in and asking in our discord as it makes it easier and quicker to help: https://discord.gg/v4geqgA

**Closed** 2018-01-20 13:21 UTC
