### ISSUE TITLE
No quarry recipe

### ISSUE THREAD

**Issue by XakepSDK** [BuildCraft/BuildCraft#3537] opened 2017-05-01 17:09 UTC
I build this:
https://github.com/BuildCraft/BuildCraft/commit/ee3e15bfcb06ed44d9a55293ed18de03c45b7fc1
Quarry recipe is missing.

**Comment by AEnterprise** [comment] 2017-05-01 17:13
the quarry and alot of other blocks still need recipes, we are currently in alpha state working out bugs and features

closing as pretty much duplicate of #3527

**Closed by AEnterprise** 2017-05-01 17:13 UTC
