### ISSUE TITLE
[1.11.2] Auto Workbench doesn't craft Lapislazuli-blocks

### ISSUE THREAD

**Issue by Holzstock** [BuildCraft/BuildCraft#3697] opened 2017-07-01 16:14 UTC
The Auto Workbench doesn't Lapislazuli-blocks, others like Coal-blocks or Redstone-blocks work.

![2017-07-01_18 12 19](https://user-images.githubusercontent.com/29532918/27763703-05653922-5e89-11e7-8d96-12d77c7f2fd0.png)

**Comment by AEnterprise** [comment] 2017-07-01 16:46
works just fine for me, most another mod has removed the recipe (crafttweaker/modtweaker/...) also what BC version?
![2017-07-01_18 42 21](https://user-images.githubusercontent.com/5206666/27763925-6a733d10-5e8d-11e7-99da-be622236811b.png)

**Comment by Holzstock** [comment] 2017-07-03 09:02
BC Version is 7.99.4, have removed _all_ mods from the mods Folder, still doesn't work.

![2017-07-03_10 59 29](https://user-images.githubusercontent.com/29532918/27785812-078e2716-5fdf-11e7-8546-e9d79fab2952.png)

**Comment by AEnterprise** [comment] 2017-07-03 09:36
we are still unable to reproduce this ourselfs with 7.99.4. could you reproduce this once more and provide the logs from that sessions? maybe those hold a clue as to what's going on

**Comment by Holzstock** [comment] 2017-07-03 10:01
Not sure which log you mean...

[FML Client Log.zip](https://github.com/BuildCraft/BuildCraft/files/1119134/FML.Client.Log.zip)
maybe this is the correct one.

**Comment by AEnterprise** [comment] 2017-07-03 10:11
ok looking at the logs your forge version is pretty old, could you update to the recomended forge build for 1.11.2 (1.11.2 - 13.20.1.2386) ?

**Comment by Holzstock** [comment] 2017-07-03 10:18
done.
[Logs.zip](https://github.com/BuildCraft/BuildCraft/files/1119177/Logs.zip)

**Comment by AEnterprise** [comment] 2017-07-03 10:38
so updating forge didn't fix it?

**Comment by Holzstock** [comment] 2017-07-03 10:39
nope

**Comment by AEnterprise** [comment] 2017-07-03 10:43
yeah i realy have no idea atm then as to what is causing this

**Comment by Holzstock** [comment] 2017-07-03 10:45
I will reinstall Minecraft as soon as i have better Internet Connection. Maybe that could fix it.

**Comment by AlexIIL** [comment] 2017-07-03 14:11
I can reproduce this if I change something about the lapis lazuli item, such as rename it in an anvil. Can you turn on advanced tooltips (F3 + H) and hover over the lapis to see if it has something like "NBT: 2 tag(s)"

**Comment by Holzstock** [comment] 2017-07-04 06:38
![2017-07-04_08 38 04](https://user-images.githubusercontent.com/29532918/27818014-284bb0ee-6094-11e7-8003-0309f8e07b49.png)

**Comment by AEnterprise** [comment] 2017-07-04 07:11
if that's the exact stack you used to set the recipe and try to craft it should work (and it works in all our tests)

**Comment by AEnterprise** [comment] 2017-07-23 08:42
Closing as we are still unable to reproduce this, the only explanation at this point would be that another mod is messing with the recipe in some very weird way

**Closed by AEnterprise** 2017-07-23 08:42 UTC
Labels: status: needs verification, version: 1.11.2
