### ISSUE TITLE
Server Crashes when Rendering Facecades, not user error

### ISSUE THREAD

**Issue by DarkMatterXCIX** [BuildCraft/BuildCraft#3992] opened 2018-01-22 07:32 UTC
BuildCraft version: 7.99.14
Forge version: 1.12.2-14.23.1.2555
Link to crash report or log: ----
Singleplayer or multiplayer: Multiplayer
Additional information: don't tell me its my fault, everything is up to date, don't close the ticket I know enough about mods to know it is not user error. the crash report specifically states there is a issue with loading the Facecades everytime we go near them in a search bar or open there own menu in the creative selections. im just putting this here in hopes you can fix it, thank you, cause everytime your mod comes off it starts to work - Dark
[crash-2018-01-22_00.56.35-client.txt](https://github.com/BuildCraft/BuildCraft/files/1651071/crash-2018-01-22_00.56.35-client.txt)

**Comment by AEnterprise** [comment] 2018-01-22 07:36
i closed the issue because it was missing all the required info, if you had replied with the info i would re-opened

from your crashreport:
```
Updating screen events

java.lang.IllegalStateException: Writing facade block state
	State = StateInfo [id=1785980916, block = Block{null}, state =  null]
	Block = Block{null}
	Block Class = class com.swdteam.xplosive.common.block.BlockArrowBomb
```

we tracked this down yesterday as being mods that add blocks being on the client but not the server, duplicate of #3990 
please check that the xplosive mod that you have on your client is installed on the server as well (and other mods as well, there might be more)

**Closed by AEnterprise** 2018-01-22 07:36 UTC
