### ISSUE TITLE
Quarry drops the clear block

### ISSUE THREAD

**Issue by BlaCoiso** [BuildCraft/BuildCraft#3037] opened 2015-09-24 15:36 UTC
Quarry drops the clear block(the red thing that destroys the block) if drop blocks is set to true and the block is broken manually before the quarry. 
![2015-09-24_16 32 06](https://cloud.githubusercontent.com/assets/13855359/10077921/66fb8094-62da-11e5-846f-a7a60c6cd352.png)
![2015-09-24_16 32 09](https://cloud.githubusercontent.com/assets/13855359/10077920/66f8aefa-62da-11e5-9ef0-183346713f5d.png)

**Comment by BlaCoiso** [comment] 2015-09-24 15:38
Seems that block can be placed, and it drops when broken.
![2015-09-24_16 37 57](https://cloud.githubusercontent.com/assets/13855359/10077970/a25b6e92-62da-11e5-85b2-2be31b11a81f.png)

**Comment by SandGrainOne** [comment] 2015-09-24 15:51
Duplicate of #3026

**Closed** 2015-09-24 15:53 UTC
Labels: duplicate
