### ISSUE TITLE
Quarry doesn't function - Buildcraft 7.99.4

### ISSUE THREAD

**Issue by kaosjr** [BuildCraft/BuildCraft#3708] opened 2017-07-07 04:48 UTC
I'm playing with Buildcraft 7.99.4 on a new 1.11.2 pack, and I've tried using the quarry with little success.
For whatever reason, it seems that the quarry will not accept power in any way.
Due to this, I'm unable to use the quarry.
![2017-07-06_21 45 11](https://user-images.githubusercontent.com/16449077/27943503-99ad0830-6294-11e7-8809-50734412940c.png)
![2017-07-06_21 45 16](https://user-images.githubusercontent.com/16449077/27943504-99ae20da-6294-11e7-82f7-798b64afb8a8.png)
![2017-07-06_21 45 28](https://user-images.githubusercontent.com/16449077/27943506-99b15098-6294-11e7-8758-6f4118463ba3.png)
![2017-07-06_21 45 34](https://user-images.githubusercontent.com/16449077/27943505-99b0a1ca-6294-11e7-9653-a1256f22f6f3.png)
I'm unfortunately not going to be able to use the quarry due to this, but I figured that I might as well file a bug report since I didn't see any with the same issue posted already.
Thanks!

**Comment by AEnterprise** [comment] 2017-07-07 07:50
This is working as intended at this point, buildcraft uses it's own powersystem again (MJ) and there is no conversion with other energysystems

you will need to use engines to generate MJ for the quarry, you can use kinetic pipes to transport the MJ from the engine to the quarry (recipes for those will be in 7.99.6 that should be out later today)

**Closed by AEnterprise** 2017-07-07 07:50 UTC
