### ISSUE TITLE
IllegalArgumentException crash with Literal Ascension 1.11.2-1.0.1.1 calling BlockDelegate.getPickBlock

### ISSUE THREAD

**Issue by leagris** [BuildCraft/BuildCraft#3544] opened 2017-05-02 15:25 UTC
### Versions

Minecraft Forge 13.20.0.2282
Literal Ascension 1.11.2-1.0.1.1
Buildcraft 7.99.1

### Crash Report:

[crash-2017-05-02_10.42.56-server.txt](https://gist.github.com/leagris/6f9733c19c339457472e2a76b661293b)

### Related Literal Ascension Issue:
[IllegalArgumentException crash with buildcraft 7.99.1 calling BlockDelegate.getPickBlock](https://bitbucket.org/jamieswhiteshirt/literal-ascension/issues/31/)

**Comment by afdw** [comment] 2017-05-02 15:27
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3536, already fixed.

**Closed by afdw** 2017-05-02 15:27 UTC

**Comment by AEnterprise** [comment] 2017-05-02 15:29
@AlexIIL you might want to considder a hotfix release as i have a feeling we're only gona keep getting duplicate reports until the fix is released

**Comment by afdw** [comment] 2017-05-02 15:31
But I'm not sure that current fix (https://github.com/BuildCraft/BuildCraft/commit/44a39885b3001162e518ce9fc4e5831a397fe27f) is better than my fix (https://github.com/BuildCraft/BuildCraft/commit/7855814ebfee3a21e299ec91c4937391bae53a25) because it probably can cause other Exceptions and other problems.

**Comment by AEnterprise** [comment] 2017-05-02 15:36
both fixes still have the potential to crash in different ways, the only way to make crashes impossible would be to wrap the thing in a try catch that catches absolutely everything

i do think that the current fix might be a bit better for performance as it doesn't involve constantly creating player objects that need to be cleaned up by the GC

**Comment by leagris** [comment] 2017-05-02 15:37
My apologies for this duplicate of https://github.com/BuildCraft/BuildCraft/issues/3536
I searched issues titles only, but:
"Crash on dedicated server" lacks of explicity :)
