### ISSUE TITLE
1.11.2-7.99.3 creative mode crash when hitting search icon

### ISSUE THREAD

**Issue by kreezxil** [BuildCraft/BuildCraft#3583] opened 2017-05-14 23:15 UTC
client crash report
https://pastebin.com/52gQmRN5

Steps:
1. go creative
1. hit 'e'
1. click on compass to search
1. enjoy the crash

**Comment by AlexIIL** [comment] 2017-05-14 23:53
Can you try removing extra utils 2? If that fixes it then this is a duplicate of #3582

**Comment by AEnterprise** [comment] 2017-06-11 18:42
closing due to lack of response and most likely a duplicate

**Closed by AEnterprise** 2017-06-11 18:42 UTC
