### ISSUE TITLE
[Error]MC 1.11.2 BC 7.99.4 No electric pipes

### ISSUE THREAD

**Issue by Rambo99** [BuildCraft/BuildCraft#3692] opened 2017-06-28 09:49 UTC
In the release there are no blocks associated with the transfer of energy (electricity) from the engines to the consumers (mine, quarry and so on). In previous versions, _**electric pipes**_ were used for this, they are absent in this release and it is also impossible to create (crafting) them. They simply do not exist.

**Comment by AEnterprise** [comment] 2017-06-28 09:51
first of all: there where never any "electric pipes", they are kinetic pipes, they transfer a different kind of power then electricity

also the kinetic pipes are not implemented yes, duplicate of #3523

**Closed by AEnterprise** 2017-06-28 09:51 UTC

**Comment by Rambo99** [comment] 2017-06-28 09:58
Instead of just closing posts with errors, is not it easier to fix YOUR mistake? Is it so difficult to add 8 standard recipes that existed in previous versions?! Or maybe YOU just LAZE?!

**Comment by asiekierka** [comment] 2017-06-28 10:07
https://github.com/BuildCraft/BuildCraft/issues/3523#issuecomment-311616041
