### ISSUE TITLE
item list

### ISSUE THREAD

**Issue by quentffr21** [BuildCraft/BuildCraft#2411] opened 2015-01-23 18:27 UTC
hello

buildcraft 6.3.3 also with 6.3.1 and 6.3.2
forge 10.13.2.1232

when you use the "accept Equivalents" button, after little time (2,3 second) the list not save his status (button return to not enable) i trying with a copper ore. 
no problem with the "accept variation".
i tested this in SP and SMP 

another thing (not certain is a bug)
when you don't use any button of list (variation or equivalent) and use the full line with some item only the first item was correctly routed.

thanks in advance

**Comment by hea3ven** [comment] 2015-02-02 23:22
fixed first issue, the second issue is a duplicate of #2422.

**Closed** 2015-02-02 23:23 UTC

**Comment by quentffr21** [comment] 2015-02-03 06:54
thanks
