### ISSUE TITLE
crash when generating terrain

### ISSUE THREAD

**Issue by cdfa** [BuildCraft/BuildCraft#3640] opened 2017-06-02 08:23 UTC
Hi, i get these crashes sometimes when generating new terrain. Seems like it happens when generating ocean monuments

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.1.jar)
  LoadingPlugin (Quark-r1.2-92.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta4-anarchy.jar)
  DummyPlugin (ForgeEndertech-1.11.2-2.1.2.0-build.0065.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
  RebornCoreASM (RebornCore-1.11.2-2.16.0.112-universal.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.89.jar)
  llibrary (llibrary-1.7.6-1.11.2.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.5.jar)
  IvToolkit (IvToolkit-1.3.3.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.371.jar)
  literalascension (literalascension-1.11.2-1.0.2.2.jar)
  PotionCoreFMLLoadingPlugin (PotionCore-1.5.2_for_1.11.2.jar)
  AstralCore (astralsorcery-1.4.1.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 6/2/17 10:17 AM
Description: Exception preparing structure feature

java.lang.IllegalArgumentException: Couldn't find a biome with an ID of 166527
	at buildcraft.energy.generation.GenLayerAddOilOcean.canReplaceBiome(GenLayerAddOilOcean.java:34)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:66)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:60)
	at net.minecraft.world.biome.BiomeProvider.func_76940_a(BiomeProvider.java:147)
	at net.minecraft.world.gen.structure.StructureOceanMonument.func_75047_a(SourceFile:86)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at net.minecraft.world.gen.ChunkProviderOverworld.func_180514_a(ChunkProviderOverworld.java:560)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:903)
	at net.minecraft.village.Village.func_179860_f(Village.java:382)
	at net.minecraft.village.Village.func_75557_k(Village.java:365)
	at net.minecraft.village.Village.func_75560_a(Village.java:61)
	at net.minecraft.village.VillageCollection.func_75544_a(SourceFile:62)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at buildcraft.energy.generation.GenLayerAddOilOcean.canReplaceBiome(GenLayerAddOilOcean.java:34)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:66)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:60)
	at net.minecraft.world.biome.BiomeProvider.func_76940_a(BiomeProvider.java:147)
	at net.minecraft.world.gen.structure.StructureOceanMonument.func_75047_a(SourceFile:86)

-- Feature being prepared --
Details:
	Is feature chunk: ~~ERROR~~ IllegalArgumentException: Couldn't find a biome with an ID of 292254
	Chunk location: 177,389
	Chunk pos hash: 1670742278321
	Structure type: net.minecraft.world.gen.structure.StructureOceanMonument
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at net.minecraft.world.gen.ChunkProviderOverworld.func_180514_a(ChunkProviderOverworld.java:560)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:903)
	at net.minecraft.village.Village.func_179860_f(Village.java:382)
	at net.minecraft.village.Village.func_75557_k(Village.java:365)
	at net.minecraft.village.Village.func_75560_a(Village.java:61)
	at net.minecraft.village.VillageCollection.func_75544_a(SourceFile:62)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: test
	All players: 1 total; [EntityPlayerMP['theMCpenguin'/251, l='test', x=2852.69, y=240.85, z=5912.16]]
	Chunk stats: ServerChunkCache: 1347 Drop: 0
	Level seed: 80557833873531404
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":300.0,"heightScale":300.0,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":50.0,"depthNoiseScaleZ":50.0,"depthNoiseScaleExponent":0.24,"mainNoiseScaleX":120.0,"mainNoiseScaleY":240.0,"mainNoiseScaleZ":120.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":5.0,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":15,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useMansions":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":15,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":4,"riverSize":5,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":256,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":256,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":256,"coalSize":17,"coalCount":25,"coalMinHeight":0,"coalMaxHeight":256,"ironSize":9,"ironCount":30,"ironMinHeight":0,"ironMaxHeight":128,"goldSize":9,"goldCount":4,"goldMinHeight":0,"goldMaxHeight":96,"redstoneSize":8,"redstoneCount":10,"redstoneMinHeight":0,"redstoneMaxHeight":48,"diamondSize":8,"diamondCount":1,"diamondMinHeight":0,"diamondMaxHeight":24,"lapisSize":9,"lapisCount":10,"lapisCenterHeight":96,"lapisSpread":64}
	Level spawn location: World: (-17,64,76), Chunk: (at 15,4,12 in -2,4; contains blocks -32,0,64 to -17,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 223477 game time, 11049 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 63066 (now: false), thunder time: 156705 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1363676544 bytes (1300 MB) / 3404570624 bytes (3246 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 14, tcache: 154, allocated: 0, tallocated: 2
	FML: MCP 9.38 Powered by Forge 13.20.0.2299 Optifine OptiFine_1.11.2_HD_U_B9 124 mods loaded, 124 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2299.jar) 
	UCHIJAAAA	forge{13.20.0.2299} [Minecraft Forge] (forge-1.11.2-13.20.0.2299.jar) 
	UCHIJAAAA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	potioncore_coremod{1.5.2_for_1.11.2} [Potion Core Coremod] (minecraft.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	uncraftingtable{1.7.2} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.2.jar) 
	UCHIJAAAA	achunkloader{1.11-1.2.0} [A Chunk Loader] (achunkloader-1.11.2-1.2.0.jar) 
	UCHIJAAAA	thinkbigcore{1.6.1} [§5§m===§r §e§lThink Big Core §5§m===§r] (Think Big Core V1.6.1 - 1.11.2.jar) 
	UCHIJAAAA	adinferos{1.2.6} [§e§k!!§6§k]]§c§kkk§4§lAd Inferos§c§kkk§6§k]]§e§k!!] (Ad Inferos V1.2.6 - 1.11.2.jar) 
	UCHIJAAAA	forgeendertech{1.11.2-2.1.2.0} [Forge Endertech] (ForgeEndertech-1.11.2-2.1.2.0-build.0065.jar) 
	UCHIJAAAA	adchimneys{1.11.2-2.0.10.0} [Advanced Chimneys] (AdChimneys-1.11.2-2.0.10.0-build.0051.jar) 
	UCHIJAAAA	animania{1.1.2} [Animania] (animania-1.11.2-1.1.2.jar) 
	UCHIJAAAA	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCHIJAAAA	jei{4.3.6.282} [Just Enough Items] (jei_1.11.2-4.3.6.282.jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	armoroverlay{3.3a} [Armor Overlay] (armoroverlay-3.3a.jar) 
	UCHIJAAAA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJAAAA	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.jar) 
	UCHIJAAAA	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.jar) 
	UCHIJAAAA	astralsorcery{1.4.1} [Astral Sorcery] (astralsorcery-1.4.1.jar) 
	UCHIJAAAA	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCHIJAAAA	quark{r1.2-92} [Quark] (Quark-r1.2-92.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	autosapling{1.11.2-1.3.5} [AutoSapling] (AutoSapling 1.11.2-1.3.5.jar) 
	UCHIJAAAA	betterachievements{0.4.3.12} [Better Achievements] (BetterAchievements-1.11.2-0.4.3.12.jar) 
	UCHIJAAAA	bettertitlescreen{1.3a} [Better Title Screen] (BetterTitleScreen-1.11.2-1.3a.jar) 
	UCHIJAAAA	blockdrops{1.2.2} [Block Drops] (blockdrops-1.11.2-1.2.2.jar) 
	UCHIJAAAA	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide-API-1.11.2-2.1.1-52.jar) 
	UCHIJAAAA	bloodmagic{1.11-2.1.10-79} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.10-79.jar) 
	UCHIJAAAA	bookshelf{1.5.0.371} [Bookshelf] (Bookshelf-1.11.2-1.5.0.371.jar) 
	UCHIJAAAA	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	UCHIJAAAA	bullseye{2.0.0} [Bullseye] (Bullseye-1.11.2-2.0.0.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAAAA	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJAAAA	chesttransporter{2.7.9} [Chest Transporter] (ChestTransporter-1.11.2-2.7.9.jar) 
	UCHIJAAAA	chisel{MC1.11.2-0.0.10.14} [Chisel] (Chisel-MC1.11.2-0.0.10.14.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	controlling{2.0.4} [Controlling] (Controlling-2.0.4.jar) 
	UCHIJAAAA	coralreef{1.0} [Coral Reef] (CoralReef-1.4.jar) 
	UCHIJAAAA	cyberware{alpha-0.2.9} [Cyberware] (cyberware-1.11.2-alpha-0.2.9.jar) 
	UCHIJAAAA	cyclopscore{0.10.4} [Cyclops Core] (CyclopsCore-1.11.2-0.10.4.jar) 
	UCHIJAAAA	darkutils{1.2.0.126} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.126.jar) 
	UCHIJAAAA	dsurround{3.4.5.1} [§3Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.5.1.jar) 
	UCHIJAAAA	presets{3.4.5.1} [§3Presets!] (DynamicSurroundings-1.11.2-3.4.5.1.jar) 
	UCHIJAAAA	embers{0.214} [Embers] (embers-0.214.jar) 
	UCHIJAAAA	csb_ench_table{1.1} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.11-1.1.jar) 
	UCHIJAAAA	shetiphiancore{3.4.5} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.5.jar) 
	UCHIJAAAA	endertanks{1.5.5} [EnderTanks] (endertanks-1.11.0-1.5.5.jar) 
	UCHIJAAAA	enderthing{0.7.3} [Enderthing] (enderthing-1.11.0-0.7.3.jar) 
	UCHIJAAAA	enderzoo{1.11.2-1.3.0.47} [Ender Zoo] (EnderZoo-1.11.2-1.3.0.47.jar) 
	UCHIJAAAA	evilcraft{0.10.26} [EvilCraft] (EvilCraft-1.11.2-0.10.26.jar) 
	UCHIJAAAA	extrabitmanipulation{1.11.2-3.0.6} [Extra Bit Manipulation] (ExtraBitManipulation-1.11.2-3.0.6.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	flourpower{1.11-0.0.3-2} [Flour Power] (FlourPower-1.11-0.0.3-2.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta4-anarchy.jar) 
	UCHIJAAAA	foragecraft{1.11} [ForageCraft] (ForageCraft-1.11.jar) 
	UCHIJAAAA	forestry{5.3.4.99} [Forestry] (forestry_1.11.2-5.3.4.99.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Forgelin] (Forgelin-1.4.2.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UCHIJAAAA	giacomos_bookshelf{1.1} [Giacomo's Bookshelves Mod] (GiacomosBookshelf-1.11.2-1.1.jar) 
	UCHIJAAAA	fishing{1.5.1} [Fishing Net Mod] (GiacomosFishingNet-1.11.2-1.5.1.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.89.be6ffe4} [Inventory Tweaks] (InventoryTweaks-1.62+beta.89.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.19.803} [Iron Chest] (ironchest-1.11.2-7.0.19.803.jar) 
	UCHIJAAAA	jaff{1.6_for_1.11.2} [Just a Few Fish] (JustAFewFish-1.6_for_1.11.2.jar) 
	UCHIJAAAA	jeresources{0.6.4.6} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.4.6.jar) 
	UCHIJAAAA	kleeslabs{4.3.5} [KleeSlabs] (KleeSlabs_1.11.2-4.3.5.jar) 
	UCHIJAAAA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UCHIJAAAA	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (literalascension-1.11.2-1.0.2.2.jar) 
	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJAAAA	login_shield{1.11.2-1-g7435bb5} [Login Shield] (Login_Shield-1.11.2-1-g7435bb5.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.2-1.13.jar) 
	UCHIJAAAA	shear{1.1.2} [More Shearables] (MoreShearables1.2.2-1.11.2.jar) 
	UCHIJAAAA	morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus-1.11.2-3.2.14.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJAAAA	multibeds{1.3.3} [Multi-Beds] (multibeds-1.11.0-1.3.3.jar) 
	UCHIJAAAA	natura{1.11.2-4.2.0.20} [Natura] (natura-1.11.2-4.2.0.20.jar) 
	UCHIJAAAA	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.11.2-1.3.0.jar) 
	UCHIJAAAA	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCHIJAAAA	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCHIJAAAA	potioncore{1.5.2_for_1.11.2} [Potion Core] (PotionCore-1.5.2_for_1.11.2.jar) 
	UCHIJAAAA	qualitytools{1.0.4_for_1.11.2} [Quality Tools] (QualityTools-1.0.4_for_1.11.2.jar) 
	UCHIJAAAA	reborncore{2.16.0.112} [Reborn Core] (RebornCore-1.11.2-2.16.0.112-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.16.0.112} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.16.0.112-universal.jar) 
	UCHIJAAAA	reccomplex{1.3.2} [Recurrent Complex] (RecurrentComplex-1.3.2.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	roots{0.018} [Roots 2] (roots-2-0.018.jar) 
	UCHIJAAAA	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.11.2-2.0.5.jar) 
	UCHIJAAAA	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCHIJAAAA	simulatednights{1.11.2-1.2.0} [Simulated Nights] (simulatednights-1.11.2-1.2.0.jar) 
	UCHIJAAAA	sophisticatedwolves{3.6.5} [Sophisticated Wolves] (SophisticatedWolves-3.6.5.jar) 
	UCHIJAAAA	soundphysics{1.0.0} [Sound Physics] (soundphysics-mc1.11-v1.0.0.jar) 
	UCHIJAAAA	spiceoflife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.11.2-1.3.8.jar) 
	UCHIJAAAA	stellarapi{0.6.4.1.3} [Stellar API] (Stellar API-0.6.4.1.3.jar) 
	UCHIJAAAA	stellarsky{0.6.5.1.4} [Stellar Sky] (Stellar Sky-0.6.5.1.4.jar) 
	UCHIJAAAA	stevescarts{2.3.0.22} [Steve's Carts 2] (StevesCarts-1.11.2-2.3.0.22.jar) 
	UCHIJAAAA	storageboats{2.0} [Storage Boats Mod] (StorageBoats-2.4.jar) 
	UCHIJAAAA	supercraftingframe{1.2.1.89} [Super Crafting Frame] (supercraftingframe-1.11-1.2.1.89.jar) 
	UCHIJAAAA	tesla{1.3.0.51} [TESLA] (Tesla-1.11-1.3.0.51.jar) 
	UCHIJAAAA	toroquest{1.11.2-3.5} [ToroQuest] (toroquest-1.11.2-3.5.jar) 
	UCHIJAAAA	translocator{2.2.0.59} [Translocator] (Translocators-1.11.2-2.2.0.59-universal.jar) 
	UCHIJAAAA	underphangables{1.0.4} [Underp Hangables] (underphangables-1.11.2-1.0.4.jar) 
	UCHIJAAAA	underwaterutilities{@VERSION@} [Underwater Utilities] (UnderwaterUtilities-1.11.2-1.2.3.jar) 
	UCHIJAAAA	vanillafoodpantry{3.1} [Vanilla Food Pantry] (vanillafoodpantry-mc1.11.2-3.1.jar) 
	UCHIJAAAA	waddles{0.5.2} [Waddles] (Waddles-1.11.2-0.5.2.jar) 
	UCHIJAAAA	wanionlib{1.11.2-1.0} [WanionLib] (WanionLib-1.11.2-1.0.jar) 
	UCHIJAAAA	wearablebackpacks{2.4.1} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.4.1.jar) 
	UCHIJAAAA	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
	UCHIJAAAA	unidict{1.11.2-1.0} [UniDict] (UniDict-1.11.2-1.0.jar) 
	UCHIJAAAA	yabba{1.11.2-0.5.1} [YABBA] (YABBA-1.11.2-0.5.1.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.1.jar)
  org.blockartistry.DynSurround.asm.Transformer
LoadingPlugin (Quark-r1.2-92.jar)
  vazkii.quark.base.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta4-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
DummyPlugin (ForgeEndertech-1.11.2-2.1.2.0-build.0065.jar)
  
ForgelinPlugin (Forgelin-1.4.2.jar)
  
RebornCoreASM (RebornCore-1.11.2-2.16.0.112-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.89.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  team.chisel.common.asm.ChiselTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.5.jar)
  shetiphian.core.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3.jar)
  
BookshelfLoadingPlugin (Bookshelf-1.11.2-1.5.0.371.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
literalascension (literalascension-1.11.2-1.0.2.2.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
PotionCoreFMLLoadingPlugin (PotionCore-1.5.2_for_1.11.2.jar)
  com.tmtravlr.potioncore.asm.ArmorHandlerTransformer
AstralCore (astralsorcery-1.4.1.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.16.0.112
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	translocator Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['theMCpenguin'/251, l='test', x=2852.69, y=240.85, z=5912.16]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B9
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.82
	OpenGlRenderer: GeForce GTX 950M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by AEnterprise** [comment] 2017-06-02 08:28
for next time please put your crashlog on pastebin or gist and put the link here instead of this wall of text, makes things easier for us

as for the crash we have seen this before and it seems during generation something somewhere is causing the biome events to fire with an invalid biome ID so BC crashes on that

@AlexIIL you are working on the biomegen rewrite, would you mind removing the throwing of the exception when we get an invalid biome? it seems to be something caused by vanilla or forge so it would probably be better to just ignore it instead of crashing

**Comment by Barteks2x** [comment] 2017-06-02 09:10
Based on my testing, it happens when client attempts to generate it's own biomes. I might create a forge PR to remove generating biomes clientside, which should fix it.

**Comment by cdfa** [comment] 2017-06-06 09:04
sorry, i'll put it behind a link next time, but thanks for the response

**Comment by 5kedone** [comment] 2017-06-07 12:42
so is this one being fixed your end or is it a forge issue now ~?

**Comment by AEnterprise** [comment] 2017-06-07 12:44
it still is an issue with how minecraft/forge and other mods sometimes generate terrain but BC should no longer be crashing due to it

**Comment by MokahTGS** [comment] 2017-06-09 21:01
I'm assuming this is the same crash:  https://pastebin.com/nvm5KFxV

**Comment by afdw** [comment] 2017-06-09 21:33
@MokahTGS yes.

**Comment by AlexIIL** [comment] 2017-07-06 21:16
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)

**Closed by AlexIIL** 2017-07-06 21:16 UTC
Labels: status: fixed/implemented in dev, type: bug, version: 1.11.2
