### ISSUE TITLE
BuildCraft 7.99.3 Still no kinesis Pipes 

### ISSUE THREAD

**Issue by HardCostKill3R** [BuildCraft/BuildCraft#3593] opened 2017-05-20 11:03 UTC
I've installed BuildCraft 7.99.3 for 1.11.2 and there are no Kinesis pipes and there are other missing items/ recipes.

**Comment by afdw** [comment] 2017-05-20 11:07
Yes, still no kinesis pipes. Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3516 and https://github.com/BuildCraft/BuildCraft/issues/3523.

**Closed by afdw** 2017-05-20 11:07 UTC
