### ISSUE TITLE
Exception when looking up usages for integrated gates in NEI

### ISSUE THREAD

**Issue by linuxdemon1** [BuildCraft/BuildCraft#3347] opened 2016-05-23 22:48 UTC
When looking up the uses of any of the integrated gate (eg: Emerald And gate with light sensor), it produces a ClassCastException, attempting to cast a null to ItemStack. I tested this both on FTB's Infinity Evolved Skyblock v1.1.0 and an instance with just NEI, CCC, buildcraft, and buildcraft-compat
Logs: [Crashreport](http://pastebin.com/TCd2df5Z), [Forge log](http://pastebin.com/5WXmVxR9)

Java version: 1.8.0_91 (OpenJDK)
OS: Linux
Minecraft version: 1.7.10
Forge build: 10.13.4.1614
BC version: 7.1.16
BC-compat version: 7.1.3
NEI version: 1.0.5.120
CCC verision: 1.0.7.47

**Comment by AlexIIL** [comment] 2016-05-23 23:56
Duplicate of https://github.com/BuildCraft/BuildcraftCompat/issues/58 (we deal with compat issues over there).

**Closed by AlexIIL** 2016-05-23 23:56 UTC

**Comment by cosmicdan** [comment] 2016-07-13 17:57
Sorry to bump, but this problem didn't occur on BC .16 (confirmed by rolling back just now) and BuildcraftCompat seems stalled in the 1.7.10 branch. I tried cloning the source and setting up a dev environment to try and solve it on BuildcraftCompat end but a bunch of maven repo's are down at the moment so I don't know what to do there.
