### ISSUE TITLE
Refinery not accepting Biomass

### ISSUE THREAD

**Issue by Megistus** [BuildCraft/BuildCraft#2787] opened 2015-06-11 13:04 UTC
With the update to 7.0.8, my refineries have stopped accepting biomass, and what they have in them are not being processed into ethanol. Further, by breaking a refinery and replacing it ... it will not accept biomass into its tanks.

I have just downloaded 7.0.9 but did not see any reference to this particular bug.

**Comment by AgentK9** [comment] 2015-06-11 13:19
any other mods?

**Comment by Megistus** [comment] 2015-06-11 13:49
Plenty...
Treecapacitator
Archimedes Ships
Bibliocraft
buildcraft
Cart Livery
Chocolate Quest
COFH
Craft Guid
Enchant View
EnderIO
Enhanced Portals
Extra Doors
Forestry (Recently Updated for the BC 7 update)
Ganys Surface
Gendustry
Map Writer
Mine Factory Reloaded
Nether Ores
Project Red
Railcraft
Rogue Like Dungeons
Thaumcraft
Thermal Expansion
Thermal Foundation
T Mechworks
Weapon Mod

... I had my system running quite happy processing ethanol until I upgraded to BC 7

**Comment by Thog** [comment] 2015-06-19 22:17
The problem is not related to BuildCraft but to Forestry : The BC internal plugin is not called

> [00:09:12] [Client thread/INFO] [Forestry]: Module BuildCraft 6 Recipes Plugin failed to load: Compatible BuildCraftAPI|recipes version not found

https://github.com/ForestryMC/ForestryMC/blob/master/src/main/java/forestry/plugins/PluginBuildCraftRecipes.java#L26

**Comment by AgentK9** [comment] 2015-06-20 13:03
BUILDCRAFT COMPAT!!!!

**Comment by Thog** [comment] 2015-06-20 13:04
@AgentK9 This pluign is located on Forestry NOT on BC

**Comment by AgentK9** [comment] 2015-06-20 13:06
I know, but you should ALWAYS have BCCompat if you have any other mods.

**Comment by Megistus** [comment] 2015-06-20 19:51
If you are implying that I don't have BC Compat ... that would be false ... while it is not listed, I considered it assumed as I play with other mods. 

Okay on the conclusions, hopefully Forestry will update soon. 

Thanks

**Comment by mezz** [comment] 2015-06-20 23:19
@asiekierka pinged me about this on IRC.

Should be fixed the latest unstable Forestry and the upcoming Stable 3.6.0.
https://github.com/ForestryMC/ForestryMC/commit/9d1d1b9ef1495fb0a759a30d31a862517ae128d6

**Closed** 2016-03-24 23:01 UTC
