### ISSUE TITLE
Electric Engine From Forestry can't connect to quarry

### ISSUE THREAD

**Issue by Sorinwaker** [BuildCraft/BuildCraft#3783] opened 2017-08-17 12:15 UTC
**Buildcraft** version: 7.99.7
**Forge** version: 1.11.2 13.20.1.2386
Just wondering if you guys were aware of this , thank you for your good work !
Electric Engine From Forestry can't connect to quarry
Singleplayer/multiplayer: Multiplayer

Additional information: Forestry version 5.3.4.119 will send a post to forestry dev too 

Thank you,

Sorinwaker

**Comment by LuigiHutch** [comment] 2017-08-17 12:22
Thanks for the report! This is a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3760

**Closed** 2017-08-17 12:25 UTC
