### ISSUE TITLE
Bug with world loading

### ISSUE THREAD

**Issue by Rockefeller157** [BuildCraft/BuildCraft#4416] opened 2019-06-02 16:39 UTC
Hello.
For my server, I tested a modpack with many mods, buildcraft included. When I tested it, minecraft ran correctly without a problem, but when I go on a singleplay world, or create a new one, the game crashes.
If you need the modpack, it's called "Dischronica" on technicpack.net
(of course, buildcraft is not on it since it doesn't work properly)

Thanks for your help and time.

BuildCraft version: 
buildcraft all 7.99.20 - buildcraft all 7.99.24.1

Forge version: 
1.12.2-14.23.4.2760

Link to crash report: 
https://pastebin.com/dPzR2F2y

Singleplayer or multiplayer: 
Singleplayer

Steps to reproduce: 
- Run Minecraft
- Create a new world or run an existing one

Edit:
Also crashes when only running Buildcraft Core without any module or addon.

**Comment by AlexIIL** [comment] 2019-06-02 17:21
Duplicate of #4175 - see https://github.com/micdoodle8/Galacticraft/issues/3393 for more details.

**Closed by AlexIIL** 2019-06-02 17:21 UTC
