### ISSUE TITLE
Quarry !! mc 1.11.2

### ISSUE THREAD

**Issue by Merctcanserim** [BuildCraft/BuildCraft#3563] opened 2017-05-10 16:06 UTC
quarry does not works and not craftable, it does not put frames .pls fix this. but i using gamemode 1 and i am manually putting "frames" and  works .But do not you have to put the frames on your own?

**Comment by LuigiHutch** [comment] 2017-05-10 16:18
Update to 7.99.3. Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3517

**Closed** 2017-05-10 17:39 UTC
