### ISSUE TITLE
Buildcraft 1.11.2 - Purple And Black tubes or blocks when previously replaced

### ISSUE THREAD

**Issue by TimeGumLord1** [BuildCraft/BuildCraft#3701] opened 2017-07-04 18:13 UTC
Hi there, so i recently i made my own server on a server hosting website and i bought it to allow me and my  friends to play with forge mods. One of them is Buildcraft 1.11.2 which yes i know is in alpha but however was wondering if anyone knows about this issue?

So i placed some blocks with tubes with buildcraft on my server and at FIRST it was fine and looked and acted normal but then after i backed up my server and added a few mods and rearanged buildcraft (taking it away from the mods folder on the server and placing it back in again) and then now this has happend.
![2017-07-04_19 09 42](https://user-images.githubusercontent.com/22731806/27839897-c64d6406-60ec-11e7-802f-39e59ced2f6b.png)

**Comment by LuigiHutch** [comment] 2017-07-04 18:16
Thanks for the report!
I believe this a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3685 . Please repost your finding and any logs you have over on that issue. Thanks!

**Comment by TimeGumLord1** [comment] 2017-07-04 18:17
Ok will do i just hope someone can help soon!

**Comment by AEnterprise** [comment] 2017-07-04 20:19
this is indeed a duplicate, can you post your server logs in the linked issue?

**Closed by AEnterprise** 2017-07-04 20:19 UTC

**Comment by TimeGumLord1** [comment] 2017-07-04 20:23
Sure here it is i think.
[2017-07-04-2.log.gz](https://github.com/BuildCraft/BuildCraft/files/1122999/2017-07-04-2.log.gz)

**Comment by AlexIIL** [comment] 2017-07-04 20:31
@TimeGumLord1 Do you have an fml-server-latest log? The log file has a log of "Skipping BlockEntity with id buildcrafttransport:pipe_holder", I'm wondering if the main forge log has more information

**Comment by TimeGumLord1** [comment] 2017-07-04 20:41
Hello i gtg to bed now and will check on what you guys have put but here it is i think
[fml-server-2.zip](https://github.com/BuildCraft/BuildCraft/files/1123026/fml-server-2.zip)

**Comment by TimeGumLord1** [comment] 2017-07-04 20:43
if that one has nothing in it try these? But sorry to be a pain but i fiddled around with the mods during these times so have a dig around and see what you guys can find. Sorry :)
[fml-server-1.zip](https://github.com/BuildCraft/BuildCraft/files/1123027/fml-server-1.zip)
[fml-server-3.zip](https://github.com/BuildCraft/BuildCraft/files/1123028/fml-server-3.zip)

**Comment by TimeGumLord1** [comment] 2017-07-04 20:44
or this 
[fml-server-latest.zip](https://github.com/BuildCraft/BuildCraft/files/1123029/fml-server-latest.zip)
[fml-junk-earlystartup.zip](https://github.com/BuildCraft/BuildCraft/files/1123032/fml-junk-earlystartup.zip)

**Comment by AlexIIL** [comment] 2017-07-04 20:50
@TimeGumLord1 Looks like github's not letting me download either from your [last comment](https://github.com/BuildCraft/BuildCraft/issues/3701#issuecomment-312950289) - can you re-upload them?

**Comment by AlexIIL** [comment] 2017-07-04 20:53
Oh hang on, if you loaded the world without buildcraft once then there's nothing we can do about this. (This also means its not a duplicate of #3685).

**Comment by TimeGumLord1** [comment] 2017-07-04 20:54
oh ok yeah i think thats what i did by accident, you see when i run the server without buildcraft that goes away but with buildcraft it stays, so do you just think its been corrupted and cant do anything then?

**Comment by TimeGumLord1** [comment] 2017-07-04 20:56
gtg now read posts in the morning

**Comment by AlexIIL** [comment] 2017-07-04 21:02
When you remove a mod it replaces the blocks missing (in this case pipes) with alternate air blocks, which retain the block type information (so they know that they were pipes). However the information about which pipe it was is lost (as BuildCraft stores that separately). You should be able to find a backup zip of your world from before your removed buildcraft. If you haven't done much in your world you could try booting up the server with that world, rather than loosing all of the pipes.

**Comment by TimeGumLord1** [comment] 2017-07-05 06:43
Yeah possible i will have a look through it and see what i can do. Thanks for your help though anyway! I would just end this fourm since it was a mistake and not an actual glitch or bug in your mod well in this case not entirely! :)
