### ISSUE TITLE
crash 7.99.4

### ISSUE THREAD

**Issue by Andvee** [BuildCraft/BuildCraft#3690] opened 2017-06-27 13:35 UTC
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-93.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  AstralCore (astralsorcery-1.4.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  TransformerLoader (OpenComputers-MC1.11.2-1.7.0.24.jar)
  BookshelfLoadingPlugin (Bookshelf-1.11.2-2.0.0.388.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 6/27/17 6:10 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.ClassCastException: com.google.common.collect.AbstractMapBasedMultimap$RandomAccessWrappedList cannot be cast to net.minecraft.util.NonNullList
	at buildcraft.lib.client.guide.parts.recipe.GuideCraftingFactory.oreConvert(GuideCraftingFactory.java:194)
	at buildcraft.lib.client.guide.parts.recipe.GuideCraftingFactory.getFactory(GuideCraftingFactory.java:97)
	at buildcraft.lib.client.guide.parts.recipe.GuideCraftingRecipes.getUsages(GuideCraftingRecipes.java:39)
	at buildcraft.lib.client.guide.parts.recipe.RecipeLookupHelper.getAllUsages(RecipeLookupHelper.java:30)
	at buildcraft.lib.client.guide.loader.MarkdownPageLoader.loadAllCrafting(MarkdownPageLoader.java:254)
	at buildcraft.lib.client.guide.loader.MarkdownPageLoader.loadAllCrafting(MarkdownPageLoader.java:239)
	at buildcraft.lib.client.guide.loader.MarkdownPageLoader$$Lambda$740/128713165.parse(Unknown Source)
	at buildcraft.lib.client.guide.loader.MarkdownPageLoader.loadSpecialLine(MarkdownPageLoader.java:192)
	at buildcraft.lib.client.guide.loader.MarkdownPageLoader.turnLineIntoPart(MarkdownPageLoader.java:90)
	at buildcraft.lib.client.guide.loader.MarkdownPageLoader.loadPage(MarkdownPageLoader.java:353)
	at buildcraft.lib.client.guide.loader.IPageLoaderText.loadPage(IPageLoaderText.java:19)
	at buildcraft.lib.client.guide.GuideManager.loadLangInternal(GuideManager.java:90)
	at buildcraft.lib.client.guide.GuideManager.reloadLang(GuideManager.java:73)
	at buildcraft.lib.client.guide.GuideManager.load(GuideManager.java:53)
	at buildcraft.lib.BCLibProxy$ClientProxy.fmlPostInit(BCLibProxy.java:134)
	at buildcraft.lib.BCLib.postInit(BCLib.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2052820776 bytes (1957 MB) / 3024093184 bytes (2884 MB) up to 7158628352 bytes (6827 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7680m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2366 Optifine OptiFine_1.11.2_HD_U_C1 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2366.jar) 
	UCHIJ	forge{13.20.0.2366} [Minecraft Forge] (forge-1.11.2-13.20.0.2366.jar) 
	UCHIJ	opencomputers|core{1.7.0.24} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJ	bettercombatmod{1.4.0} [Better Combat] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
	UCHIJ	examplemod{1.0} [examplemod] ([MC 1.11.X] BetterCombatMod 1.4.jar) 
	UCHIJ	astralsorcery{1.4.4} [Astral Sorcery] (astralsorcery-1.4.4.jar) 
	UCHIJ	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.1.7.jar) 
	UCHIJ	jei{4.5.0.290} [Just Enough Items] (jei_1.11.2-4.5.0.290.jar) 
	UCHIJ	immersiveengineering{0.11-62} [Immersive Engineering] (ImmersiveEngineering-0.11-62.jar) 
	UCHIJ	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJ	natura{1.11.2-4.2.0.22} [Natura] (natura-1.11.2-4.2.0.22.jar) 
	UCHIJ	betterwithmods{1.2.9-1.11.2} [Better With Mods] (Better With Mods-1.2.35-1.11.2.jar) 
	UCHIJ	quark{r1.2-93} [Quark] (Quark-r1.2-93.jar) 
	UCHIJ	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJ	betterfoliage{2.1.5} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.5.jar) 
	UCHIJ	bibliocraft{2.3.2} [BiblioCraft] (BiblioCraft[v2.3.2][MC1.11.2].jar) 
	UCHIJ	bookshelf{2.0.388} [Bookshelf] (Bookshelf-1.11.2-2.0.0.388.jar) 
	UCHIE	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	UCHIE	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	UCHIE	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	UCHIE	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	UCHIE	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	UCHIE	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	UCHIE	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	UCHIE	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	UCHIJ	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJ	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	UCHIJ	darkutils{1.2.0.147} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.147.jar) 
	UCHIJ	embers{0.216} [Embers] (embers-0.216.jar) 
	UCHIJ	geographicraft{0.8.7} [GeographiCraft] (GeographiCraft-0.8.7.jar) 
	UCHIJ	immersivepetroleum{1.0.7} [Immersive Petroleum] (immersivepetroleum-1.11.2-1.0.7.jar) 
	UCHIJ	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCHIJ	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCHIJ	mysticalagriculture{1.5.6} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.5.6.jar) 
	UCHIJ	opencomputers{1.7.0.24} [OpenComputers] (OpenComputers-MC1.11.2-1.7.0.24.jar) 
	UCHIJ	oretweaker{1.0.2-1.11.2} [Ore Tweaker] (OreTweaker-1.0.2-1.11.2.jar) 
	UCHIJ	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UCHIJ	roots{0.020} [Roots 2] (roots-2-0.020.jar) 
	UCHIJ	storagedrawers{1.11.2-4.2.9} [Storage Drawers] (StorageDrawers-1.11.2-4.2.9.jar) 
	UCHIJ	wawla{2.4.0.231} [What Are We Looking At] (Wawla-1.11.2-2.4.0.231.jar) 
	UCHIJ	waystones{3.0.16} [Waystones] (Waystones_1.11.2-3.0.16.jar) 
	UCHIJ	woot{1.11.2-0.2.0} [Woot] (woot-1.11.2-0.2.0.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-93.jar)
  vazkii.quark.base.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
AstralCore (astralsorcery-1.4.4.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.11.2-1.7.0.24.jar)
  li.cil.oc.common.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.11.2-2.0.0.388.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.162.4' Renderer: 'AMD Radeon (TM) R9 380 Series'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.11.2_HD_U_C1
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.162.4
	OpenGlRenderer: AMD Radeon (TM) R9 380 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8`

After removing "Better With Mods" problem seems resolved.

**Comment by AEnterprise** [comment] 2017-06-27 13:38
duplicate of #3676

will be fixed in the next version of BC

**Closed by AEnterprise** 2017-06-27 13:38 UTC
