### ISSUE TITLE
Crash report for version 7.99.1

### ISSUE THREAD

**Issue by WilliamBlaze** [BuildCraft/BuildCraft#3558] opened 2017-05-07 02:30 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  ForgelinPlugin (Forgelin-1.4.0.jar)
  LoadingPlugin (Quark-r1.2-90.jar)
  HammerCoreCore (HammerCore_1.11.2-1.5.7.jar)
  Plugin (NotEnoughIDs-1.5.4.jar)
  CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  llibrary (llibrary-1.7.4-1.11.2.jar)
  literalascension (literalascension-1.11.2-1.0.1.1.jar)
  MalisisSwitchesPlugin (malisisswitches-1.11.2-4.1.0.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/6/17 3:53 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BC Transport (buildcrafttransport)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.jamieswhiteshirt.literalascension.common.block.BlockDelegate.getPickBlock, parameter player
	at com.jamieswhiteshirt.literalascension.common.block.BlockDelegate.getPickBlock(BlockDelegate.kt)
	at buildcraft.transport.plug.FacadeStateManager.getRequiredStack(FacadeStateManager.java:63)
	at buildcraft.transport.plug.FacadeStateManager.postInit(FacadeStateManager.java:89)
	at buildcraft.transport.BCTransport.init(BCTransport.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2411569136 bytes (2299 MB) / 3075997696 bytes (2933 MB) up to 4124573696 bytes (3933 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3000m -Xmx4000m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2295 Optifine OptiFine_1.11.2_HD_U_B7 102 mods loaded, 102 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2295.jar) 
	UCHI	forge{13.20.0.2295} [Minecraft Forge] (forge-1.11.2-13.20.0.2295.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHI	rpghud{3.6.3} [RPG-Hud] ([1.11] RPG-HUD-3.6.3.jar) 
	UCHI	cxlibrary{1.4.0} [CXLibrary] (cxlibrary-1.11.2-1.4.0.jar) 
	UCHI	advinv{1.3.0} [Advanced Inventory] (advInv-1.11.2-1.3.0.jar) 
	UCHI	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCHI	ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.1-8.jar) 
	UCHI	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCHI	jei{4.3.4.273} [Just Enough Items] (jei_1.11.2-4.3.4.273.jar) 
	UCHI	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHI	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCHI	quark{r1.2-90} [Quark] (Quark-r1.2-90.jar) 
	UCHI	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHI	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHI	hammercore{1.5.7} [Hammer Core] (HammerCore_1.11.2-1.5.7.jar) 
	UCHI	blackholestorage{14r} [Black Hole Storage] (Black Hole Storage 1.11.2-14r.jar) 
	UCHI	blockdispenser{1.0} [BlockDispenser] (BlockDispenser-1.1-2.jar) 
	UCHI	buildcraftlib{7.99.1} [BuildCraft Lib] (buildcraft-7.99.1.jar) 
	UCHI	buildcraftcore{7.99.1} [BuildCraft] (buildcraft-7.99.1.jar) 
	UCHI	buildcraftfactory{7.99.1} [BC Factory] (buildcraft-7.99.1.jar) 
	UCHE	buildcrafttransport{7.99.1} [BC Transport] (buildcraft-7.99.1.jar) 
	UCHI	buildcraftbuilders{7.99.1} [BC Builders] (buildcraft-7.99.1.jar) 
	UCHI	buildcraftenergy{7.99.1} [BC Energy] (buildcraft-7.99.1.jar) 
	UCHI	buildcraftrobotics{7.99.1} [BC Robotics] (buildcraft-7.99.1.jar) 
	UCHI	buildcraftsilicon{7.99.1} [BC Silicon] (buildcraft-7.99.1.jar) 
	UCHI	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHI	chickenchunks{2.3.0.63} [ChickenChunks] (ChickenChunks-1.11.2-2.3.0.63-universal.jar) 
	UCHI	cookingforblockheads{5.2.6} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.2.6.jar) 
	UCHI	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2_beta(17mar17).jar) 
	UCHI	cyberware{alpha-0.2.9} [Cyberware] (cyberware-1.11.2-alpha-0.2.9.jar) 
	UCHI	embers{0.209} [Embers] (embers-0.209.jar) 
	UCHI	endercompass{1.2.5.2} [Ender Compass] (EnderCompass-1.11-1.2.5.2.jar) 
	UCHI	epicsiegemod{12.0.157} [Epic Siege Mod] (EpicSiegeMod-12.0.157.jar) 
	UCHI	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.3.jar) 
	UCHI	zerocore{1.11.2-0.1.0.5} [Zero CORE] (zerocore-1.11.2-0.1.0.5.jar) 
	UCHI	bigreactors{1.11.2-0.4.5.28} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.28.jar) 
	UCHI	fairylights{2.1.0} [Fairy Lights] (fairylights-2.1.0-1.11.2.jar) 
	UCHI	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta4-law.jar) 
	UCHI	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
	UCHI	friendlyfire{1.4.0} [Friendly Fire] (FriendlyFire-1.11-1.4.0.jar) 
	UCHI	helpertools{v5.1} [HelperTools] (HelperTools-1.11.2-v5.1.jar) 
	UCHI	ironchest{1.11-7.0.17.799} [Iron Chest] (IronChest-1.11.jar) 
	UCHI	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHI	jeresources{0.6.3.5} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.3.5.jar) 
	UCHI	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCHI	literalascension{1.11.2-1.0.1.1} [Literal Ascension] (literalascension-1.11.2-1.0.1.1.jar) 
	UCHI	machinepowercraft{6a} [Machine Power Craft] (MachinePowerCraft 3_1.11.2-6a.jar) 
	UCHI	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHI	malisisblocks{1.11.2-5.1.0} [Malisis Blocks] (malisisblocks-1.11.2-5.1.0.jar) 
	UCHI	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHI	malisisswitches{1.11.2-4.1.0} [Malisis Switches] (malisisswitches-1.11.2-4.1.0.jar) 
	UCHI	mysticalagriculture{1.5.2} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.5.2c.jar) 
	UCHI	mysticalagradditions{1.0.2} [Mystical Agradditions] (mysticalagradditions[1.11.2]-1.0.2.jar) 
	UCHI	naturescompass{1.3.0} [Nature's Compass] (NaturesCompass-1.11.2-1.3.0.jar) 
	UCHI	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCHI	neid{1.5.4} [NotEnoughIDs] (NotEnoughIDs-1.5.4.jar) 
	UCHI	oredowsing{11.11.2-1.0.1-BETA} [Ore Dowsing] (OreDowsing-11.11.2-1.0.1-BETA.jar) 
	UCHI	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHI	petbat{1.4.7} [Pet Bat] (PetBat-1.11.2.jar) 
	UCHI	playerstats2{14r} [Player Stats 2] (PlayerStats2_1.11.2-14r.jar) 
	UCHI	thutcore{4.4.1} [ThutCore] (thutcore-4.4.1.jar) 
	UCHI	pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-5.2.7.jar) 
	UCHI	pokecube{5.2.7} [Pokécube Core] (Pokecube Core-5.2.7.jar) 
	UCHI	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-5.2.7.jar) 
	UCHI	pokecube_mobs{2.4.8} [Pokécube Mobs] (Pokecube Mobs-2.4.8.jar) 
	UCHI	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.4.8.jar) 
	UCHI	pokecube_adventures{5.0.7} [Pokécube Revival] (Pokecube Revival-5.0.7.jar) 
	UCHI	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-5.0.7.jar) 
	UCHI	pokeplayer{@VERSION} [Pokecube Mystery Dungeon] (Pokecube Revival-5.0.7.jar) 
	UCHI	recycler{1.4.5} [Corail Recycleur] (recycler-1.4.5-1.11.2.jar) 
	UCHI	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHI	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UCHI	rftools{6.00} [RFTools] (rftools-1.1x-6.00.jar) 
	UCHI	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHI	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHI	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHI	roots{0.016} [Roots 2] (roots-2-0.016.jar) 
	UCHI	shulkerbox{1.1.0} [Shulkerbox] (ShulkerBox 1.1.0.jar) 
	UCHI	secraft{III-1a} [Solar Energy Craft] (SolarEnergyCraft_1.11.2-III-1a.jar) 
	UCHI	solarfluxreborn{2.15r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.15r.jar) 
	UCHI	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.11.2-1.3a.jar) 
	UCHI	stacksize{1.1} [Stacksize Mod] (stacksize-1.11.2-1.1.jar) 
	UCHI	tesla{1.3.0.52} [TESLA] (Tesla-1.11-1.3.0.52.jar) 
	UCHI	teslafied{1.0.0} [Teslafied] (teslafied-1.11-1.1.0.jar) 
	UCHI	theoneprobe{1.4.6} [The One Probe] (theoneprobe-1.1x-1.4.6.jar) 
	UCHI	thut_wearables{2.1.2} [Thut's Wearables] (thut_wearables-2.1.2.jar) 
	UCHI	thut_bling{1.0.1} [Thut's Bling] (thut_bling-1.0.1.jar) 
	UCHI	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
	UCHI	toolbelt{1.6.0} [Tool Belt] (ToolBelt-1.11.2-1.6.0.jar) 
	UCHI	topaddons{1.11.2-0.10.0} [TOP Addons] (topaddons-1.11.2-0.10.0.jar) 
	UCHI	trashslot{7.4.3} [TrashSlot] (TrashSlot_1.11.2-7.4.3.jar) 
	UCHI	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.11-1.1.1a.jar) 
	UCHI	vanillafoodpantry{3.1r02} [Vanilla Food Pantry] (vanillafoodpantry-mc1.11.2-3.1r02.jar) 
	UCHI	variedcommodities{1.11.2} [Varied Commodities] (VariedCommodities_1.11.2(22jan17).jar) 
	UCHI	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHI	xnet{1.3.1} [XNet] (xnet-1.3.1.jar) 
	UCHI	yarrmateys_cutemobmodels{1.0.15} [Yarr Cute Mob Models - Remake] (YarrCuteMobModelsRemake-1.0.15-1.11.2.jar) 
	UCHI	denseores{1.0} [denseores] (denseores-1.11-alpha-1.0.1.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
ForgelinPlugin (Forgelin-1.4.0.jar)
  
LoadingPlugin (Quark-r1.2-90.jar)
  vazkii.quark.base.asm.ClassTransformer
HammerCoreCore (HammerCore_1.11.2-1.5.7.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
Plugin (NotEnoughIDs-1.5.4.jar)
  ru.fewizz.neid.asm.Transformer
CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  cubex2.cxlibrary.CoreModTransformer
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
literalascension (literalascension-1.11.2-1.0.1.1.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
MalisisSwitchesPlugin (malisisswitches-1.11.2-4.1.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.3347' Renderer: 'Intel(R) HD Graphics 2000'
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 

i can't make head or tales of my crash log, but if there's a way to trouble shoot the issue so i can use the Buildcraft 7.99.1 version, i'm all ears.

**Comment by AEnterprise** [comment] 2017-05-07 08:24
duplicate of #3544 , already fixed for the next version

**Closed by AEnterprise** 2017-05-07 08:24 UTC
