### ISSUE TITLE
mine wells and quarys arn't working and thers no conductive pipes yet

### ISSUE THREAD

**Issue by chrisrabbit** [BuildCraft/BuildCraft#3540] opened 2017-05-02 03:16 UTC

**Comment by afdw** [comment] 2017-05-02 03:39
How not working? What you done and what is result? Can you post screenshots?

**Comment by AEnterprise** [comment] 2017-05-02 07:18
the missing kinesis pipes is a duplicate of #3523 

you need to give the quarry frames to work, mining well should work if you put the engine directly on top and it has an output pipe for items

i'll close this as duplicate but if you still have issues with the mining well please post an screenshot of that setup and i will re-open the issue

**Closed by AEnterprise** 2017-05-02 07:18 UTC
