### ISSUE TITLE
Quarry does not seek

### ISSUE THREAD

**Issue by SirIntellegence** [BuildCraft/BuildCraft#3813] opened 2017-09-17 22:18 UTC
**Buildcraft** version: 7.99.7
**Forge** version: 13.20.1.2429
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Don't know if you need it yet...

Additional information:
I recall that in earlier versions, the quarry seeks blocks instead of doing a blind scan. It looks like it is wasting time trying to mine air. I can provide a save file if needed.

![quarry bug](https://user-images.githubusercontent.com/3401182/30525437-b22328f0-9bc3-11e7-8f0e-b3799f349192.gif)

**Comment by afdw** [comment] 2017-09-17 22:20
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3776.

**Closed by afdw** 2017-09-17 22:20 UTC
