### ISSUE TITLE
BuildCraft crashing server

### ISSUE THREAD

**Issue by VeterTkacz** [BuildCraft/BuildCraft#3985] opened 2018-01-21 00:31 UTC
**BuildCraft** version: 7.99.14
**Forge** version: 1.12.2
Link to crash report or log: https://gist.github.com/AEnterprise/4d099228e4d40d883fd2a0aa5acdbd49

Singleplayer or multiplayer: Server
Additional information: Me and some friends created a server a couple of days ago, and we installed BuildCraft we used the mod normally and we shut down the server this morning, now when we try to enter we can't get the server to run and the error seems like it's happening because of BuildCraft, please help.

**Comment by AlexIIL** [comment] 2018-01-21 00:51
That's odd. Unfortunately forge is just swallowing the error, so I don't actually know what the issue is :/

Do you have any other log files in your logs folder? It looks like that's the detailed one, it's possible that a different log file contains more information. Also, can you upload the log file to https://gist.github.com rather than pasting it directly into the comment.

**Comment by AEnterprise** [comment] 2018-01-21 08:49
can you try updating to latest forge? that MIGHT make forge spit out the error, also please check the crashlogs folder for it

**Comment by AEnterprise** [comment] 2018-01-23 07:51
thanks to the help of mezz and exidex with digging around forge will no longer be swallowing errors when there are both errors thrown in pre-init and registration phases

could you please update forge to 2603 and try again?

**Comment by AEnterprise** [comment] 2018-01-31 10:31
any update? can you try with forge 2603+ to get the error? without it we can't realy fix this as we don't know what went wrong

**Comment by AEnterprise** [comment] 2018-02-06 13:57
Closing for a lack of information, if you provide the requested information we can re-open and take another look at this.

**Closed by AEnterprise** 2018-02-06 13:57 UTC
Labels: status: needs investigation, version: 1.12.2
