### ISSUE TITLE
Crash(game won't start)

### ISSUE THREAD

**Issue by kenijey** [BuildCraft/BuildCraft#3541] opened 2017-05-02 06:41 UTC
[crash-2017-05-02_09.40.22-client.txt](https://github.com/BuildCraft/BuildCraft/files/969614/crash-2017-05-02_09.40.22-client.txt)
please help...

**Comment by AEnterprise** [comment] 2017-05-02 07:14
duplicate of #3534 

please search for your issue next time and make a more descriptive issue please.

**Closed by AEnterprise** 2017-05-02 07:14 UTC

**Comment by kenijey** [comment] 2017-05-02 07:15
oh sorry
