### ISSUE TITLE
Stirling Engine drops redstone engine.

### ISSUE THREAD

**Issue by jdkorv11** [BuildCraft/BuildCraft#3565] opened 2017-05-11 04:06 UTC
While playing in buildcraft 7.99.1 mining a stirling engine with a pickaxe it will drop a redstone engine.

**Comment by LuigiHutch** [comment] 2017-05-11 08:49
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3552. Update to 7.99.3

**Closed** 2017-05-11 12:40 UTC
Labels: duplicate
