### ISSUE TITLE
Rendering Screen

### ISSUE THREAD

**Issue by TheDarkLach** [BuildCraft/BuildCraft#4430] opened 2019-06-15 22:07 UTC
BuildCraft version: 7.99.24.1
Forge version: 1.12.2 - 14.23.5.2838
Link to crash report or log: [https://pastebin.com/nS5AE55E](url)
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: Playing on Minecraft 1.12.2 Whenever I right click an engine for my quarry the game freezes then crashes.
Additional information: Optifine not installed, seen similar issues where people had optifine installed.

**Comment by AlexIIL** [comment] 2019-06-15 22:25
Duplicate of #4419.

**Closed by AlexIIL** 2019-06-15 22:25 UTC
Labels: type: bug, version: 1.12.2
