### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [BuildCraft/BuildCraft#4001] opened 2018-01-26 13:25 UTC
BuildCraft version: buildcraft-7.99.14
Forge version: 14.23.1.2601
Link to crash report or log: https://pastebin.com/KsM7QZdq
Singleplayer or multiplayer: SMP
Additional information: Not 100% what happened here as I'm a server admin and not the player in question. Hope it helps from the crash report

**Comment by AlexIIL** [comment] 2018-01-26 13:40
It looks like something unexpected happened while extracting the item from *something*. For some reason that method doesn't log nearly as much as it should.

**Comment by AEnterprise** [comment] 2018-01-26 13:46
looks like a race or corrupt TE state to me, `[1xtile.air@0, 2147483647xtile.immersiveengineering.stone_decoration@3]` indicates the block was set to air (probably broken) but the TE has not been removed from the world for some reason?

but even then it's weird that it first supllied a stack during simulation and not for actual extraction as nothing else could have ticked

pinging @BluSunrize to see if he has an idea

**Comment by AlexIIL** [comment] 2018-01-26 13:47
No, no, it's nothing todo with TE state.

That string is an array of all the blocks in an item holder.

**Comment by AlexIIL** [comment] 2018-01-26 13:48
(1xtile.air@0 is t string returned by ItemStack.EMPTY.toString() )

**Comment by AEnterprise** [comment] 2018-01-26 13:49
oh that makes sense, my bad

**Comment by cauliflower69** [comment] 2018-01-26 14:22
I have asked the player in question and he said

1:52 PM] rich9517: had tow pipes extracting from a storage draw
[1:52 PM] rich9517: i think there may have been only one item left in the draw

**Comment by AEnterprise** [comment] 2018-01-31 10:28
did he have his drawer locked by any chanse?

**Comment by cauliflower69** [comment] 2018-01-31 12:21
It wasn't locked it did however have a creative upgrade

**Comment by Ghent** [comment] 2018-02-02 13:29
@cauliflower69 Was the extraction from a drawer, drawer slave or drawer controller?  What kind of pipe was it?  Testing to try to replicate so we can fix.

**Comment by AEnterprise** [comment] 2018-03-14 16:28
i'm gona have to close this for not being reproducable and missing info

**Closed by AEnterprise** 2018-03-14 16:28 UTC
Labels: status: needs investigation, type: bug, type: mod compat, version: 1.12.2
