### ISSUE TITLE
not launching due to issue with facadeswap issue (1.11.2-7.99.3)

### ISSUE THREAD

**Issue by SDUBZ** [BuildCraft/BuildCraft#3595] opened 2017-05-21 00:44 UTC
Forge:1.11.2-2300
Minecraft: 1.11.2
BuildCraft: buildcraft-7.99.3
[10:32:24] [Client thread/WARN] [FML]: ****************************************
[10:32:24] [Client thread/WARN] [FML]: * Unknown recipe class! buildcraft.transport.recipe.FacadeSwapRecipe Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[10:32:24] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:241)
[10:32:24] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:176)
[10:32:24] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:55)
[10:32:24] [Client thread/WARN] [FML]: *  at java.util.TimSort.gallopLeft(Unknown Source)
[10:32:24] [Client thread/WARN] [FML]: *  at java.util.TimSort.mergeAt(Unknown Source)
[10:32:24] [Client thread/WARN] [FML]: *  at java.util.TimSort.mergeForceCollapse(Unknown Source)...
[10:32:24] [Client thread/WARN] [FML]: ****************************************

**Comment by AEnterprise** [comment] 2017-05-21 08:26
duplicate of #3590

**Closed by AEnterprise** 2017-05-21 08:26 UTC
Labels: 1.11.2, bug
