### ISSUE TITLE
Empty Bucket Disappears from Stirling Engine After Exiting and Reloading the Game

### ISSUE THREAD

**Issue by snakemasterepic** [BuildCraft/BuildCraft#3998] opened 2018-01-25 05:21 UTC
BuildCraft version: 7.99.14
Forge version: 14.231.2555
Link to crash report or log: 
Singleplayer or multiplayer: Singleplayer
Additional information: 

**Summary**
If a lava bucket is used by a stirling engine and the user closes the game before retrieving the empty bucket, then the bucket disappears from the engine upon reloading the save.

**Repro Steps**

1. Launch Minecraft 1.12 with BuildCraft 7.99.14 installed.
2. Create a new world in creative mode.
3. Place a stirling engine.
4. Right click the engine and place a lava bucket in its fuel slot.
5. Place a lever next to the engine and pull the lever to turn the engine on.
6. Save and quit.
7. Reload the save.

**Observed Result**
There is no empty bucket in the fuel slot of the stirling engine.

**Expected Result**
There is an empty bucket in the fuel slot of the stirling engine.

**Notes**

- This only applies to empty buckets.  Removing the empty bucket and placing another lava bucket in the fuel slot before closing the world does not result in the new lava bucket disappearing.

#3938 

![2018-01-24_21 11 36](https://user-images.githubusercontent.com/17624346/35372029-81c464d2-014c-11e8-9d10-51ddf896fd1a.png)

**Comment by AEnterprise** [comment] 2018-01-25 11:43
gona close this as duplicate of the issue you linked as it's pretty much the same thing, empty buckets are not a valid fuel so upon reloading the slot is refusing (and thus voiding) the bucket

**Closed by AEnterprise** 2018-01-25 11:43 UTC
