### ISSUE TITLE
7.2.6 Connection problems: pipes->engines

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3336] opened 2016-05-12 21:50 UTC
why don't these pipes connect?
![2016-05-12_23 47 44](https://cloud.githubusercontent.com/assets/5960902/15231566/3f348df8-189c-11e6-8486-1b355179d2fc.png)
![2016-05-12_23 47 46](https://cloud.githubusercontent.com/assets/5960902/15231570/47310dce-189c-11e6-9c73-db23964cefe8.png)

5 blocks further
![2016-05-12_23 48 15](https://cloud.githubusercontent.com/assets/5960902/15231575/4eae86c6-189c-11e6-8834-860b183d7073.png)
![2016-05-12_23 48 18](https://cloud.githubusercontent.com/assets/5960902/15231577/5078a2a2-189c-11e6-8253-2047b0669277.png)

Any tips?

**Comment by rapus95** [comment] 2016-05-12 22:01
Further investigation resulted in this:
![2016-05-13_00 00 15](https://cloud.githubusercontent.com/assets/5960902/15231830/bd348022-189d-11e6-9969-ae9d0e8033f8.png)
Every engine has one orientation in which it doesn't connect to anything... But i've no clue what the actual direction depends on :/

**Comment by AgentK9** [comment] 2016-05-13 01:16
Well, kind of obviously, only wooden or emerald kinesis pipes connect to the front, but as for everything else... very strange.
@asiekierka 
@AlexIIL

**Comment by AlexIIL** [comment] 2016-05-24 18:25
Somehow a world reload fixed it for me... however I'm not sure how this is happening. It doesn't seem to be a sync issue (connecting from a different client doesn't change anything).

**Comment by AEnterprise** [comment] 2016-06-25 09:16
is this still an issue?

**Comment by AlexIIL** [comment] 2016-06-25 13:22
yes unfortunately, and I haven't been able to work out what causes it :(

**Comment by AEnterprise** [comment] 2016-06-25 13:29
just noticed that optifine is involved in the second set of screenshots

is it possible that a (partially) incorrect blockpos is being passed allong in the checks if it can connect or not?

**Comment by AlexIIL** [comment] 2016-06-25 17:46
It happens server-side, and I have reproduced it without optifine so its not to blame this time.

Its possible that an incorrect blockpos is being passed along somewhere, but I haven't found it yet.

**Comment by AEnterprise** [comment] 2016-08-31 12:47
is this still heapening?

**Comment by 0142929** [comment] 2017-05-12 18:08
latest buildcraft-7.2.8 for 1.8.9 has same problem
![2017-05-12_21 05 15](https://cloud.githubusercontent.com/assets/896793/26010783/ef0a9216-3756-11e7-9ad4-dae6efe62d43.png)
![2017-05-12_21 05 59](https://cloud.githubusercontent.com/assets/896793/26010782/ef093ca4-3756-11e7-92aa-b19a76288fc0.png)

**Comment by AEnterprise** [comment] 2017-05-12 18:10
euh not in that setup, that redstone engine is not suposed to connect to the wooden kinesis pipe because it proveds to weak power (becuase it's basicly free power)

also closing this as nobody else reported this heapening so should be fixed (as long as optifine isn't involved)

**Comment by LuigiHutch** [comment] 2017-05-12 18:11
Well this is fixed in 7.99.x but not 7.2.x

**Closed by AEnterprise** 2017-05-12 18:10 UTC
Labels: 1.8.9, bug

**Comment by AEnterprise** [comment] 2017-05-12 18:13
yes but i don't think we will be doing anymore 7.2.x releases unless critical world devouring bugs pop up with the development being focused on the 8.0 branch

**Comment by 0142929** [comment] 2017-05-12 18:15
re-open ticket please, still not resolved

**Comment by 0142929** [comment] 2017-05-12 18:16
so no more 1.8.9 support?

**Comment by AEnterprise** [comment] 2017-05-12 18:35
correct, with the development being focused on 1.11 there is no 1.8.9 support at this time

**Comment by 0142929** [comment] 2017-05-12 18:41
that's very pity...
so.. me'll try to fix it myself.
maybe you can tell me where to look please?
me still new in java

**Comment by AEnterprise** [comment] 2017-05-12 18:48
if you want to try and fix it yourself and do a PR you are more then welcome to
as for where to look: the only thing i can say is look at the engine placement code and anything related

at some point an effort was made to fix this but none of the devs found the root cause, it is most likely an incorrect blockposs being passed somewhere or an incorrect shifing of it to check

**Comment by AlexIIL** [comment] 2017-05-12 18:59
@0142929 it's likely to be somewhere in https://github.com/BuildCraft/BuildCraft/blob/7.2.x/common/buildcraft/core/lib/engines/TileEngineBase.java, or in the methods related to it.

**Comment by 0142929** [comment] 2017-05-13 16:55
thanks very much!
