### ISSUE TITLE
[v7.99.3] Game Loading Freeze - No Crashing...just no loading

### ISSUE THREAD

**Issue by MokahTGS** [BuildCraft/BuildCraft#3617] opened 2017-05-26 23:31 UTC
Getting some wierd behavior when trying to load the game with BC installed.  the game starts to load and then gets to the end but then stops loading when the console gets to this point:

https://pastebin.com/mNz5wCvK

Again, no crash, just gets stuck trying to load the game.

**Comment by AlexIIL** [comment] 2017-05-26 23:34
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3590 - It should be fixed when 7.99.4 is released.

**Closed by AlexIIL** 2017-05-26 23:34 UTC
Labels: duplicate
