### ISSUE TITLE
[1.11.2] Cannot craft conduction pipes

### ISSUE THREAD

**Issue by Knito58** [BuildCraft/BuildCraft#3664] opened 2017-06-10 12:24 UTC
Recipes seem to be missing. No result is given when I lay it out in the crafting table. JEI doesn't show any conducting pipes.

**Comment by AEnterprise** [comment] 2017-06-10 12:26
duplicate of #3523 they are not ported yet

**Closed by AEnterprise** 2017-06-10 12:26 UTC
