### ISSUE TITLE
Gate's right slots can't be accessed when using JEI

### ISSUE THREAD

**Issue by KrisBigK** [BuildCraft/BuildCraft#3901] opened 2017-12-07 23:03 UTC
The right slots of the gate can't be accessed because JEI 's inventory covers it

**Buildcraft** version: 7.99.12
**Forge** version: forge1.12.2-14.23.1.2555
Singleplayer/multiplayer: Singleplayer
Additional information:JEI version:4.7.10.97

**Comment by AlexIIL** [comment] 2017-12-07 23:08
Duplicate of #3866 (BuildCraft/BuildCraftCompat#78). This will be fixed in (not released quite yet) compat for 7.99.13.

**Closed by AlexIIL** 2017-12-07 23:08 UTC
