### ISSUE TITLE
[1.8.9] Null World Crash in Chunk-Loaded Dimension

### ISSUE THREAD

**Issue by oitsjustjose** [BuildCraft/BuildCraft#3279] opened 2016-03-27 15:11 UTC
[FML Crash Report](http://puu.sh/nVMGO/7fcb2dbd9f.txt)

So I can't take any photos of what I'm doing, so let me try to explain the setup. This may not be a fault of BuildCraft's, but rather a fault of EnderIO's (which is alpha, so that's fair - I can report it to CrazyPants if it's EnderIO).

I have a BloodMagic teleposer teleporting a BuildCraft Tank between the overworld (for Botania mana generation) and the nether (for a lava refill). This setup worked fine overnight, but today when I got on (and happened to get teleported by the Teleposer as I was walking by), the server threw this crash. Both sides are Chunk-Loaded, and now the server crashes promptly after the world has completed loading.

Any idea why my presence (assuming that that's what caused it, seeing as it only happened when I got teleposed to the nether too) would cause the tank's worldObj to be null? On the nether side, I am using EnderIO Pressurized Fluid Conduits to get lava from the pump to the tank for its transfer speed.

**Comment by AEnterprise** [comment] 2016-03-27 15:44
it seems that the cause of this is a race condition, the tank is teleported and the fluid conduit tries to access it before the world of the tank is correctly set, probably cause the teleporter didn't finish yet

**Comment by XFactHD** [comment] 2016-03-29 19:10
This did also happen to @Direwolf20 on ForgeCraft and he did only use BC pipes. The source and destination were both in the Overworld in his case.

**Comment by AlexIIL** [comment] 2016-03-29 19:35
If you haven't already I would recommend opening an issue with ender IO and seeing if they have caused it.

**Comment by HenryLoenwind** [comment] 2016-03-29 20:37
throwNullWorldCrash? having no world a is perfectly valid condition in vanilla. Not guarding against it I can understand, but doing it that way?

**Comment by AlexIIL** [comment] 2016-03-29 20:52
@HenryLoenwind  Actually the issue is that someone has added a BC tile to the world WITHOUT setting its worldObject. This does not happen in vanilla, its only happened (so far) after it has been teleported via an enderIO teleporter

**Comment by HenryLoenwind** [comment] 2016-03-29 21:04
It also happens with vanilla. We had had quite a lot of crashes on chunk-loading in 1.8.9 until we null-world-proofed all multi-blocks. There must have been some change in vanilla here.

**Comment by AlexIIL** [comment] 2016-03-29 21:07
This also happens if you teleport a tank a few blocks, so its not chunkloading.

**Comment by AlexIIL** [comment] 2016-03-29 22:00
Actually yeah on second thought I can just ignore it and pretend that the tile doesn't exist instead of throwing a tantrum.

**Comment by AlexIIL** [comment] 2016-03-29 23:33
To clarify (after some thought) its defiantly BC's fault (sorry for blaming BM and enderIO) however BM's fix will ensure that it is ready to be used a few ticks before it normally would.

**Comment by oitsjustjose** [comment] 2016-03-31 21:19
Nah, no worries, thanks for fixing it! /me anxiously waits for an update while also waiting for BC 8's massive changes ;D

**Comment by AlexIIL** [comment] 2016-04-02 12:06
Should be fixed in 7.2.5

**Closed by AlexIIL** 2016-04-02 12:06 UTC
