### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by maverag** [BuildCraft/BuildCraft#3653] opened 2017-06-05 16:30 UTC
[crash 122.txt](https://github.com/BuildCraft/BuildCraft/files/1052540/crash.122.txt)

**Comment by AlexIIL** [comment] 2017-06-05 16:42
Duplicate of #3639 -- the issue is caused by NEI, reported [here](https://github.com/TheCBProject/NotEnoughItems/issues/100).

Hopefully they fix this soon :)

**Closed by AlexIIL** 2017-06-05 16:42 UTC
