### ISSUE TITLE
Oil looks like water.

### ISSUE THREAD

**Issue by kjl2875** [BuildCraft/BuildCraft#3652] opened 2017-06-05 03:34 UTC
But, is real oil.
Using pump, golden fluid pipe and tanks.

**Comment by AEnterprise** [comment] 2017-06-05 06:48
i'm assuming you ment it looks like water. What BC, MC and forge versions are you using? Also do you have any mods that change rendering (like optifine or similar)?

**Comment by AlexIIL** [comment] 2017-06-05 10:37
Can you screenshot it?

**Comment by kjl2875** [comment] 2017-06-05 11:28
forge-1.11.2-13.20.0.2312-windows base.

I using 18 mods in
forestry_1.11.2-5.3.4.99.jar
industrialcraft-2-2.7.59-ex111.jar
buildcraft-7.99.4.jar

and then, attach screenshot here.
(uploading)

**Comment by AEnterprise** [comment] 2017-06-05 11:35
your mods list is not adding up to 18 mods, you're missing 4, could you go into your world and hold F3+C for 10-15 seconds to force a debug crash and then put that crashreport on gist or pastebin and link it here

also there is no screenshot in the comment you made, could you also upload one?

**Comment by kjl2875** [comment] 2017-06-05 11:41
1. Please wait few days. because can not found this issu in single player.
2. Here. using all mods.
AutoRegLib-1.1-4.jar
bdlib-1.13.2.7-mc1.11.2.jar
buildcraft-7.99.4.jar
cfm-4.1.2-mc1.11.2.jar
CompactSolars-1.11.2-5.0.12.333-universal.jar
compatlayer-1.11.2-0.2.9.jar
forestry_1.11.2-5.3.4.99.jar
gendustry-1.6.5.7-mc1.11.2.jar
generators-0.9.20.5-mc1.11.2.jar
industrialcraft-2-2.7.59-ex111.jar
EJML-core-0.26.jar
ironchest-1.11.2-7.0.19.803.jar
jei_1.11.2-4.3.5.277.jar
journeymap-1.11.2-5.4.6.jar
mcjtylib-1.1x-2.3.11.jar
Morph-o-Tool-1.1-13.jar
OptiFine_1.11.2_HD_U_C1.jar
rftools-1.1x-6.01.jar
worldedit-forge-mc1.11-6.1.6-dist.jar

**Comment by AEnterprise** [comment] 2017-06-05 11:42
please remove optifine and see if that fixes the issue

**Comment by kjl2875** [comment] 2017-06-05 11:56
OK. Thank you.
(Can not attach screenshot. maybe deleted test world file.)

**Comment by TheCodedOne** [comment] 2017-06-05 12:08
so, can you reproduce the issue?

**Comment by AlexIIL** [comment] 2017-06-05 12:20
This sounds like a simalir bug where the order of fluids got messed up by connecting to a different server or world, and then fluid pipes and tanks would render client side as whatever the previous fluid looked like. I want to say this this is a duplicate of that bug but I can't find it on github so I'll assume it's that. Does this sound like what was happening @kjl2875 ?

**Comment by AlexIIL** [comment] 2017-06-05 12:22
Specifically, if you place oil in the world is Igbo black (working) or blue (water, broken)

**Comment by kjl2875** [comment] 2017-06-05 12:27
I think so. @AlexIIL

I can't reproduce the issue.
so, I keep trying.

and I have same time this issu.
https://github.com/BuildCraft/BuildCraft/issues/3650

1. Using oil pump.
2. Server crash.
3. Change oil to water. (but, it real oil)

**Comment by Hypsellis** [comment] 2017-06-07 04:22
I get another strange bug surely caused by Optifine, the stagnant oil have missing texture.

**Comment by AEnterprise** [comment] 2017-06-07 06:13
@Hypsellis so when optifine is removed it looks fine? if so you will want to report it to optifine, i doubt it is somehting that needs to be fixed or can be fixed on our end (though we can never be certain as optifine is closed source so nobody realy knows everything it changes)

**Comment by Hypsellis** [comment] 2017-06-16 21:04
Here is pictures of the bug.
![2017-06-16_23 01 39](https://user-images.githubusercontent.com/17103411/27244706-0933da74-52e8-11e7-9795-853f9b1e0545.png)
![2017-06-16_23 04 27](https://user-images.githubusercontent.com/17103411/27244732-2a1315de-52e8-11e7-923f-113fbdf1416f.png)

**Comment by AlexIIL** [comment] 2017-06-16 21:19
...That's odd. Can you try with some of the other BC fluids? (specifically heavy oil, gaseous fuel, residue, etc. I *think* they are in 7.99.4)

**Comment by AEnterprise** [comment] 2017-06-17 07:32
also does this heapen without any rendering altering mods like optifine/shaders?

**Comment by Hypsellis** [comment] 2017-06-17 14:21
It doesn't seem to be caused by Optifine, it happens without it, and almost all the BuildCraft fluids have this issue.

**Comment by kjl2875** [comment] 2017-07-07 03:25
It looks happen from unknown texture partitical.
just talk it.

**Comment by AEnterprise** [comment] 2017-07-23 08:54
since it's caused by optifine we can't realy do much about it as we don't know how it's messing up the oil, best is to file a bug report to optifine, if the optifine dev(s), it might be something we are doing wrong but we'll need them to point it out then as we don't know what optifine is doing

**Closed by AEnterprise** 2017-07-23 08:54 UTC
Labels: status: needs investigation, type: bug, version: 1.11.2

**Comment by Hypsellis** [comment] 2017-07-25 20:07
I just told it wasn't caused by Optifine, it happens without it and happens to almost all BuildCraft fluids.

**Comment by LuigiHutch** [comment] 2017-07-25 20:31
Please find a reliable way to reproduce it and if you do, make a new issue on it. Thanks!
