### ISSUE TITLE
BC 7.2.2 Server attempting to load client-only classes

### ISSUE THREAD

**Issue by XeonDead** [BuildCraft/BuildCraft#3261] opened 2016-03-20 19:02 UTC
```
[21:56:47] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: buildcraft/api/transport/pluggable/PluggableModelKey
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_74]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_74]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/transport/pluggable/PluggableModelKey
        at buildcraft.transport.gates.ItemGate.createPipePluggable(ItemGate.java:224) ~[ItemGate.class:?]
        at buildcraft.transport.BlockGenericPipe.addOrStripPipePluggable(BlockGenericPipe.java:819) ~[BlockGenericPipe.class:?]
        at buildcraft.transport.BlockGenericPipe.func_180639_a(BlockGenericPipe.java:784) ~[BlockGenericPipe.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:427) ~[lg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:588) ~[lm.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_74]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.transport.pluggable.PluggableModelKey
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
        at buildcraft.transport.gates.ItemGate.createPipePluggable(ItemGate.java:224) ~[ItemGate.class:?]
        at buildcraft.transport.BlockGenericPipe.addOrStripPipePluggable(BlockGenericPipe.java:819) ~[BlockGenericPipe.class:?]
        at buildcraft.transport.BlockGenericPipe.func_180639_a(BlockGenericPipe.java:784) ~[BlockGenericPipe.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:427) ~[lg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:588) ~[lm.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_74]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
```

Getting this error when placing gate on a pipe, running BC 7.2.2 (latest).

**Comment by AlexIIL** [comment] 2016-03-21 13:05
This could be caused by us not building correctly or by a different mod including the BC api... what jar files are you using? (other mods, do you have only the BC "all" jar or do you have all the separate modules)

**Comment by XeonDead** [comment] 2016-03-21 20:32
Clean setup. No other than BC "all" 7.2.2 jar and BC-Compat 7.2.0, should be noted that error occures on SMP server.

Full stack trace below:
`[23:29:30] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: buildcraft/api/transport/pluggable/PluggableModelKey
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_74]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/transport/pluggable/PluggableModelKey
	at buildcraft.transport.gates.ItemGate.createPipePluggable(ItemGate.java:224) ~[ItemGate.class:?]
	at buildcraft.transport.BlockGenericPipe.addOrStripPipePluggable(BlockGenericPipe.java:819) ~[BlockGenericPipe.class:?]
	at buildcraft.transport.BlockGenericPipe.func_180639_a(BlockGenericPipe.java:784) ~[BlockGenericPipe.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:427) ~[lg.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:588) ~[lm.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.transport.pluggable.PluggableModelKey
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at buildcraft.transport.gates.ItemGate.createPipePluggable(ItemGate.java:224) ~[ItemGate.class:?]
	at buildcraft.transport.BlockGenericPipe.addOrStripPipePluggable(BlockGenericPipe.java:819) ~[BlockGenericPipe.class:?]
	at buildcraft.transport.BlockGenericPipe.func_180639_a(BlockGenericPipe.java:784) ~[BlockGenericPipe.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:427) ~[lg.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:588) ~[lm.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@5454d35e from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.8.9-11.15.1.1764-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at buildcraft.transport.gates.ItemGate.createPipePluggable(ItemGate.java:224) ~[ItemGate.class:?]
	at buildcraft.transport.BlockGenericPipe.addOrStripPipePluggable(BlockGenericPipe.java:819) ~[BlockGenericPipe.class:?]
	at buildcraft.transport.BlockGenericPipe.func_180639_a(BlockGenericPipe.java:784) ~[BlockGenericPipe.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:427) ~[lg.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:588) ~[lm.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
Caused by: java.lang.RuntimeException: Attempted to load class buildcraft/api/transport/pluggable/PluggableModelKey for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49) ~[forge-1.8.9-11.15.1.1764-universal.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.8.9-11.15.1.1764-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at buildcraft.transport.gates.ItemGate.createPipePluggable(ItemGate.java:224) ~[ItemGate.class:?]
	at buildcraft.transport.BlockGenericPipe.addOrStripPipePluggable(BlockGenericPipe.java:819) ~[BlockGenericPipe.class:?]
	at buildcraft.transport.BlockGenericPipe.func_180639_a(BlockGenericPipe.java:784) ~[BlockGenericPipe.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:427) ~[lg.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:588) ~[lm.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:59) ~[ja.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_74]
	at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
	... 5 more
`

**Comment by AlexIIL** [comment] 2016-03-21 20:55
Does this happen in singleplayer?
Also can you screenshot the contents of the folder ````buildcraft/api/transport/pluggable/```` inside the BuildCraft jar? (Basically if a file called ````PluggableModelKey.java```` exists)

**Comment by AlexIIL** [comment] 2016-03-21 20:57
Sorry I misread your comment, Thanks for the bug report!

**Comment by AlexIIL** [comment] 2016-03-22 14:22
Fixed in https://github.com/BuildCraft/BuildCraft/commit/2bd01a24522fd0c8d98ecdc263ddc80f496c8be9

**Closed by AlexIIL** 2016-03-22 14:22 UTC
Labels: bug-major, minecraft 1.8
