### ISSUE TITLE
Minecraft crashes when loading a Spawner

### ISSUE THREAD

**Issue by guyfromhere** [BuildCraft/BuildCraft#3375] opened 2016-06-26 09:55 UTC
Hey, I'm using the stable version for 1.7.10.
Yesterday I wanted to play Minecraft since a long time, but Minecraft crashed everytime on the same location. The crash report says, it was an 

> Rendering Block Entity

error. Some lines below I found this:

> -- Block Entity Details --
> Details:
> 	Name: MobSpawner // net.minecraft.tileentity.TileEntityMobSpawner
> 	Block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
> 	Block data value: 0 / 0x0 / 0b0000
> 	Block location: World: (-84,34,-2878), Chunk: (at 12,2,2 in -6,-180; contains blocks -96,0,-2880 to -81,255,-2865), Region: (-1,-6; contains chunks -32,-192 to -1,-161, blocks -512,0,-3072 to -1,255,-2561)
> 	Actual block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
> 	Actual block data value: 0 / 0x0 / 0b0000

Means that the MobSpawner at -84 34 -2878 has created the error.
I removed all mods and I didn't had a crash. After some tries I just had BC 7.1.16 loaded and then it crashes at the "error"-location again.

**Comment by AEnterprise** [comment] 2016-06-26 09:59
i highly doubt this is a BC error as BC doesn't add mobs or changes anything even remotely related to mobspawners

also you cut out all the information we need from the crashlog, please upload the crashlog to gist or pastebin and link it here

**Comment by guyfromhere** [comment] 2016-06-26 10:03
> ---- Minecraft Crash Report ----
> // I bet Cylons wouldn't have this problem.
> 
> Time: 6/26/16 12:02 PM
> Description: Rendering Block Entity
> 
> java.lang.NullPointerException: Rendering Block Entity
> 	at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98265_a(SourceFile:110)
> 	at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98281_h(SourceFile:236)
> 	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147517_a(SourceFile:20)
> 	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:15)
> 	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:10)
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
> 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
> 	at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98265_a(SourceFile:110)
> 	at net.minecraft.tileentity.MobSpawnerBaseLogic.func_98281_h(SourceFile:236)
> 	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147517_a(SourceFile:20)
> 	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:15)
> 	at net.minecraft.client.renderer.tileentity.TileEntityMobSpawnerRenderer.func_147500_a(SourceFile:10)
> 
> -- Block Entity Details --
> Details:
> 	Name: MobSpawner // net.minecraft.tileentity.TileEntityMobSpawner
> 	Block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
> 	Block data value: 0 / 0x0 / 0b0000
> 	Block location: World: (-84,34,-2878), Chunk: (at 12,2,2 in -6,-180; contains blocks -96,0,-2880 to -81,255,-2865), Region: (-1,-6; contains chunks -32,-192 to -1,-161, blocks -512,0,-3072 to -1,255,-2561)
> 	Actual block type: ID #52 (tile.mobSpawner // net.minecraft.block.BlockMobSpawner)
> 	Actual block data value: 0 / 0x0 / 0b0000
> Stacktrace:
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
> 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [EntityClientPlayerMP['myminecraftname'/323, l='MpServer', x=-38.70, y=50.95, z=-2839.29]]
> 	Chunk stats: MultiplayerChunkCache: 625, 625
> 	Level seed: 0
> 	Level generator: ID 00 - default, ver 1. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (-64,75,-2778), Chunk: (at 0,4,6 in -4,-174; contains blocks -64,0,-2784 to -49,255,-2769), Region: (-1,-6; contains chunks -32,-192 to -1,-161, blocks -512,0,-3072 to -1,255,-2561)
> 	Level time: 8626488 game time, 9324734 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
> 	Forced entities: 105 total; [EntityPig['Pig'/264, l='MpServer', x=26.22, y=70.00, z=-2891.34], EntityPig['Pig'/265, l='MpServer', x=30.44, y=71.00, z=-2866.69], EntityEnderman['Enderman'/266, l='MpServer', x=31.09, y=30.00, z=-2866.63], EntityEnderman['Enderman'/267, l='MpServer', x=31.69, y=29.86, z=-2856.57], EntitySheep['Sheep'/268, l='MpServer', x=16.91, y=70.00, z=-2848.13], EntityCreeper['Creeper'/269, l='MpServer', x=22.50, y=51.00, z=-2838.50], EntitySpider['Spider'/270, l='MpServer', x=19.22, y=38.00, z=-2817.97], EntitySkeleton['Skeleton'/271, l='MpServer', x=21.50, y=56.00, z=-2829.50], EntitySkeleton['Skeleton'/272, l='MpServer', x=25.50, y=56.00, z=-2828.50], EntitySkeleton['Skeleton'/273, l='MpServer', x=23.50, y=56.00, z=-2827.50], EntitySkeleton['Skeleton'/274, l='MpServer', x=23.50, y=56.00, z=-2822.50], EntityCreeper['Creeper'/275, l='MpServer', x=19.53, y=54.00, z=-2810.34], EntityCreeper['Creeper'/276, l='MpServer', x=18.50, y=54.00, z=-2812.50], EntityCreeper['Creeper'/277, l='MpServer', x=16.63, y=54.00, z=-2808.91], EntityZombie['Zombie'/278, l='MpServer', x=23.50, y=13.00, z=-2798.94], EntityBat['Bat'/279, l='MpServer', x=22.34, y=13.00, z=-2778.75], EntityBat['Bat'/280, l='MpServer', x=29.25, y=60.10, z=-2777.25], EntitySkeleton['Skeleton'/282, l='MpServer', x=24.50, y=17.00, z=-2763.50], EntityCreeper['Creeper'/283, l='MpServer', x=17.53, y=16.00, z=-2767.44], EntitySkeleton['Skeleton'/284, l='MpServer', x=27.94, y=46.00, z=-2769.47], EntitySheep['Sheep'/290, l='MpServer', x=37.81, y=69.00, z=-2858.78], EntityPig['Pig'/291, l='MpServer', x=33.31, y=70.00, z=-2861.22], EntitySkeleton['Skeleton'/293, l='MpServer', x=33.50, y=37.00, z=-2835.50], EntityBat['Bat'/294, l='MpServer', x=42.50, y=40.00, z=-2830.59], EntityBat['Bat'/295, l='MpServer', x=29.03, y=34.42, z=-2837.22], EntityCreeper['Creeper'/296, l='MpServer', x=40.31, y=49.00, z=-2843.22], EntitySkeleton['Skeleton'/298, l='MpServer', x=37.50, y=37.00, z=-2832.09], EntityZombie['Zombie'/300, l='MpServer', x=36.50, y=36.00, z=-2805.50], EntityZombie['Zombie'/302, l='MpServer', x=40.45, y=21.00, z=-2778.70], EntityZombie['Zombie'/303, l='MpServer', x=42.84, y=22.00, z=-2779.05], EntityZombie['Zombie'/87, l='MpServer', x=-115.50, y=34.00, z=-2897.50], EntityZombie['Zombie'/90, l='MpServer', x=-117.50, y=34.00, z=-2895.50], EntityZombie['Zombie'/91, l='MpServer', x=-116.50, y=34.00, z=-2895.50], EntityZombie['Zombie'/92, l='MpServer', x=-116.66, y=34.00, z=-2888.66], EntityWitch['Witch'/93, l='MpServer', x=-115.50, y=34.00, z=-2891.50], EntitySheep['Sheep'/94, l='MpServer', x=-119.73, y=64.00, z=-2896.22], EntitySkeleton['Skeleton'/95, l='MpServer', x=-113.50, y=19.00, z=-2867.84], EntitySheep['Sheep'/96, l='MpServer', x=-106.81, y=64.00, z=-2859.56], EntityChicken['Chicken'/97, l='MpServer', x=-101.59, y=63.00, z=-2811.63], EntityItem['item.item.egg'/98, l='MpServer', x=-101.19, y=63.13, z=-2812.78], EntityClientPlayerMP['myminecraftname'/323, l='MpServer', x=-38.70, y=50.95, z=-2839.29], EntityPig['Pig'/102, l='MpServer', x=-86.16, y=63.00, z=-2909.25], EntitySkeleton['Skeleton'/103, l='MpServer', x=-90.50, y=33.00, z=-2887.50], EntitySkeleton['Skeleton'/104, l='MpServer', x=-91.50, y=33.00, z=-2883.50], EntityChicken['Chicken'/105, l='MpServer', x=-84.38, y=63.00, z=-2880.63], EntityCreeper['Creeper'/106, l='MpServer', x=-95.50, y=29.00, z=-2867.50], EntitySheep['Sheep'/107, l='MpServer', x=-87.78, y=64.00, z=-2878.16], EntitySheep['Sheep'/108, l='MpServer', x=-86.88, y=65.00, z=-2856.19], EntityPig['Pig'/109, l='MpServer', x=-86.03, y=65.00, z=-2861.03], EntityPig['Pig'/110, l='MpServer', x=-87.66, y=65.00, z=-2863.50], EntitySkeleton['Skeleton'/111, l='MpServer', x=-92.50, y=49.00, z=-2831.94], EntitySheep['Sheep'/121, l='MpServer', x=-79.75, y=63.00, z=-2907.78], EntityPig['Pig'/122, l='MpServer', x=-75.59, y=64.00, z=-2866.50], EntityMinecartChest['entity.MinecartChest.name'/123, l='MpServer', x=-73.50, y=33.50, z=-2862.50], EntitySkeleton['Skeleton'/124, l='MpServer', x=-73.53, y=63.00, z=-2808.91], EntityZombie['Zombie'/125, l='MpServer', x=-74.22, y=47.00, z=-2773.78], EntitySkeleton['Skeleton'/126, l='MpServer', x=-66.50, y=44.00, z=-2777.50], EntitySheep['Sheep'/137, l='MpServer', x=-51.97, y=65.00, z=-2901.94], EntitySheep['Sheep'/138, l='MpServer', x=-59.75, y=64.00, z=-2905.63], EntityMinecartChest['entity.MinecartChest.name'/139, l='MpServer', x=-58.50, y=34.50, z=-2873.13], EntityZombie['Zombie'/140, l='MpServer', x=-61.00, y=34.00, z=-2834.44], EntityZombie['Zombie'/141, l='MpServer', x=-53.50, y=34.00, z=-2841.50], EntityBat['Bat'/142, l='MpServer', x=-56.03, y=36.10, z=-2819.50], EntityBat['Bat'/143, l='MpServer', x=-55.56, y=35.10, z=-2824.13], EntitySnowman['Snow Golem'/144, l='MpServer', x=-48.63, y=85.00, z=-2805.63], EntityZombie['Zombie'/145, l='MpServer', x=-51.09, y=38.00, z=-2780.50], EntitySheep['Sheep'/148, l='MpServer', x=-41.94, y=65.00, z=-2904.94], EntityZombie['Zombie'/149, l='MpServer', x=-47.70, y=34.00, z=-2844.07], EntityBat['Bat'/150, l='MpServer', x=-32.03, y=32.10, z=-2817.34], EntitySpider['Spider'/151, l='MpServer', x=-37.06, y=21.00, z=-2790.63], EntityZombie['Zombie'/152, l='MpServer', x=-34.69, y=20.00, z=-2791.09], EntitySpider['Spider'/153, l='MpServer', x=-41.47, y=20.00, z=-2797.16], EntitySkeleton['Skeleton'/204, l='MpServer', x=-12.50, y=24.00, z=-2908.44], EntityBat['Bat'/205, l='MpServer', x=-34.31, y=15.92, z=-2897.28], EntityBat['Bat'/206, l='MpServer', x=-23.50, y=35.00, z=-2916.38], EntityPig['Pig'/207, l='MpServer', x=-28.66, y=66.00, z=-2903.50], EntitySheep['Sheep'/208, l='MpServer', x=-25.09, y=65.00, z=-2887.91], EntityZombie['Zombie'/209, l='MpServer', x=-23.59, y=18.00, z=-2805.97], EntitySkeleton['Skeleton'/210, l='MpServer', x=-16.47, y=41.00, z=-2791.84], EntityCreeper['Creeper'/211, l='MpServer', x=-23.50, y=28.00, z=-2760.09], EntityCreeper['Creeper'/212, l='MpServer', x=-23.50, y=28.00, z=-2758.50], EntityCreeper['Creeper'/213, l='MpServer', x=-20.35, y=28.69, z=-2757.86], EntityZombie['Zombie'/221, l='MpServer', x=-5.50, y=53.00, z=-2911.50], EntitySkeleton['Skeleton'/222, l='MpServer', x=-5.78, y=49.00, z=-2880.16], EntityZombie['Zombie'/223, l='MpServer', x=-12.50, y=48.00, z=-2876.50], EntityBat['Bat'/224, l='MpServer', x=-0.16, y=48.82, z=-2835.38], EntityBat['Bat'/225, l='MpServer', x=-2.00, y=48.95, z=-2837.72], EntitySheep['Sheep'/226, l='MpServer', x=-0.22, y=62.00, z=-2845.66], EntitySkeleton['Skeleton'/227, l='MpServer', x=-3.50, y=23.00, z=-2787.50], EntityZombie['Zombie'/228, l='MpServer', x=-0.78, y=22.00, z=-2788.78], EntityBat['Bat'/229, l='MpServer', x=-4.24, y=45.37, z=-2794.42], EntityBat['Bat'/230, l='MpServer', x=-12.50, y=41.89, z=-2792.59], EntityBat['Bat'/231, l='MpServer', x=-20.50, y=42.26, z=-2796.72], EntityPig['Pig'/240, l='MpServer', x=2.50, y=79.00, z=-2879.50], EntitySkeleton['Skeleton'/241, l='MpServer', x=6.71, y=15.00, z=-2853.05], EntityZombie['Zombie'/242, l='MpServer', x=8.25, y=48.00, z=-2851.38], EntitySkeleton['Skeleton'/243, l='MpServer', x=9.31, y=18.00, z=-2845.50], EntitySkeleton['Skeleton'/244, l='MpServer', x=10.13, y=18.00, z=-2845.50], EntitySkeleton['Skeleton'/245, l='MpServer', x=10.50, y=18.00, z=-2843.50], EntityPig['Pig'/246, l='MpServer', x=0.44, y=70.00, z=-2844.69], EntitySkeleton['Skeleton'/247, l='MpServer', x=4.69, y=29.00, z=-2809.62], EntityZombie['Zombie'/248, l='MpServer', x=13.69, y=22.00, z=-2821.34], EntityWitch['Witch'/249, l='MpServer', x=13.68, y=21.08, z=-2822.50], EntitySheep['Sheep'/250, l='MpServer', x=1.97, y=62.00, z=-2822.03], EntityZombie['Zombie'/251, l='MpServer', x=9.50, y=56.00, z=-2814.50]]
> 	Retry entities: 0 total; []
> 	Server brand: dml,forge
> 	Server type: Integrated single player server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.7.10
> 	Operating System: Mac OS X (x86_64) version 10.11.5
> 	Java Version: 1.8.0_74, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 151104368 bytes (144 MB) / 449036288 bytes (428 MB) up to 5355339776 bytes (5107 MB)
> 	JVM Flags: 5 total; -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	IntCache: cache: 13, tcache: 0, allocated: 12, tallocated: 96
> 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 10 mods loaded, 10 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
> 	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
> 	UCHIJAAAA	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) 
> 	UCHIJAAAA	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) 
> 	UCHIJAAAA	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) 
> 	UCHIJAAAA	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) 
> 	UCHIJAAAA	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) 
> 	UCHIJAAAA	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) 
> 	UCHIJAAAA	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) 
> 	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
> 	LWJGL: 2.9.1
> 	OpenGL: Intel Iris OpenGL Engine GL version 2.1 INTEL-10.14.66, Intel Inc.
> 	GL Caps: Using GL 1.3 multi texturing
> Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
> Anisotropic filtering is supported and maximum anisotropy is 16.
> Shaders are available because OpenGL 2.1 is supported.
> 
> 	Is Modded: Definitely; Client brand changed to 'dml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: []
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
> 	Anisotropic Filtering: Off (1).

**Comment by AEnterprise** [comment] 2016-06-26 10:36
that's no pastebin or gist so makes your comment very long and harder to read

looks to me like you have a corrupted spawner in your world, BC doesn't add entities so isn't the root cause, most likely you have a quarry that is chunkloading said corrupted spawner, you said you removed mods so most likely one of those added that spawner in the world with a custom entity that no longer exists cause you removed the mod

using an external program like MCEdit to remove the spawner should fix it so you can get back in your world

**Comment by guyfromhere** [comment] 2016-06-26 11:43
Is there a way to see which mod added the entity?

**Comment by AlexIIL** [comment] 2016-06-26 11:51
Not directly, no. However if you put your entire crash log into gist or pastebin then we might have a better idea of what is going on.

**Comment by guyfromhere** [comment] 2016-06-26 12:13
How to do it? Do mean I should upload the file?

**Comment by AlexIIL** [comment] 2016-06-26 12:15
Not quite. You should open the crash file, and then paste its contents into https://gist.github.com/. Give it a name, and then create it and paste the link to it back here.

**Comment by guyfromhere** [comment] 2016-06-26 12:19
https://gist.github.com/guyfromhere/0424f5796b74ab1061b84828838f9041

**Comment by AlexIIL** [comment] 2016-06-26 12:23
Yes, thats how you do it.

Could we have the crash report from when it was modded? That looks like that crash report is from a vanilla install without forge.

**Comment by guyfromhere** [comment] 2016-06-26 12:27
https://gist.github.com/guyfromhere/b8f3ca8d93e9632633df59c3646639c3

That's now only with BC.

**Comment by AlexIIL** [comment] 2016-06-26 13:47
That's odd... can you post a (full) modlist of all the mods you had before? It might be possible to work out which mod caused it.

**Comment by guyfromhere** [comment] 2016-06-26 15:22
`AncientTrees-1.7.10-1.3.0.jar
AppleCore-mc1.7.10-1.1.0.jar
AutoSapling-1.1.jar
BetterFoliage-1.0.3.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[ExtraBiomesXL][v1.4].jar
BiomesOPlenty-1.7.10-2.1.0.1338-universal.jar
Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
Chisel2-2.3.10.37.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
DynamicLights-1.7.10.jar
EasyCrafting-1.7.10-2.0.1.16.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
ExtraButtons-1.7.10.1.jar
Farseek-1.0.1.jar
GardenStuff-1.7.10-1.6.3.jar
GraveStones-1.7.2_1.4.jar
HungerOverhaul-1.7.10-1.0.0.jar
InventoryTweaks-1.59-dev-152.jar
KoreSample-1.7.10-1.3.0.jar
LitWR-1.7.10-1.0.7.jar
NotEnoughItems-1.7.10-1.0.4.83-universal.jar
OptiFine_1.7.10_HD_U_D1.jar
Pam's HarvestCraft 1.7.10j.jar
RecipeAPIv1.0.1.jar
RedstonePasteMod-1.7.10-1.6.2.jar
Ruins-1.7.10.jar
ShadersModCore-v2.3.31-mc1.7.10-f.jar
SimpleRefinement-mc1.7.10-1.0 (1).jar
SoundFilters-0.8_for_1.7.X.jar
StorageDrawers-1.7.10-1.5.6.jar
StorageDrawers-BiomesOPlenty-1.7.10-1.0.1.jar
Streams-0.1.2.jar
UndergroundBiomesConstructs-1.7.2-0.7.jar
VeganOption-mc1.7.10-0.1.1.jar
animalsPlus-1.2.jar
antiqueatlas-4.2.2-1.7.10.jar
backpack-2.0.1-1.7.x.jar
buildcraft-7.1.16.jar
carpentersblocks
extrabiomesxl_1.7.10-3.16.2.jar
hopperductmod-1.7.10-1.3.2.jar
plantmegapack-4.23-1.7.10-1448.jar
resources
ruins.txt
ruins_log.txt
worldedit-forge-mc1.7.10-6.0-beta-01.jar`

**Comment by guyfromhere** [comment] 2016-07-01 15:22
Okay, the world crashes only in 1.7.10. In 1.8+ there are no issues.
I downloaded just the Beta for 1.8.9 of BC, but it says me, that Forge Mod Loader has found a problem with my minecraft installation.
I'm using Forge for 1.8.9, so how to fix?

**Comment by AEnterprise** [comment] 2016-07-01 17:30
the only thing i can think of is a mod missing dependencies and it should then say what mod is missing what version of what dependency on your screen

**Comment by guyfromhere** [comment] 2016-07-01 17:32
Using Forge for 1.8.9 and the beta 7.2.7 for 1.8.9, downloaded from mod-buildcraft.com
![untitled](https://cloud.githubusercontent.com/assets/20150411/16529298/65fa1ab4-3fc2-11e6-9d4a-011f43b6ca59.png)

**Comment by AEnterprise** [comment] 2016-07-01 17:34
that's a broken image, can you please fix re-upload it? most likely you pressed comment while it still said 'uploading'

**Comment by guyfromhere** [comment] 2016-07-01 17:36
I'm able to see it. URL works also: https://cloud.githubusercontent.com/assets/20150411/16529298/65fa1ab4-3fc2-11e6-9d4a-011f43b6ca59.png

**Comment by AEnterprise** [comment] 2016-07-01 17:38
i am not able to see it, i only see the broken imagelink icon

**Comment by guyfromhere** [comment] 2016-07-01 17:45
<img width="854" alt="untitled" src="https://cloud.githubusercontent.com/assets/20150411/16529653/65511994-3fc4-11e6-930d-13ef46f7ef07.png">
Now?

**Comment by AlexIIL** [comment] 2016-07-01 17:49
Yeah, the image works now :)

That means that the forge version you have downloaded is outside of the range BuildCraft requires. What version did you download?

**Comment by guyfromhere** [comment] 2016-07-01 17:52
The official 1.8.9 from their homepage: http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.9.html

**Comment by AlexIIL** [comment] 2016-07-01 17:55
Ah right, you will have to download the "latest" version rather than the "recommended" version.

**Comment by AlexIIL** [comment] 2016-07-01 17:56
(As BuildCraft requires a few things that are not in the "recommended" version)

**Comment by guyfromhere** [comment] 2016-07-01 19:22
Thank you! It works with Forge 11.15.1.1902. :)

**Comment by AlexIIL** [comment] 2016-07-03 12:12
Is this fixed for you? If it is then please close this :)

**Comment by guyfromhere** [comment] 2016-07-03 13:20
resolved #3375

**Comment by AlexIIL** [comment] 2016-07-03 13:21
That's not quite how you close issues :P

**Closed by AlexIIL** 2016-07-03 13:21 UTC
