### ISSUE TITLE
Server crash upon placing a pipe

### ISSUE THREAD

**Issue by lelodragneel** [BuildCraft/BuildCraft#3835] opened 2017-10-25 02:54 UTC
**Buildcraft** version: 7.1.22
**Forge** version: forge-1.7.10-10.13.4.1614-1.7.10-universal

https://pastebin.com/qya93x2i

Additional information:
Placed a Stone Transport Pipe from BC Transport and the server instantly crashes. If I restart the server, it will instantly crash when I login (in the same chunk).

**Comment by AEnterprise** [comment] 2017-10-25 08:21
looks like an compat issue

@asiekierka do you still want to support 1.7.10 ?

**Comment by AlexIIL** [comment] 2017-10-25 16:01
I still do, especially for small things like this...

**Comment by AlexIIL** [comment] 2017-10-25 16:05
Duplicate of #3265, this should be continued at BuildCraft/BuildCraftCompat#59

**Closed** 2017-10-25 16:05 UTC
Labels: version: 1.7.10
