### ISSUE TITLE
Immersive Engineering Power not compatible

### ISSUE THREAD

**Issue by developerfabi** [BuildCraft/BuildCraft#4619] opened 2020-11-30 20:04 UTC
I tried to connect my Immersive Engineering (IF/RF) setup to a Buildcraft Assembly Table / Laser (see Picture). But apparently the laser can´t get power from the IE-Connectors. This was possible in 1.7.10, that´s why I´m asking. I would love for you guys to add Support again!

![2020-11-30_20 56 13](https://user-images.githubusercontent.com/39843259/100658565-9038b300-334f-11eb-858b-04b240b9aaa4.png)

Minecraft: 1.12.2
Forge: 14.23.5.2847
Buildcraft: 7.99.24.7
Immersive Engineering: 0.12-98

**Comment by gatoborrachon** [comment] 2020-11-30 20:26
Buildcraft for newer versions has move back to MJ, so there's no direct way to use RF in buildcraft machines, but there you have [Energy Converters](https://www.curseforge.com/minecraft/mc-mods/energy-converters)

**Comment by mikeloeven** [comment] 2021-04-03 15:55
Don't get me wrong, I have no problem with BC devs working on MJ as their internal power system however I am most certainly going to give them flack for not providing inbuilt conversion mechanisms for RF compatibility. Use Power Converters is not a valid suggestion as many mod-packs dont use that mod for numerous stability reasons. BC doesn't need to make their machines run on RF but they do need to provide some mechanism to convert between MJ / RF natively be it a block, pipe, or some other device

**Comment by AlexIIL** [comment] 2021-04-03 15:57
This is intentional.
(Duplicate of https://github.com/BuildCraft/BuildCraft/issues/4610)

**Closed by AlexIIL** 2021-04-03 15:57 UTC
Labels: auto: bug

**Comment by mikeloeven** [comment] 2021-04-03 19:48
No its childish and petty refusal to listen to the majority of the user base
