### ISSUE TITLE
Can't power machines with RF VERSION: 7.99.7

### ISSUE THREAD

**Issue by zozidalom** [BuildCraft/BuildCraft#3828] opened 2017-10-08 07:49 UTC
**Buildcraft** version: 7.99.7
**Forge** version: Latest 1.11.2 Beta
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: SinglePlayer

Additional information:

I can't power buildcraft machines like Quarry with RF. In the past this was possible.

**Comment by AEnterprise** [comment] 2017-10-08 08:27
duplicate of #3760

this was indeed possible in the past but since we have moved back towards MJ as powersystem

**Closed by AEnterprise** 2017-10-08 08:27 UTC
