### ISSUE TITLE
Quarry does not dig below the bedrock layer

### ISSUE THREAD

**Issue by SirIntellegence** [BuildCraft/BuildCraft#3816] opened 2017-09-19 00:26 UTC
**Buildcraft** version: 7.99.7
**Forge** version: 13.20.1.2429
Link to crashreport or log (on pastebin or gist, please don't put the entire log here) : 
Singleplayer/multiplayer: Don't think you need it yet

Additional information:
You can see the difference between previous versions of the quarry digging (left) and the current one (right). The quarry block is in the lower left and is powered (didn't get that in the shot...), the mining arm is in the upper right and is not moving. You can see a number of ores that were not mined on the right side.
![2017-09-18_18 13 21](https://user-images.githubusercontent.com/3401182/30570240-3b8dc2b0-9c9d-11e7-8e47-7f91645345c5.png)

**Comment by afdw** [comment] 2017-09-19 00:27
Probably duplicate of https://github.com/BuildCraft/BuildCraft/issues/3740?

**Comment by SirIntellegence** [comment] 2017-09-19 00:28
Do you suggest removing the water then?

**Comment by afdw** [comment] 2017-09-19 00:29
No, probably just wait for update of BC.

**Closed** 2017-09-19 00:31 UTC
