### ISSUE TITLE
cant take anything into bucket  from engine

### ISSUE THREAD

**Issue by xpatryk89** [BuildCraft/BuildCraft#4154] opened 2018-05-04 13:11 UTC
i found other error error, when i try to take it into bucket it dissapear, whater and oil too
BuildCraft version: 7.99.8.2
Forge version: 13.20.1.2476
Link to crash report or log: 
Singleplayer or multiplayer: single
Steps to reproduce: 
Additional information:

**Comment by LuigiHutch** [comment] 2018-05-04 13:58
Thanks for the report! This is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/4069

**Closed** 2018-05-04 14:46 UTC
