### ISSUE TITLE
No close GUI DUPE (duplicate glitch all blocks)

### ISSUE THREAD

**Issue by bigenergy** [BuildCraft/BuildCraft#4138] opened 2018-04-22 17:27 UTC
BuildCraft version: BuildCraft 7.99.16 1.12.2
Forge version: 2655
Link to crash report or log: no crash
Singleplayer or multiplayer: multiplayer
Steps to reproduce: All BuildCraft blocks that have a GUI Interface do not close the GUI.
Additional information:  You put a block that has a GUI interface, go into it, meanwhile your friend breaks this block, and the interface of this block remains open for you.

**Comment by bigenergy** [comment] 2018-04-22 17:42
Video - https://youtu.be/UthMuDJRt_I

**Comment by AlexIIL** [comment] 2018-04-22 19:26
Ok, so the issue is that you can break the block and still access the inventory. I think I've seen a similar report / fix in forge, so this sort of dupe glitch is probably already known.

**Comment by bigenergy** [comment] 2018-04-22 23:29
Are you sure this is a forge problem? On other mods there is no such.

**Comment by AlexIIL** [comment] 2018-04-22 23:35
No, not a bug in forge. I've seen a very similar bug report somewhere else, I'm not sure where though :/

**Comment by AlexIIL** [comment] 2018-04-22 23:57
Ok, looks like this is caused by incorrectly overriding `canInteractWith` in every single container... This shouldn't be too difficult to fix then. (The previous commit fixed another dupe glitch where blocks exploded with TNT or another explosion would drop their inventory... twice.

**Comment by AlexIIL** [comment] 2018-04-23 00:27
Ok, this should be fixed in [7.99.17-pre1](https://www.mod-buildcraft.com/releases/testing/BuildCraft/7.99.17-pre1/)

**Closed** 2018-05-06 17:40 UTC
Labels: priority: high, status: fixed/implemented in dev, type: bug, version: 1.12.2
