### ISSUE TITLE
No kinetic pipes

### ISSUE THREAD

**Issue by tattila8** [BuildCraft/BuildCraft#3566] opened 2017-05-11 06:21 UTC
I cant craft kinetic Pipes in Buildcraft 7.99.2

I use All the mods 2 v0.62

Please help!

**Comment by LuigiHutch** [comment] 2017-05-11 08:46
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3523. Also, why the hell are the alpha's in a public modpack?!?!

**Comment by AEnterprise** [comment] 2017-05-11 12:41
@LuigiHutch because modpack makers gladly ignore alpha tags or work around them to get the newest mods in their packs, even if they are unstable

**Closed by AEnterprise** 2017-05-11 12:41 UTC
