### ISSUE TITLE
Crash with matter overdrive

### ISSUE THREAD

**Issue by Neuromantix** [BuildCraft/BuildCraft#4364] opened 2019-02-20 06:36 UTC
BuildCraft version: 7.99.21/7.99.22
Forge version: 14.23.5.2814
Link to crash report or log: https://paste.dimdev.org/ejuvotowef.sql
[crash-2019-02-20_08.13.28-client.txt](https://github.com/BuildCraft/BuildCraft/files/2883276/crash-2019-02-20_08.13.28-client.txt)

Singleplayer or multiplayer: Singleplayer
Steps to reproduce: 5
Additional information:

**Comment by urmumecksdee** [comment] 2019-02-22 14:39
ye same for me

**Comment by AlexIIL** [comment] 2019-02-23 14:35
Can you try the workaround here: https://github.com/BuildCraft/BuildCraft/issues/4261#issuecomment-435389706 ?

(Also this is a duplicate of #4261, so I'll track it's progress there instead).

**Closed by AlexIIL** 2019-02-23 14:35 UTC
