### ISSUE TITLE
Item Duplication with Stripes Pipe

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft#2519] opened 2015-03-02 03:20 UTC
Well, using Buildcraft 6.4.1, BCCompat 6.4.0, Forge 10.13.2.1291
Some asked me if bucket can get milk using stripes pipe, then my test gave the positive answer.
Then, I gave a diamond sword to stripes pipe. The result is, one diamond sword is "threw away", and there is another one "came back through pipe".

The I test with iron axe and bedrock block, but this duplication still exists. Also did the test with obsidian pipe and normal quartz pipe+emerald pipe+vanilla chest.
It should be noticed that bucket cannot be duplicated. It will become to milk bucket.

Similar result on a sheep, but I did not test with shear. My guess is shear won't duplicate, since you can get wool from sheep with shear---the same as that you can get milk from cow with bucket.

Whatever, hope I can get reply soon. Also sorry for my English, and I will provide screenshot if necessary.

**Comment by asiekierka** [comment] 2015-03-02 11:18
Could not reproduce. With an obsidian pipe connected to a stripes pipe, as well as an obsidian pipe connected to gold pipes connected to a stripes pipe, only one diamond sword was thrown away.

Please try with http://asie.pl/bc642d.jar, both with and without BCCompat.

**Comment by hea3ven** [comment] 2015-03-02 12:08
It is the same as #2510, it will be fixed in the next version.

**Closed** 2015-03-02 12:20 UTC
Labels: duplicate
