### ISSUE TITLE
Cannot craft neither quarry nor gear. 

### ISSUE THREAD

**Issue by Syntax9421** [BuildCraft/BuildCraft#3769] opened 2017-08-09 16:19 UTC
Hi. On my multiplayer server i can't craft a quarry and i can't craft parts like gears and such. I can do it on a singleplayer server and i was wondering if there is anything that i'm missing?
When i try to craft gears, i put the wooden sticks in place and the recipe shows up i can take it out and move it but as soon as i close my workbench the sticks used to craft the gear falls to the floor. 
When i try to spawn in thing through JEI it gives me a message saying: the is no such item with name buildcraftcore:gear_wood and same goes for quarry. This issue only occurs on my multiplayer server. Is there a sub mod that i'm missing? using buildcraft version 7.99.6

Thanks in advance!

**Comment by AlexIIL** [comment] 2017-08-09 16:48
Its likely that the server is missing buildcraft - can you check to make sure that's not the case?

**Comment by Syntax9421** [comment] 2017-08-09 16:53
The server isn't missing buildcraft. It's in my modlist and have tried every single verision there is from 1.11.2.

**Comment by AlexIIL** [comment] 2017-08-09 16:56
Hmmm. Could you find and upload your log file and the server's log files?

**Comment by Syntax9421** [comment] 2017-08-09 16:58
[18:09:35] [Server thread/INFO]: Starting minecraft server version 1.11.2
[18:09:35] [Server thread/INFO]: Loading properties
[18:09:35] [Server thread/INFO]: Default game type: SURVIVAL
[18:09:35] [Server thread/INFO]: Generating keypair
[18:09:35] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:09:35] [Server thread/INFO]: Using default channel type
[18:09:36] [Server thread/INFO]: Preparing level "world"
[18:09:36] [Server thread/INFO]: Preparing start region for level 0
[18:09:37] [Server thread/INFO]: Preparing spawn area: 53%
[18:09:37] [Server thread/INFO]: Done (1,631s)! For help, type "help" or "?"
[18:10:07] [User Authenticator #1/INFO]: UUID of player Robban9421 is aa65df75-4514-4d7a-86ab-639d6a631e7d
[18:10:07] [Server thread/INFO]: Robban9421[/83.249.235.188:39541] logged in with entity id 115 at (-114.16537523746233, 79.0, -63.8207213583593)
[18:10:07] [Server thread/INFO]: Robban9421 joined the game
[18:23:03] [Server thread/INFO]: Robban9421 lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: En befintlig anslutning tvingades att stänga av fjärrvärddatorn], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[18:23:03] [Server thread/INFO]: Robban9421 left the game
urcePack:Just Enough Items, FMLFileResourcePack:Simple Quarry, FMLFileResourcePack:Xaero's Minimap
[18:09:52] [Client thread/WARN]: File minecraft:sounds/tock4.ogg does not exist, cannot add it to event bibliocraft:tock
[18:09:52] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:09:52] [Thread-8/INFO]: Initializing LWJGL OpenAL
[18:09:52] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:09:52] [Thread-8/INFO]: OpenAL initialized.
[18:09:52] [Sound Library Loader/INFO]: Sound engine started
[18:09:54] [Client thread/INFO]: Created: 16x16 textures-atlas
[18:09:55] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BuildCraft Lib, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Transport, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Hammer Core, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:Just Enough Items, FMLFileResourcePack:Simple Quarry, FMLFileResourcePack:Xaero's Minimap
[18:09:56] [Client thread/WARN]: File minecraft:sounds/tock4.ogg does not exist, cannot add it to event bibliocraft:tock
[18:09:56] [Client thread/INFO]: SoundSystem shutting down...
[18:09:56] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[18:09:56] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:09:56] [Thread-12/INFO]: Initializing LWJGL OpenAL
[18:09:56] [Thread-12/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:09:56] [Thread-12/INFO]: OpenAL initialized.
[18:09:57] [Sound Library Loader/INFO]: Sound engine started
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate1.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate0.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate3.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate2.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate8.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate5.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate4.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate7.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:58] [Client thread/WARN]: Texture bibliocraft:textures/models/inkplate6.png with size 8x8 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.
[18:09:59] [Client thread/INFO]: Created: 2048x1024 textures-atlas
[18:10:00] [Client thread/WARN]: Skipping bad option: lastServer:
[18:10:00] [Client thread/INFO]: [STDOUT]: Minimap is outdated!
[18:10:00] [Client thread/ERROR]: ########## GL ERROR ##########
[18:10:00] [Client thread/ERROR]: @ Post render
[18:10:00] [Client thread/ERROR]: 1280: Invalid enum
[18:10:06] [Client thread/INFO]: Connecting to 83.249.235.188, 25565
[18:10:09] [Client thread/INFO]: [STDOUT]: Spawn set minimap
[18:10:12] [Thread-17/INFO]: [CHAT] WARNING: BuildCraft 7.99.6 is in ALPHA!
[18:10:12] [Thread-17/INFO]: [CHAT]   Report bugs you find here
[18:10:12] [Thread-17/INFO]: [CHAT]   and include the version 7.99.6 in the description
[18:17:41] [Client thread/INFO]: [CHAT] There is no such item with name buildcraftcore:gear_wood
[18:22:34] [Client thread/INFO]: [CHAT] There is no such item with name buildcraftbuilders:quarry
[18:22:35] [Client thread/INFO]: [CHAT] There is no such item with name simplequarry:powered_quarry
[18:22:37] [Client thread/INFO]: [CHAT] There is no such item with name simplequarry:fuel_quarry
[18:23:02] [Client thread/INFO]: Stopping!
[18:23:02] [Client thread/INFO]: SoundSystem shutting down...
[18:23:02] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com


Here is my latest log file

**Comment by AlexIIL** [comment] 2017-08-09 17:06
Oh sorry, can you upload the full log files to https://gist.github.com/ and link them?

**Comment by AlexIIL** [comment] 2017-08-09 17:07
And server log file needed is "fml-server-latest", just so we have the full log file.

**Comment by Syntax9421** [comment] 2017-08-09 17:13
https://gist.github.com/Syntax9421/332ccb51e161492a66dc3609eb2a9240

**Comment by Syntax9421** [comment] 2017-08-09 17:13
Here is the link to the file.

**Comment by AlexIIL** [comment] 2017-08-09 17:14
thanks, I'm looking through it....

**Comment by AlexIIL** [comment] 2017-08-09 17:18
Looks like that doesn't have anything useful unfortunately. Might it be the case that you have disabled some BC items or blocks in the config files? (````config/buildcraft/objects.cfg````)

**Comment by Syntax9421** [comment] 2017-08-09 17:18
No everthing is as it should be...

**Comment by AlexIIL** [comment] 2017-08-09 17:22
Hmm ok. Can you also upload your full client log file as well?

**Comment by AEnterprise** [comment] 2017-08-13 08:27
@Syntax9421 can you provide the requested config file and full client and server logs (in a gist or different pastebins)? or join our discord (http://discord.gg/GuptcnW ) so we can try to help?

**Comment by AEnterprise** [comment] 2017-08-14 06:56
are you using a cracked laucher/client by chanse?

**Comment by asiekierka** [comment] 2017-08-14 07:16
The UUID is fine, so that's not it.

**Comment by AEnterprise** [comment] 2017-08-14 07:17
well we had someone asking for support during the night using a cracked launcher with this exact same issue so i'm wondering if it could be the cause or related

**Comment by AEnterprise** [comment] 2017-09-07 12:06
any extra info you can provide? if not we'll have to close this one as i cannot reproduce this in any way shape or form

**Closed** 2017-09-09 17:18 UTC
