### ISSUE TITLE
[1.12.2] Crash when connecting to server

### ISSUE THREAD

**Issue by Diamondman121314** [BuildCraft/BuildCraft#4129] opened 2018-04-16 01:44 UTC
BuildCraft version: 7.99.16
BuildCraft Compact version: 7.99.14
Forge version: 14.23.3.2666
Link to crash report or log: https://pastebin.com/qx60xUBa
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: Just joining the server as far as I know
Additional information: Not really sure if this is needed, but here's the mods list: https://pastebin.com/swH3XdkE
I went to join my test server and before even logging in, I get kicked with the message in the error.

**Comment by AlexIIL** [comment] 2018-04-16 11:55
I think this is related to (and might be a duplicate of) BuildCraft/BuildCraftCompat#80

**Comment by AEnterprise** [comment] 2018-04-17 17:05
yes this is a dupe of the compat report, the exact same error, some other mod is messing with the registries and recipes (as this doesn't happen with just BC, BCC and forestry)

**Closed by AEnterprise** 2018-04-17 17:05 UTC
Labels: status: needs investigation, status: possible duplicate, type: mod compat, version: 1.12.2
