### ISSUE TITLE
console spam from BC Couldn't load advancement

### ISSUE THREAD

**Issue by trilexcom** [BuildCraft/BuildCraft#3986] opened 2018-01-21 02:37 UTC
hi BuildCraft Team

We are getting Console spam from BC saying https://pastebin.com/dmUyzEjh

please let me know if this is a BC bug or i need to downgrade my forge to 2583?

Thanks again for your hard work i love your mod. 

have a wonderful weekend.

**BuildCraft** version: BuildCraft 7.99.14
**Forge** version: 2590 it wasn't doing that in Forge 2983 i had to upgrade forge due to tinkers requiring a higher Forge which is 2590
Link to crash report or log: https://pastebin.com/JQkhUVXF
Singleplayer or multiplayer: Multiplayer and Singleplayer
Additional information:

**Comment by AlexIIL** [comment] 2018-01-21 03:54
We shouldn't be spamming the console with that, so that part can be fixed on our end. I'd need to look into this in more detail to find out the cause.

Thanks for the report :)

**Comment by trilexcom** [comment] 2018-01-21 03:56
so when i place down the assembley table with one laser and i try to make iron chipset right after i start the engine using a lever laser goes live i get a console spam from BC

**Comment by AlexIIL** [comment] 2018-01-21 04:05
It sounds like something's removed or changed the advancement for when an assembly table is used, which isn't handled very well. Now isn't a very good time for me however, so I'll probably take a look into this later.

**Comment by trilexcom** [comment] 2018-01-21 04:08
its all good take your time. Thanks again for the help. your guys are awesome.

**Comment by trilexcom** [comment] 2018-01-22 01:43
alex should i close this ticket ? or do you want me to keep it open sense you fixed in dev? 

mat

**Closed** 2018-02-16 17:58 UTC
Labels: priority: high, status: fixed/implemented in dev, type: bug, version: 1.12.2
