### ISSUE TITLE
crash on world gen(7.99.4)(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [BuildCraft/BuildCraft#3662] opened 2017-06-10 02:20 UTC
bc:7.99.4
biomes: Biomesoplenty{6.1.0.2243}
forge: 1.11.2-2314

crash reports:
[crash-2017-06-10_12.10.02-server.txt](https://github.com/BuildCraft/BuildCraft/files/1065540/crash-2017-06-10_12.10.02-server.txt)
[crash-2017-06-10_12.05.58-server.txt](https://github.com/BuildCraft/BuildCraft/files/1065539/crash-2017-06-10_12.05.58-server.txt)
[crash-2017-06-10_11.58.43-server.txt](https://github.com/BuildCraft/BuildCraft/files/1065541/crash-2017-06-10_11.58.43-server.txt)

fml client latest:
http://puu.sh/wfMEv/be7e8d37c5.log

**Comment by afdw** [comment] 2017-06-10 02:25
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3640.

**Closed by afdw** 2017-06-10 02:25 UTC
Labels: duplicate, version: 1.11.2
