### ISSUE TITLE
7.99.12 implementing rf compatibility.

### ISSUE THREAD

**Issue by border999** [BuildCraft/BuildCraft#3890] opened 2017-12-04 18:12 UTC
Because there's no emerald pipe for good power flow in the current 1.12 version of Buildcraft.

**Comment by LuigiHutch** [comment] 2017-12-04 18:20
You can use wooden kinesis pipes to 'extract'/transfer MJ just fine.
RF compat request is a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3760

I don't see how the emerald kinesis pipe missing has any link to RF compat

**Closed** 2017-12-04 18:20 UTC
Labels: type: question

**Comment by AlexIIL** [comment] 2017-12-04 18:36
Note that power limits haven't been added yet (its still WIP) so there's no difference between wooden kinesis pipes and wooden diamond kinesis pipes (the new name for emerald kinesis pipes)

**Comment by border999** [comment] 2017-12-06 04:42
noted. And for Mr. Luigi, the statement about emerald pipes was because I was under the impression that the wooden kinesis pipe (Non-diamond) was limiting the output my engines could dish out at one time. Because it seems it can only do 200 MJ per second.
