### ISSUE TITLE
2 of 4 combustion engines hooked to Quarry building up energy perpetually

### ISSUE THREAD

**Issue by DragonwrathI** [BuildCraft/BuildCraft#3695] opened 2017-07-01 02:13 UTC
First I just want to say I'm new to Buildcraft and loving it!
Running 7.99.4 Alpha
I have a Quarry set up as best I can with colored quartz pipe carefully routed to supply both fuel(gaseous) and water to four combustion engines on it. I then have gold transport pipe carrying items from the top down a ways to the sorting center.
For some reason, 2 of the four engines buildup energy perpetually to the 10k MJ ceiling, and a third gradually climbs up as well. If I shut off the 2 that are building up there is no noticeable drop in quarry speed. Alternatively, if I shut down the engines that are not building up, the others will take over and the buildup will recede.
My understanding was that a quarry can take power of at least a half dozen combustion engines before peaking. Am I seeing a bug or is there another explanation?
On a side note which may be related? The items leaving through the gold pipe appear to be 'clogging'. They leave the quarry bunched tightly together, and then launch once in the middle of the first gold pipe segment. If this is normal then I apologize for wasting your time.

Thanks for all the time and effort you guys put into this, very cool Mod!

**Comment by AlexIIL** [comment] 2017-07-01 09:57
This is likely caused by the quarry having an internal limit of 10 MJ per tick. (Which is temporary)

**Comment by AEnterprise** [comment] 2017-07-01 10:02
i'm currently cleaning up and improving some of the quarry code, want me to bump up that limit (found some things we are constantly re-computing that is just a waste of ticktime)

**Comment by DragonwrathI** [comment] 2017-07-01 13:08
That makes sense then, no worries! I'm patient.
I'm running it in survival and calling it 'hard mode' so having fun with it. I'll keep an eye out for any obvious buggyness.
One other thing I found is major lag to near freeze if pumping oil and suddenly switching to water or vice versa. Had this happen most recently when an oil chamber had only gravel as a roof. pumping caused the blocks to update and fall opening the chamber to seawater, though it didn't start trying to pump water until the oil was completely gone.

**Comment by AEnterprise** [comment] 2017-07-01 13:11
pump performance has been massively improved for the next version so you shouldn't notice an big performance hits in cases like that

once the pump starts pumping oil it will indeed keep pumping oil until it can't find anymore with its hose

**Comment by AlexIIL** [comment] 2017-07-06 19:43
Fixed in https://github.com/BuildCraft/BuildCraft/commit/9b83b030198718988bca398e0d2904d6d0d206e7 -- 7.99.5 will be released shortly including it

**Comment by AlexIIL** [comment] 2017-07-06 21:13
Fixed in [7.99.5](https://www.mod-buildcraft.com/buildcraft-7995-alpha.html)

**Closed by AlexIIL** 2017-07-06 21:13 UTC
Labels: status: fixed/implemented in dev, type: bug, version: 1.11.2
