### ISSUE TITLE
Buildcraft Conflict

### ISSUE THREAD

**Issue by Leghtin** [BuildCraft/BuildCraft#4445] opened 2019-07-26 09:22 UTC
BuildCraft version: buildcraft-all-7.99.24.1
Forge version: 14.23.5.2838
Link to crash report or log:
 `---- Minecraft Crash Report ----

WARNING: coremods are present:
  CustomSkinLoader (CustomSkinLoader_Forge-14.10a.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64 dev.146.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/26/19 5:14 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: forestry.core.utils.InventoryUtil.internal_moveOneItemToPipe(Lnet/minecraftforge/items/IItemHandler;Lforestry/core/tiles/AdjacentTileCache;[Lnet/minecraft/util/EnumFacing;)Z
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:82)
	at forestry.farming.tiles.TileFarmHatch.updateServer(TileFarmHatch.java:66)
	at forestry.farming.multiblock.FarmController.updateServer(FarmController.java:247)
	at forestry.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:445)
	at forestry.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:81)
	at forestry.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:31)
	at forestry.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_347_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8424246568 bytes (8033 MB) / 9730785280 bytes (9280 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx10240m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version              | Source                                | Signature                                |
	|:------ |:-------------------- |:-------------------- |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2               | minecraft.jar                         | None                                     |
	| LCHIJA | mcp                  | 9.42                 | minecraft.jar                         | None                                     |
	| LCHIJA | FML                  | 8.0.99.99            | forge-1.12.2-14.23.5.2838.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2838         | forge-1.12.2-14.23.5.2838.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | buildcraftlib        | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | buildcraftcore       | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | buildcraftbuilders   | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | buildcrafttransport  | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | buildcraftsilicon    | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | buildcraftenergy     | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | ic2                  | 2.8.170-ex112        | industrialcraft-2-2.8.170-ex112.jar   | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | jei                  | 4.15.0.268           | jei_1.12.2-4.15.0.268.jar             | None                                     |
	| LCHIJA | forestry             | 5.8.1.322            | forestry_1.12.2-5.8.1.322.jar         | None                                     |
	| LCHIJA | buildcraftcompat     | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | buildcraftfactory    | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | buildcraftrobotics   | 7.99.24.1            | buildcraft-all-7.99.24.1.jar          | None                                     |
	| LCHIJA | customskinloader     | 14.10a               | CustomSkinLoader_Forge-14.10a.jar     | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
	| LCHIJA | cyclopscore          | 1.4.0                | CyclopsCore-1.12.2-1.4.0.jar          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | everlastingabilities | 1.5.1                | EverlastingAbilities-1.12.2-1.5.1.jar | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | waila                | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar           | None                                     |
	| LCHIJA | i18nmod              | 1.12.2-1.0.8         | i18nupdatemod-1.12.2-1.0.8.jar        | None                                     |
	| LCHIJA | inventorytweaks      | 1.64+dev.146.2180b27 | InventoryTweaks-1.64 dev.146.jar      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | mousetweaks          | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar         | None                                     |
	| LCHIJA | railcraft            | 12.0.0               | railcraft-12.0.0.jar                  | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | teastory             | 3.3.1-B30.413-1.12.2 | TeaStory-3.3.1-B30.413-1.12.2.jar     | None                                     |
	| LCHIJA | treechopper          | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar          | None                                     |
	| LCHIJA | wailaharvestability  | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar | None                                     |
	| LCHIJA | wawla                | 2.5.269              | Wawla-1.12.2-2.5.269.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | xaerominimap         | 1.17.3               | Xaeros_Minimap_1.17.3_Forge_1.12.jar  | None                                     |
	| LCHIJA | immersiveengineering | 0.12-88              | ImmersiveEngineering-0.12-88.jar      | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
CustomSkinLoader (CustomSkinLoader_Forge-14.10a.jar)
  customskinloader.forge.loader.LaunchWrapper
IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64 dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Leghtin'/2255, l='weadw', x=242.55, y=67.23, z=221.96]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 417.71
	OpenGlRenderer: GeForce GTX 1060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`
Singleplayer or multiplayer: single
Steps to reproduce: Put forest mod, set a multiblock structure in Forest, and game will crash
Additional information:

**Comment by AlexIIL** [comment] 2019-07-26 16:13
This is a duplicate of https://github.com/BuildCraft/BuildCraft/issues/4326 (which is a forestry issue reported here: https://github.com/ForestryMC/ForestryMC/issues/2343)

Fortunately the fix is simple: update forestry to one of the most recent beta builds (probably [5.8.2.387](https://www.curseforge.com/minecraft/mc-mods/forestry/files/2684780))

**Closed** 2019-08-02 08:04 UTC
Labels: status: duplicate, status: fixed in other mod, type: bug, type: mod compat, version: 1.12.2, version: out-of-date
