### ISSUE TITLE
Buildcraft Fluids causing FPS drop

### ISSUE THREAD

**Issue by MissPotato** [BuildCraft/BuildCraft#3924] opened 2017-12-21 01:29 UTC
**Buildcraft** version: 7.99.12
**Forge** version: 14.23.1.2566
Singleplayer/multiplayer: Both, speicifcly Client Render

Additional information:
It seems like Buildcraft Fluids are taking a long time to render.  Turning on "Terrain Animations" in optifine can tank FPS from 50 down to 35. With root.tick.texture.AtlasSpriteFluid.update jumping up from 0.00% onto the order of 10.5-11.5% of rendering time, as displayed in the image below.
 The only Buildcrat fluid nearby is a small pond of oil, despite all the fluids jumping up in load. Don't let the image deceive you, the various fluids take turns sitting at the top of the list. 

https://i.imgur.com/AIMYqMY.png

**Comment by AEnterprise** [comment] 2017-12-21 07:22
so if you leave that off or remove optifine there is no fps impact?

**Comment by AlexIIL** [comment] 2017-12-21 12:32
This happens normally if someone's computer cannot handle animating the 60 fluid textures, in this case optifine just provides a simple way to disable it.

**Comment by MissPotato** [comment] 2017-12-21 23:54
Optifine adds the option to disable the animations. Without Optifine, there is no way to disable the animations short of a resource pack. That being said, none of the other animated fluids seem to have this kind of impact. Molten fluid from TCon, or even water/lava barely make a dent on render time.

**Comment by AlexIIL** [comment] 2017-12-22 02:14
I'd assume its because minecraft has about ~10 animated textures, TCon has ~8 animated textures (total), and we have about 60.

**Comment by MissPotato** [comment] 2017-12-22 17:17
It is, but it shows the dedication and love.

**Comment by AEnterprise** [comment] 2017-12-23 18:32
duplicate of #3616

**Closed by AEnterprise** 2017-12-23 18:32 UTC
Labels: type: bug, version: 1.12.2
