### ISSUE TITLE
Transport pipe Index out of range exception

### ISSUE THREAD

**Issue by Swornh** [BuildCraft/BuildCraft#3597] opened 2017-05-21 06:06 UTC
The Setup: A Stirling engine direct facing a pump, above a lava lake, output direct into cobble stone fluid pipe, into tinkers smelter tank and "smelter tank".

working fine after empty the lake, then crash from nothing...
Game won't start again.

[crash-2017-05-21_01.52.34-client.txt](https://github.com/BuildCraft/BuildCraft/files/1016689/crash-2017-05-21_01.52.34-client.txt)

**Comment by afdw** [comment] 2017-05-21 06:09
Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3596.

**Closed by afdw** 2017-05-21 06:09 UTC
Labels: 1.11.2, bug
