### ISSUE TITLE
BC 7.2.5: Rendering of fuel tanks is buggy

### ISSUE THREAD

**Issue by rapus95** [BuildCraft/BuildCraft#3297] opened 2016-04-11 09:51 UTC
![2016-04-11_11 42 10](https://cloud.githubusercontent.com/assets/5960902/14423177/a9ee3dd6-ffda-11e5-9d8d-da148ee64a1f.png)
![2016-04-11_11 42 20](https://cloud.githubusercontent.com/assets/5960902/14423178/a9ef92a8-ffda-11e5-9c7c-a8b74df6cae6.png)

As you can see that the fuel "overlays" the tank texture (that's probably why the empty tank just renders fine)
My setup uses Optifine (in the pictures using default settings, thus most advanced stuff disabled)

Can this be fixed in the mods code (since both fuel and tank are part of buildcraft) or is this error only depending on the render pipeline (depth test etc) and thus a minecraft problem?

**Comment by iTitus** [comment] 2016-04-11 10:13
1. Does this happen without Optifine?
2. Does this happen if you get closer?

**Comment by rapus95** [comment] 2016-04-11 10:18
Yes, it happens w/o optifine too.

It stops flickering (and looking buggy) at a distance of ~10 blocks (when facing front)

**Comment by iTitus** [comment] 2016-04-11 10:21
I think the ε value needs to be bigger.

**Comment by Kubuxu** [comment] 2016-04-11 10:25
Or dynamic depending on the player distance but I don't know how hard it would be to do.

**Comment by rapus95** [comment] 2016-04-11 10:26
what ε value?

**Comment by rapus95** [comment] 2016-04-11 10:27
well i assume i got it: the amount the fuel block is smaller than the tank block?

**Comment by iTitus** [comment] 2016-04-11 10:31
Yes ;)

**Comment by rapus95** [comment] 2016-04-11 18:36
My OpenGL skills are rather bad but maybe you could solve the issue by rendering in the opposite order

**Comment by AlexIIL** [comment] 2016-04-11 19:09
That's not how openGL works :P

Currently the fluid renders ````99.9%```` of the tank size. Thats quite close though, changing it to ~````99%```` would probably fix it

**Comment by AlexIIL** [comment] 2016-04-11 19:26
This should be fixed for 7.2.6.

**Closed** 2016-04-11 19:26 UTC

**Comment by rapus95** [comment] 2016-04-11 20:48
Just knowledge things:
@AlexIIL i thought the problem resulted out of the depth test which evaluated in some sort of same depth making one color overwriting the other color (or doing not) thus the flickering. Only thing i don't know is whether the color data is overwritten when having same depth or preserved. But either way rendering tank & fluid block in the opposite order should make the right one being rendered on top, shouldn't it? Or would it only "exchange" the wrong parts with the currently right parts?

**Comment by AlexIIL** [comment] 2016-04-11 21:58
````
But either way rendering tank & fluid block in the opposite
order should make the right one being rendered on top, shouldn't it?
````
You ARE correct about what depth testing is and how it happens, however I cannot change the order that they are rendered (the tank block is rendered in batches in mini-chunks, and the fluid is rendered indervidually per-tank per-frame).

The issue is that floating point calculations are not perfect (loss of precision and not requiring them to be for performance) and so the depth of each pixel is not its true value but one slightly off. Normally this isn't a problem because the difference in position between each polygon is bigger than the loss in precision, but if the polygons are close enough then the losses become grater than the difference, and it causes a depth-fight.

When you get closer to the screen it can use more precision, and so you get less depth-fighting. 

````
Only thing I don't know is whether the color data is overwritten
when having same depth or preserved
````
OpenGL allows you to specify how the depth test is evaluated, out of the 5 basic number comparisons. (Function spec on OpenGL depth testing functions [here](https://www.opengl.org/sdk/docs/man/docbook4/xhtml/glDepthFunc.xml)). I don't know which one minecraft uses but it doesn't really affect the result.
