### ISSUE TITLE
Gate actions with parameter

### ISSUE THREAD

**Issue by tokoku-11** [BuildCraft/BuildCraft#2454] opened 2015-02-10 11:58 UTC
I can choose parameter only Pipe disconnecting side on Gate Actions (Closed, Open, Input Only, Output Only) in Quartz and Emerald Gate

**Comment by AEnterprise** [comment] 2015-02-10 13:03
that is the intended behaviour IIRC

**Comment by tokoku-11** [comment] 2015-02-10 14:10
I don't understand Pipe actions by Gate actions with parameter:Pipe disconnecting side.

**Comment by tokoku-11** [comment] 2015-02-10 15:09
Why?
![2015-02-11_00 07 02](https://cloud.githubusercontent.com/assets/7271486/6129486/2af7de80-b182-11e4-899b-afdbbf70bd0c.png)

![2015-02-11_00 01 10](https://cloud.githubusercontent.com/assets/7271486/6129477/1e1c3404-b182-11e4-92b2-c092637ddc13.png)

![2015-02-11_00 00 23](https://cloud.githubusercontent.com/assets/7271486/6129492/38bfbae2-b182-11e4-908e-15203512dccd.png)

![2015-02-11_00 03 20](https://cloud.githubusercontent.com/assets/7271486/6129497/3ec832ca-b182-11e4-9882-1f58064d0173.png)

**Comment by SandGrainOne** [comment] 2015-02-10 15:17
The "S" (lower left corner of the icon) in the action parameter stands for "South". Have you made sure "South" is the side you want to disconnect? We can't see the directions of your construction.

**Comment by tokoku-11** [comment] 2015-02-10 15:20
Gate side is South.

**Comment by AEnterprise** [comment] 2015-02-10 15:25
you don't need to specify the gate side but the side you want to close

**Comment by tokoku-11** [comment] 2015-02-10 15:43
I understand I don't need to specify the gate side.
Why can gate choose the gate side ?
and 
Why do Fluid Pipe branch rule change by Gate action ?

**Comment by SandGrainOne** [comment] 2015-02-11 07:30
I think Tokoku would like to see the option to select "south" to be hidden because the gate is already blocking the South side by being placed there.

I don't understand the other question.

**Comment by AEnterprise** [comment] 2015-02-11 11:24
yeah that part i understand now but the other is indeed a something i also don't understand

@tokoku-11 could you please try to explain what you mean in other words? maybe a longer explanation so it is more clear to us or so we can fill in the gaps from context? or maybe ask someone else to help you word it cause as long as we don't understand what you mean we sadly can't help

**Comment by tokoku-11** [comment] 2015-02-11 11:48
Sorry. My English ability is not native level.
So I upload a video clip.
http://youtu.be/cSEjeEc91vk

**Comment by AEnterprise** [comment] 2015-02-11 11:53
ok, you are closing the south side but there is no connection there so it shouldn't allow that and my guess is that that is causing the issue you are having, close of the side the water shouldn't go to (in this case north or east)

**Comment by tokoku-11** [comment] 2015-02-11 12:03
That's right.

**Closed** 2015-02-18 10:41 UTC
Labels: bug-major
