### ISSUE TITLE
Take liquid with bucket in GUI of machines not working

### ISSUE THREAD

**Issue by Azuxul** [BuildCraft/BuildCraft#3956] opened 2018-01-01 11:38 UTC
**BuildCraft** version: 7.99.13
**Forge** version: 14.23.1.2565
Singleplayer or multiplayer: multiplayer
Additional information:

Hi,

Take liquid with bucket in a GUI (tested with chocolate engine and chocolate separator) not working. Bucket empties when i leave the GUI and liquid level drop.

Video : https://i.azuxul.fr/a8109a0e493.mp4

**Comment by AEnterprise** [comment] 2018-01-01 15:06
technicaly a dupe of #3886 , that gui is bugged in general when it comes to putting in and taking out fluids

**Closed by AEnterprise** 2018-01-01 15:06 UTC
