### ISSUE TITLE
wierd server message dealing with pipe when added buildcraft 7.2.3

### ISSUE THREAD

**Issue by SDUBZ** [BuildCraft/BuildCraft#3270] opened 2016-03-25 16:30 UTC
i loaded into my server and got this message with latest version of the 1.8.9 buildcraft 7.2.3 heres the message  A BuildCraft pipe @ BlockPos{x=255, y=64, z=319} could not save pipe ID! Please report to developers!

http://pastebin.com/Au9TDypE

**Comment by AlexIIL** [comment] 2016-03-25 17:43
Can I have a full log file please? I'm wondering what type of pipe might be at 

Can you try re-running your server with [this](https://www.dropbox.com/s/x82ya6fqnaqdzs0/buildcraft-7.2.3-test1.jar?dl=0) jar file? It adds a bit more info to the log so I know what is going on here.

**Comment by SDUBZ** [comment] 2016-03-25 17:47
yes will do as soon as i have a backup downloaded before i do anything else thanks for patience in advanced

**Comment by SDUBZ** [comment] 2016-03-25 18:01
im trying to find the log that had these blocks postion in it and i cant see it in the logs anywhere O_O

**Comment by SDUBZ** [comment] 2016-03-25 18:41
tested that file you got me to add here's the latest log

[fml-server-latest.txt](https://github.com/BuildCraft/BuildCraft/files/189900/fml-server-latest.txt)

**Comment by AlexIIL** [comment] 2016-03-25 18:45
thanks

**Comment by SDUBZ** [comment] 2016-03-25 19:08
just thought id let you know the block in question in singleplayer of the server world is invisible but there and i can jump on it etc

**Comment by oitsjustjose** [comment] 2016-03-26 00:07
@AlexIIL I was just about to come on here and report this crash bug (the one attached in SDUBZ's next-to-most-recent comment). It's keeping my server from launching now :(

[Here's my log just for giggles, it's basically the same](http://puu.sh/nU2c0/3ce735db52.txt)

**Comment by AlexIIL** [comment] 2016-03-27 00:44
Can you try with [this](https://www.dropbox.com/s/tzk9ngtcsohhgau/buildcraft-7.2.4-test1.jar?dl=0) jar? It shouldn't crash this time, but it will put out a bunch of log data with more info.

**Comment by oitsjustjose** [comment] 2016-03-27 00:45
giving it a shot right now!

**Comment by oitsjustjose** [comment] 2016-03-27 00:48
Yup, definitely not crashing anymore! Thanks! :heart:

**Comment by AlexIIL** [comment] 2016-03-27 00:49
Can I have your server log? All of the pipes might have just vanished

**Comment by oitsjustjose** [comment] 2016-03-27 00:51
Oh..uh. Heh. Sure.

[Here you are](http://puu.sh/nVcc5/73f4679dca.log)

Haven't had a chance to actually log in and see what's going on. Fortunately (and unfortunately at the same time) we weren't using BC Pipes too heavily.

**Comment by AlexIIL** [comment] 2016-03-27 00:54
From the looks of it only 2 pipes have vanished, and neither of them saved a pipeId. Odd.

**Comment by AlexIIL** [comment] 2016-03-27 00:55
I'm hoping that you didn't only have 2 pipes in your loaded chunks, as then it would mean that all of them have vanished.

**Comment by oitsjustjose** [comment] 2016-03-27 01:00
Nope, just logged in - my nether pump's pipes were all there!

**Comment by Cleardragonf** [comment] 2016-04-08 16:53
I too found an issue that i'm curious about...this happens when ever we use a pump on a server here's the log.

[http://pastebin.com/XXHaVhzi](url)

**Comment by AlexIIL** [comment] 2016-04-08 17:20
I think you did that pastebin link wrong :P

**Comment by AlexIIL** [comment] 2016-04-08 17:45
@Cleardragonf Your issue is a duplicate of #3292 , but thanks for bumping it.

This issue *should* have been fixed by 7.2.5.

**Closed by AlexIIL** 2016-04-08 17:45 UTC
Labels: bug

**Comment by Cleardragonf** [comment] 2016-04-14 22:17
Ok but it didn't...that's what I'm getting at i still get that error message.

**Comment by Cleardragonf** [comment] 2016-04-14 22:18
i use 7.2.5 from the buildcraft webpage but everytime i place that pump down on a server it crashes with that message...and then i need to recreate a new world.

**Comment by AlexIIL** [comment] 2016-04-14 22:26
Oh right, I mixed up the version numbers- it will be fixed for 7.2.6, which is currently in the pipeline. Sorry.
