### ISSUE TITLE
Oil Refinery Isn't Working. Bug

### ISSUE THREAD

**Issue by Kaktusik75** [BuildCraft/BuildCraft#3950] opened 2017-12-28 22:25 UTC
**Build Craft** version: 7.99.13
**Forge** version: 1.12.2-14.2.3.1.2582
Singleplayer 
Additional information: Everything was checked twice and it still isn't working I even rebuilt my whole system still didn't work, a bug I'm guessing.
![not working](https://user-images.githubusercontent.com/34925254/34424629-fa19ea50-ec1c-11e7-9cee-90f18ea100e8.png)
![not working 2](https://user-images.githubusercontent.com/34925254/34424630-fe3cf028-ec1c-11e7-8ddd-a5851afc4ce2.png)
![not working 3](https://user-images.githubusercontent.com/34925254/34424633-028cd652-ec1d-11e7-83f8-9593821a44a2.png)

**Comment by LuigiHutch** [comment] 2017-12-28 22:34
Thanks for the report. That is actually the distiller as the refinery is not more. BC oil processing has been completely redone. Here is a basic guide about how the new blocks work: http://imgur.com/a/AXUOX

For your setup in short, you need to extract the fluids out the top and bottom :)

Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3737

**Closed** 2017-12-28 22:36 UTC
Labels: type: not a bug
