### ISSUE TITLE
Energy module causes lags

### ISSUE THREAD

**Issue by UltiMaxCZ** [BuildCraft/BuildCraft#4064] opened 2018-03-04 12:40 UTC
BuildCraft version: 7.99.15
Forge version: 14.23.2.2611
Debug: [profile-results-2018-03-04_12.20.07.txt](https://github.com/BuildCraft/BuildCraft/files/1778426/profile-results-2018-03-04_12.20.07.txt)
Singleplayer or multiplayer: Singleplayer

If I have full Buildcraft (all 7 modules), I have 1-10 FPS, but when I remove Energy module, I have 60 FPS. I have BC mainly for quarry, which can be (afaik) powered only by engines from Energy module, so...

Also every 25-45 seconds my FPS drop from 50-60 (without energy m.) to ±25. I don't know which part of BC causes it, but it's not such a serious problem which would make the game unplayable.

**Comment by AEnterprise** [comment] 2018-03-04 12:44
there already some known performance issues this would fall under (https://github.com/BuildCraft/BuildCraft/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+performance%22)

the FPS lag can in singleplayer sometimes affect TPS, also some parts of BC are not so well optimized, the fps dips are probably the GC cleaning up, how much ram do you have allocated?

**Comment by AlexIIL** [comment] 2018-03-04 12:49
I'd assume this is caused by the same problem as #3616: can you find the most expensive element in the client debug pie?

**Comment by UltiMaxCZ** [comment] 2018-03-04 13:09
Memory: 3059MB, 40% used
Allocated: 2380MB, 77% used

Debug is in the post, i dont know much about it (what all these values mean).

**Comment by AlexIIL** [comment] 2018-03-04 13:11
Oh, by debug pie I mean the circle that comes up when you press "shift + F3" rather than just F3.

**Comment by afdw** [comment] 2018-03-04 13:24
One you provided is from server, not client, so it's much less related to FPS.

**Comment by UltiMaxCZ** [comment] 2018-03-04 13:35
Oh, sorry.

**Pie:** Tick - 90-95%; gameRender - 4-10%; display_update - 1%
![2018-03-04_14 33 44](https://user-images.githubusercontent.com/37039638/36946172-079e51aa-1fb9-11e8-80e5-497ed8d192bb.png)

**Comment by UltiMaxCZ** [comment] 2018-03-04 20:15
Now without Energy module.
New sandstone flatmap, no mobs.
![2018-03-04_21 14 32](https://user-images.githubusercontent.com/37039638/36950072-1e46a9b0-1ff1-11e8-9af5-5b2197f3d50b.png)

**Comment by AEnterprise** [comment] 2018-03-04 20:16
with energy module added can you navigate in the pie chart (use the numbers next to the slices at the bottom to go in or 0 to go up) to find what using all that time in tick?

**Comment by UltiMaxCZ** [comment] 2018-03-04 21:37
I dont know what exactly Atlas Sprite is, but can I disable/remove it? Because it looks like Atlas sprite causes the lags.

**Comment by AlexIIL** [comment] 2018-03-04 21:44
The animated fluid textures. That would make this a duplicate of #3616.

**Closed by AlexIIL** 2018-03-04 21:44 UTC
Labels: status: duplicate, status: needs investigation, type: performance, version: 1.12.2

**Comment by AlexIIL** [comment] 2018-03-04 21:46
(Currently the only way of disabling them is to use [this resource pack](https://mod-buildcraft.com/releases/Misc/packs/buildcraft_fluid_still.zip)).

**Comment by UltiMaxCZ** [comment] 2018-03-04 22:20
It helped, thanks!
