### ISSUE TITLE
Adding gate to pipe with docking stations causes crash

### ISSUE THREAD

**Issue by pwholmes** [BuildCraft/BuildCraft#2494] opened 2015-02-25 17:56 UTC
I decided to finally try out robots in the new Buildcraft 6.4.0 release, but didn't have much luck.  In fact I never even got to place any robots in the world.  I put down a single isolated structure pipe, added two or three docking stations to it, added an iron AND gate, started to flip through the possible actions in the gate's UI... and BAM!  End of the world.  The world now crashes on startup with the same error every time.  Here's the top of the crash report; I can add the rest if requested:

Description: Ticking block entity

java.lang.AbstractMethodError: buildcraft.transport.TileGenericPipe.getWorldObj()Lnet/minecraft/world/World;
	at buildcraft.robots.statements.ActionRobotGotoStation.actionActivate(ActionRobotGotoStation.java:55)
	at buildcraft.transport.Gate.resolveActions(Gate.java:483)
	at buildcraft.transport.Pipe.updateEntity(Pipe.java:156)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:385)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at buildcraft.robots.statements.ActionRobotGotoStation.actionActivate(ActionRobotGotoStation.java:55)
	at buildcraft.transport.Gate.resolveActions(Gate.java:483)
	at buildcraft.transport.Pipe.updateEntity(Pipe.java:156)
	at buildcraft.transport.TileGenericPipe.func_145845_h(TileGenericPipe.java:385)

-- Block entity being ticked --
Details:
	Name: net.minecraft.src.buildcraft.transport.GenericPipe // buildcraft.transport.TileGenericPipe
	Block type: ID #623 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-841,79,-264), Chunk: (at 7,4,8 in -53,-17; contains blocks -848,0,-272 to -833,255,-257), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #623 (tile.pipeBlock // buildcraft.transport.BlockGenericPipe)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

**Comment by hea3ven** [comment] 2015-02-25 18:47
Duplicate of #2486

**Comment by asiekierka** [comment] 2015-02-25 20:54
It was a beta after all. Stable on Saturday.

**Closed** 2015-02-25 20:55 UTC
Labels: duplicate
