### ISSUE TITLE
Some of ur items making journey map fullscreen turn bluescreen 

### ISSUE THREAD

**Issue by zacharyhenry** [BuildCraft/BuildCraft#4411] opened 2019-05-24 02:49 UTC
BuildCraft version: 7.99.24.1
Forge version: 14.23.5.2838
Singleplayer 
Steps to reproduce: 

1.Known items that making journeymap v5.5.5b7 go bluescreen 

2.Quarry 
3.redstone engine
4.stirling engine
5.combustion engine
6.creative engine
7.Item.volume_box.name (how do u break this from overworld) (dont put this in ur world u can't get rid of it makes it where fullscreen map doesn't work at all)
8.Mining Well
9.Distiller

Additional information: 
https://www.youtube.com/watch?v=nqpnCUVDHe8

Journeymap issue related to this post

https://github.com/TeamJM/journeymap/issues/114

https://github.com/BuildCraft/BuildCraft/issues/4199#issuecomment-495796581

**Comment by AEnterprise** [comment] 2019-05-25 07:47
this is a duplicate of #4199 feel free to add your list of items that cause this there

**Closed by AEnterprise** 2019-05-25 07:47 UTC
Labels: status: needs investigation, type: bug, type: mod compat, version: 1.12.2
