### ISSUE TITLE
Guide Book doesn't works 1.11.2

### ISSUE THREAD

**Issue by sowdowdow** [BuildCraft/BuildCraft#3584] opened 2017-05-15 08:25 UTC
It's like the guide book doesn't work.
![image](https://cloud.githubusercontent.com/assets/26247667/26048513/bae987aa-3957-11e7-8d55-f6c630862170.png)
When I click on the different tabs, nothing happen (Except the three red buttons and "pluggables")
+ Distiller as no texture.

Sorry my english is really bad :x
B.C. : 7.99.3
Forge : 8.0.99.99

**Comment by LuigiHutch** [comment] 2017-05-15 09:11
The distiller missing icon is a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3574. And you have to move around the guide by clicking on the icons/names directly as the guide is currently WIP and incomplete

**Closed** 2017-05-15 15:59 UTC
