### ISSUE TITLE
[7.1.16 - 1.7.10] Builder causes players to time out

### ISSUE THREAD

**Issue by GiovanniPorta** [BuildCraft/BuildCraft#3362] opened 2016-06-01 16:35 UTC
A player on our server put a BC builder together and now anyone who gets near the area consistently times out, and the serverside logs show nothing of importance except that the player "disconnected"

**Comment by AlexIIL** [comment] 2016-06-01 16:52
Do the clients have any information (crashes, errors or other problems) in their logs?

**Comment by GiovanniPorta** [comment] 2016-06-01 17:10
No, just a network timeout in the client log.
```
[09:41:15] [Netty Client IO #4/ERROR] [FML/]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
```

Basically what happens is the client goes near the Buildcraft builder. Everything is working fine, and you can see the builder "spitting out" blocks as it is building. But a few seconds later everything stops, and then you time out. I also recorded CPU spikes of about 40% for the server when this was happening.

The builder was tested with the same blueprint in singleplayer and there were no issues.

**Comment by AEnterprise** [comment] 2016-06-01 20:17
can you give a full client log of this heapening and a server one to match? might be more info about the cause in there

**Comment by GiovanniPorta** [comment] 2016-06-01 21:04
The logs are way to big to paste, so I'll just upload snippets.
[
Relevant part of the server log](https://gist.github.com/GiovanniPorta/fb9e1aa2f39c1261c0a5c8d49898c337) - _shows time outs of two clients_

[Client log from join to time out](https://gist.github.com/GiovanniPorta/09921c2742a5b207f3fcbd9a2b73fb15#file-fml-client-log-L1281) - _time out @ 09:41:15_

**Comment by AEnterprise** [comment] 2016-06-02 11:31
so it looks like the cpu usage spikes to 100% when this heapens that means the timeouts are not directly buildcrafts fault but your server getting overloaded the client to not get it's response packets in time causing the timeout

what are the server specs? it might not have enough ram allocated

**Comment by GiovanniPorta** [comment] 2016-06-02 15:56
I doubt it's an issue with the server specs.

Server is a VM with 8GB of RAM and 2 vCores of an E5-2670v3.

I can run robots and build with those without spiking the CPU whatsoever, but the moment a builder block is used instead, it causes issues.

**Comment by AEnterprise** [comment] 2016-06-02 18:15
hmm, then it must indeed be the builder but it's odd

**Comment by AEnterprise** [comment] 2016-06-25 09:13
is this also a problem on 1.8? if not this can be closed

maybe also resolved with the 8.0 rewrite?

**Comment by AlexIIL** [comment] 2016-06-25 13:20
Yeah its possible that its a large blueprint and we try to do too much checking in a single tick. Or perhaps its too much traffic being generated.

**Comment by GiovanniPorta** [comment] 2016-06-25 19:03
The same issue occurs with the quarry so it has nothing to do with blueprints.

**Comment by Revemohl** [comment] 2016-07-23 07:10
I've noticed this problem as well, but with the quarry as Giovanni mentioned. Since it's a common issue for those two blocks, could it somehow be related to the red deletion blocks that they spit out?

**Comment by AlexIIL** [comment] 2016-07-23 11:36
Both the quarry and the builder use the same blueprint builder code (the quarry just generates a blueprint for the shape and size of the quarry, and it's the same with the filler for all its different types).

The red breaking blocks are an animation, and are done in the same way that other blocks going out of the blueprint are. I'm not sure how they could be todo with it though, other than showing that the issue occurs when it's building its blueprint.

**Comment by Revemohl** [comment] 2016-07-25 10:53
One possibility that came up is that VeinMiner, more specifically version 0.34.1, is the one causing this (it didn't happen on 0.31.6 when I went back to it, at least for the quarry). Do you have that mod in your pack?

**Comment by GiovanniPorta** [comment] 2016-07-25 12:17
No, VeinMiner is not in the pack. Link to the list of mods be seen on my first reply.

**Comment by GiovanniPorta** [comment] 2016-08-16 22:30
Might this have anything to do with running the server on a Haswell processor? I can try moving the server to an Ivy Bridge machine.

For the record, it's running on a Google Cloud VM.

**Comment by AEnterprise** [comment] 2016-08-31 12:46
no the processor shouldn't have anything to do with it on it's own, most likely the server just can't keep up with everything that is going on

**Comment by GiovanniPorta** [comment] 2016-09-02 05:54
@AEnterprise if you count "everything that is going on" as 1 person using a builder/quarry/whatever, then I find that hard to believe, especially since it works fine in singleplayer on a computer with inadequate specifications.

**Comment by AEnterprise** [comment] 2016-09-02 06:37
yes but how strong is that server? how much ram does it have allocated?

**Comment by GiovanniPorta** [comment] 2016-09-02 06:40
@AEnterprise you asked this already.

https://github.com/BuildCraft/BuildCraft/issues/3362#issuecomment-223336557

**Comment by AEnterprise** [comment] 2016-09-02 06:55
yes but i rered that and you say it's a VM with 8GB, that doesn't mean you allocated 8GB to minecraft, i'm basicly asking to verify how much is allocated

**Comment by AEnterprise** [comment] 2016-09-17 13:43
#3431

**Closed by AEnterprise** 2016-09-17 13:43 UTC
Labels: 1.7.10, bug, needs investigation, performance
