### ISSUE TITLE
buildcraftcore:goggles

### ISSUE THREAD

**Issue by sfxworks** [BuildCraft/BuildCraft#4213] opened 2018-06-26 06:54 UTC
BuildCraft version: buildcraft-7.99.17
Forge version: 14.23.4.2705
Singleplayer or multiplayer: Multiplayer 
Steps to reproduce:  On launch / Server start
Additional information:  When starting the server, I get some logspam regarding some invalid json. This happens when loading parts of the world during the phase where it prepares spawn.

Link to crash report or log: 
```
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'buildcraftcore:goggles'
        at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
        at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
        at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:202) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
        at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1357) ~[ForgeHooks.class:?]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1339) [ForgeHooks.class:?]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1313) [ForgeHooks.class:?]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:792) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3151]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:760) [WorldManager.class:1.12.2-2705-7.1.0-BETA-3151]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3540) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by LuigiHutch** [comment] 2018-06-26 09:03
Thanks for the report! This is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3865

**Closed** 2018-06-26 12:02 UTC
