### ISSUE TITLE
[Minor] com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'buildcraftcore:goggles'

### ISSUE THREAD

**Issue by kane-thornwyrd** [BuildCraft/BuildCraft#3979] opened 2018-01-19 06:45 UTC
**BuildCraft** version: 7.99.15-pre4
**Forge** version: 1.12.2-14.23.1.2590
Link to crash report or log: N/A
Singleplayer or multiplayer: Server-side
Additional information: 
Just got an easy error to fix, nothing too severe, doesn't crash the game
```
[06:25:38] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement buildcraftcore:goggles
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'buildcraftcore:goggles'
	at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
	at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
	at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:202) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1342) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1324) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1298) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by 3TUSK** [comment] 2018-01-19 07:20
Duplicate of #3865

**Closed as completed** 2018-01-19 07:45 UTC
