### ISSUE TITLE
Filler not working

### ISSUE THREAD

**Issue by Redwoodstudio** [BuildCraft/BuildCraft#4004] opened 2018-01-28 10:48 UTC
Hello, I tried to use a filler but gui didn't open.

BuildCraft version: newest (7.99.14)
Forge version: 1.12.2-14.23.1.2555
Singleplayer or multiplayer: Singleplayer
Additional information: I didn't see a recipe in JEI

**Comment by LuigiHutch** [comment] 2018-01-28 10:51
Thanks for the report! This is actually a duplicate of https://github.com/BuildCraft/BuildCraft/issues/3971 

1. You need to connected to landmarks to access the GUI

2. Some recipes in 7.99.x are missing, that is because they are blocks which are unfinished and aren't ready to be used in survival.

**Comment by Redwoodstudio** [comment] 2018-01-28 10:53
ok, thanks

**Closed** 2018-01-28 10:52 UTC
