### ISSUE TITLE
I have a problem installing Buildcraft on 1.11.2(with more mods)

### ISSUE THREAD

**Issue by Snowpig7u** [BuildCraft/BuildCraft#3732] opened 2017-07-14 12:13 UTC
Im not really expirienced on installing mods, so i will try to leave some details:
Buildcraft version-7.99.5 ! game crashes after installing buildcraft and leaving no
hints other than the crash report. Ive tried the mod load alone removing any mods 
from the mods file and surprisingly it works.
My guess is that there is a mod interaction giving problems.
These is my last crash report:
[crash-2017-07-14_15.06.37-client.txt](https://github.com/BuildCraft/BuildCraft/files/1148327/crash-2017-07-14_15.06.37-client.txt)

**Comment by LuigiHutch** [comment] 2017-07-14 12:20
Thanks for the report! This is actually a Mekanism issue, see: aidancbrady/Mekanism#4513 for details. Duplicate of https://github.com/BuildCraft/BuildCraft/issues/3716

**Closed** 2017-07-14 13:49 UTC
