### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by coder-carl** [BuildCraft/BuildCraft#4394] opened 2019-04-15 10:58 UTC
BuildCraft version: buildcraft-all-7.99.23
Forge version: 2815
Link to crash report or log: 
Singleplayer or multiplayer: 
Steps to reproduce: 
Additional information: 
https://paste.ubuntu.com/p/kFdvVjdmNp/

**Comment by AEnterprise** [comment] 2019-04-15 12:19
this is caused by extrautils2 not implementing the IProperty interface, buildcraft just detects and logs it, but it's something that needs to be fixed on the ex2 side

**Closed by AEnterprise** 2019-04-15 12:19 UTC
