### ISSUE TITLE
Not everything is craftable

### ISSUE THREAD

**Issue by thill1999** [BuildCraft/BuildCraft#3591] opened 2017-05-19 14:17 UTC
as much as i try to it wont let me craft a quarry

**Comment by AEnterprise** [comment] 2017-05-19 14:22
BC version?

also not all BC items are suposed to be craftable as some are still WIP

**Comment by AEnterprise** [comment] 2017-05-19 14:32
quarry does have a recipe in 7.99.3, duplicate of #3527

**Closed by AEnterprise** 2017-05-19 14:32 UTC
Labels: not a bug
